### ISSUE TITLE
[Remote-SSH Bug]: Unbound variable 'wgetTriesSegment' in script 'linux-exec-server-installer.sh'

### ISSUE THREAD

**Issue by Krystifer** [microsoft/vscode-remote-release#10231]
- VSCode Version: 1.93.0
- Local OS Version: Windows 11 Home Single Language
- Remote OS Version: Linux

Hi, I'm trying to use remote SSH extension to connect to a computer cluster with Linux OS, from VSCode, I own an account in the cluster, so I configured the user, hostname, etc in the configuration file. I followed the steps in https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh to do that. However, when I initiate the connection I got the error: ''Unbound variable 'wgetTriesSegment' in script 'linux-exec-server-installer.sh'' as shown in the screenshot. It seems to be an error in the script, I can go to the location of that script in my computer and I can identify the variable, but I'm not sure of what is causing this variable to be bad defined. The connection is not even initiated since I'm not asked to write a password, and I haven't defined authentication keys in the configuration file. 

PD: I'm new on bash commands and Linux OS.

![Screenshot 2024-09-05 170523](https://github.com/user-attachments/assets/ed093b73-9d38-442e-a692-de097033ded4)
![Screenshot2](https://github.com/user-attachments/assets/661244a2-e5a9-472a-ba30-df88a4901f0b)

**Comment by joshspicer** [comment]
Thanks for sharing. I think i've fixed this in the latest pre-release build (`v0.115.2024090521 (pre-release)`). Mind giving it a try?

**Comment by Krystifer** [comment]
> Thanks for sharing. I think i've fixed this in the latest pre-release build (`v0.115.2024090521 (pre-release)`). Mind giving it a try?

Thanks for your answer. Installing the pre-release version doesn't fix the error, I downgrade to `v0.113.1` and it works.

**Comment by joshspicer** [comment]
Ah, I see the issue. That value is influenced by the `remote.SSH.localServerDownload` setting.  When set from the default (`auto`) to `off` the script incorrectly interprets the empty value as an error.

I suspect that you have that setting set to `off`?

**Comment by Krystifer** [comment]
Yes, I had that setting set to `of`, setting it to `auto` solves the issue. Thanks.

**Comment by joshspicer** [comment]
If helpful, i've also pushed a new pre-release build `v0.115.2024090522 (pre-release)` that fixes the bug in the extension.

**Comment by ryanmoon** [comment]
Can confirm that setting `remote.SSH.localServerDownload` to `auto` and using the pre-release has things working. Thanks for being so quick on this!

**Comment by joshspicer** [comment]
Release patch version `v0.114.1` fixes this issue.  Please do comment if the issues continues to persist after upgrading

**Comment by samueldyoung29ctr** [comment]
I'm still having Remote SSH sessions through a PuTTY wrapper script on Windows 10 fail both on 0.114.1 and 0.115.2024090522. For each version, it fails regardless of whether `remote.SSH.localServerDownload` is `auto` or `off`. The install script appears to fail inside `do_install`, where the `code` executable is renamed to a hashed name in my remote .vscode-server folder:

```
[09:29:35.423] > Installing to '/scratch/samueldy'/.vscode-server...
> 2fd81c8ded26%%1%%
> Downloading with wget
> wget is from busybox: no
[09:29:35.532] > P
[09:29:35.564] > rogram 'wget' appears to support flag '--no-config'
[09:29:36.713] > D
[09:29:36.747] > ownload complete
> 2fd81c8ded26%%2%%
> tar --version: tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[09:29:36.909] > m
[09:29:36.925] > mv: cannot move 'code' to "'/scratch/samueldy'/.vscode-server/code-4849ca9bdf966
> 6755eb463db297b69e5385090e3": No such file or directory
```

I cannot use `remote.SSH.localServerDownload: always` due to org policies that prevent using OpenSSH SCP with this server. Right now the only Remote SSH release working for me is 0.113.1.

**Comment by joshspicer** [comment]
Hey there @samueldyoung29ctr - thanks for sharing those logs.  Please see https://github.com/microsoft/vscode-remote-release/issues/10230 for more info and possible workarounds

**Comment by TylerLeonhardt** [comment]
Marking as verified due to author verification
