### ISSUE TITLE
Unable to install VSIX on remote through SSH

### ISSUE THREAD

**Issue by Raamakrishnan** [microsoft/vscode-remote-release#1027]
Version: 1.37.0-insider (user setup)
Commit: 36e08fed41272d1ff0d73d9b3a540b0a052ecef4
Date: 2019-07-24T19:58:47.132Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Remote - SSH Version: 0.44.2
Remote Machine - CentOS 7

When trying to install an extension on remote through VSIX that is available in remote, I get this error notification:
`ENOENT: no such file or directory, open 'C:\home\users\<username>\veriloghdl-1.0.3-f5a19.vsix'`

My actual location of VSIX on the remote is `/home/users/<username>/veriloghdl-1.0.3-f5a19.vsix`
Looks like the path is being recognized as my local machine path.

**Comment by roblourens** [comment]
How are you trying to install it?

**Comment by Raamakrishnan** [comment]
1. I uploaded the VSIX to remote
2. Connect Remote-SSH to remote
3. Open Extensions panel > Install from VSIX...
4. The new remote file picker flyout opens. Select the VSIX.
5. This error notification shows up.

**Comment by egamma** [comment]
@Raamakrishnan it would be helpful when you tried to reproduce the same scenario when using VS Code Remote Containers.

**Comment by sandy081** [comment]
This should be fixed in this milestone.

**Comment by Tyriar** [comment]
Not fixed for me.

![image](https://user-images.githubusercontent.com/2193314/62332679-6595cc00-b475-11e9-8935-7cecfcd63f8f.png)

It seems like the problem is it's using the remote file picker by default, and then using the local resulting path. cc @alexr00 

---

VS Code version: Code - Insiders 1.37.0-insider (92da68a71cfb60bd3b9b0d7fbfb2a7e1fff9dbaf, 2019-08-01T05:37:54.848Z)
OS version: Windows_NT x64 10.0.18945
Remote OS version: Linux x64 4.15.0-51-generic
Remote OS version: Linux x64 4.15.0-51-generic
Remote OS version: Linux x64 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (36.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.15.0-51-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (4 x 3491)|
|Memory (System)|17.57GB (2.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.15.0-51-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (4 x 3491)|
|Memory (System)|17.57GB (2.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.15.0-51-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (4 x 3491)|
|Memory (System)|17.57GB (2.35GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

**Comment by sandy081** [comment]
My bad, this is not yet supported in remote.

**Comment by sandy081** [comment]
Verify that, installing a VSIX that is located in remote machine is installed correctly.
