### ISSUE TITLE
devcontainer cli failed after upgrade vscode

### ISSUE THREAD

**Issue by JanosToth1989** [microsoft/vscode-remote-release#10436]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Update the vscode from snap
2. From terminal I got this error:
humdalab@HUMDALAB-01W:~devcontainer 
/home/humdalab/.local/bin/devcontainer: 52: /snap/code/170/usr/share/code/code: not found

How can I update the path? With the suggested method "You can quickly try out the CLI through the Dev Containers extension. Select the Dev Containers: Install devcontainer CLI command from the Command Palette (F1)." it is not working.

**Comment by tipy01** [comment]
```bash
$: readlink `which devcontainer-insiders`
readlink: missing operand
$: readlink `which devcontainer`
$: which devcontainer-insiders
$: which devcontainer
/home/tipy01/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin/devcontainer
```

I guess I am not using insiders version and my "bin" folder is different than the one of @JanosToth1989

**Comment by chrmarti** [comment]
@tipy01 Thanks, what is in the `remote-containers-path` file?

**Comment by tipy01** [comment]
In `remote-containers-path`:
/home/tipy01/.vscode/extensions/ms-vscode-remote.remote-containers-0.389.0

**Comment by chrmarti** [comment]
Got it, we only update `vscode-path` when the extension updates. I can check for `vscode-path` requiring an update separately.

Alternatively we could try to handle snaps special (or find a way to preserve `current` as the path segment from the beginning), but checking for the path requiring an update is simpler and maybe more robust and would also cover the user moving the VS Code installation around.

**Comment by chrmarti** [comment]
This fix is available in Dev Containers 0.391.0-pre-release. Please give it a try and let us know if it fixes this issue for you.

**Comment by rzhao271** [comment]
Dev Containers still doesn't seem to work on my Windows machine. Letting someone else verify this issue.
![Downloading VS Code Server fails](https://github.com/user-attachments/assets/627206fe-a880-4967-98c6-d371414305e4)

**Comment by joshspicer** [comment]
@JanosToth1989 @tipy01 - could either of you confirm or deny this has been fixed for you?

**Comment by rzhao271** [comment]
On Ubuntu 22.04 WSL, after installing the CLI,
```bash
ls "/home/rzhao271/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin"
```
yields
```bash
devcontainer-insiders*  devcontainer-insiders.cmd  remote-containers-path
```
but running the CLI doesn't work because it tries to output a non-existent path
```bash
devcontainer-insiders --help
cat: '/home/rzhao271/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin/vscode-path': No such file or directory
wslpath: /home/rzhao271/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.392.0
Failed to determine Dev Containers path
```

**Comment by chrmarti** [comment]
@rzhao271 Good catch! I broke the initial run. 🤦

**Comment by chrmarti** [comment]
Fixed in 0.393.0-pre-release. @rzhao271 Could you give that another try? Thanks!
