### ISSUE TITLE
Migrate off Terminal.onDidWriteData API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-remote-release#1112]
It's being removed in September, see https://github.com/microsoft/vscode/issues/78574

**Comment by rommni** [comment]
Hi, the Terminal.onDidWriteData API has now been removed, we now can't use remote-ssh extension with insiders version, will there be a fix soon? I need it to run ssh on arm64 architecture which is only supported in insiders version.

**Comment by anatolyburakov** [comment]
Can reproduce this on latest insiders build. Is there an easy way to downgrade insiders build to a previous version?

**Comment by LukaHorvat** [comment]
This worked for me: https://github.com/microsoft/vscode/issues/46089
I downgraded to 1.38 and it seems to work.

Make sure to set updates to manual.

**Comment by anatolyburakov** [comment]
@LukaHorvat thanks, that worked like a charm!

**Comment by Dayjo** [comment]
This is an issue for me, just randomly stopped working today! Can no longer access remote ssh projects :(

**Comment by Tyriar** [comment]
This should get fixed today, sorry about the hassle.

**Comment by roblourens** [comment]
Sorry, this is fixed now.

**Comment by sanket-bhalerao** [comment]
@roblourens when can we expect a release for this?

**Comment by tiptronic85** [comment]
With this configuration i still have the problem:

Versione: 1.39.0-insider (user setup)
Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66
Data: 2019-09-17T06:02:08.670Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by snowzach** [comment]
You need to update the remote plugin. I had to download and install it manually.

**Comment by laskoviymishka** [comment]
How can i update remote plugin manually?

**Comment by roblourens** [comment]
It should autoupdate. If not you can run "Check for Extension Updates"
