### ISSUE TITLE
VSCode+Remote+WSL2 may fail with cannot reconnect. Pleaser reload the window error

### ISSUE THREAD

**Issue by pasoni** [microsoft/vscode-remote-release#1616]
- VSCode Version:
    Version: 1.38.1 (user setup)
    Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
    Date: 2019-09-11T13:35:15.005Z
    Electron: 4.2.10
    Chrome: 69.0.3497.128
    Node.js: 10.11.0
    V8: 6.9.427.31-electron.0
    OS: Windows_NT x64 10.0.18995

- Local OS Version: 
   18995.1001.amd64fre.vb_release_base.190927-1603
- Remote OS Version:
  Ubuntu 18.04 (WSL2)
<img width="233" alt="VSCode-Cannot-reconnect" src="https://user-images.githubusercontent.com/45770325/66230412-fa48c000-e698-11e9-871b-aff7f5c9f433.png">

- Remote Extension/Connection Type: SSH/Docker/WSL
  WSL
Steps to Reproduce:

1. connect to WSL2 via VSCode remote
2. launch WSL2 terminal set some environment variables.
3. Leave session open  and let machine hibernate ( on laptop close lid and leave it in that state for ~10 minutes)
4. log on to machine
5. look at VSCode , you should be connected to WSL2 remote

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by ahernandez-allegion** [comment]
This is the same issue reported here:

https://github.com/microsoft/vscode-remote-release/issues/1637
https://github.com/microsoft/vscode-remote-release/issues/1646

**Comment by mrawdon** [comment]
Is there any progress on this issue?  I am seeing this issue every day.

**Comment by vladimirschneider** [comment]
I have this issue ~ every houre or more often

**Comment by mrawdon** [comment]
I saw it again today when my machine returned from hibernate, I think this is the third time I've seen it since I posted. 
![image](https://user-images.githubusercontent.com/1678756/85400281-2c9b9580-b526-11ea-9d1a-cfd1d9aa0cec.png)

I attached my console log here, I don't know if there is anything else that would be useful.
[-1592913275950.log](https://github.com/microsoft/vscode-remote-release/files/4819129/-1592913275950.log)

**Comment by aeschli** [comment]
Thanks @mrawdon , that's good input.
@alexdima Can you have a look at at the [log](https://github.com/microsoft/vscode-remote-release/files/4819129/-1592913275950.log) ?

**Comment by badstreff** [comment]
running into this daily :(

**Comment by vladimirschneider** [comment]
Hey! It's work great in vscode insider preview, it is solved a trouble of a dialog  of reload windows. I hope this help you.

**Comment by ShengdingHu** [comment]
I fixed this issue by disabling "python for vscode" extension surprisingly.

**Comment by alexdima** [comment]
I looked at the log, and it shows a story of two connections, `ea1f0…` and `58317…`.

It is hard to say how long this took, because timestamps are not in the log, but `ea1f0` was an extension host connection and it got disconnected 7 times and was able to reconnect 7 times. `58317` was a management connection and it got disconnected 5 times and was able to reconnect only 4 times.

In the end it looks to me that the server did not wait for the client to reconnect, so that's why `58317` finally failed with `Unknown reconnection token`. It would be interesting to learn what the server saw on its side.

@aeschli Is it possible to extract somehow the server logs?

**Comment by lanthaler** [comment]
This is still happening to me every single time I hibernate my machine. Let me know if I can provide some logs as I can reliable reproduce it.

**Comment by paulalex** [comment]
> This is still happening to me every single time I hibernate my machine. Let me know if I can provide some logs as I can reliable reproduce it.

This seems to be intermittent for me, so was working fine earlier and then I started vs code for a different repo and I am now unable to work, have not hibernated or even locked my machine this morning. Seems to just start happening.

**Comment by aivanov-noveo** [comment]
The same issue. The workaround is `wsl --shutdown` :-(
