### ISSUE TITLE
Pannel “check remote” keep pop out and catch the cursor and interrupt my work.

### ISSUE THREAD

**Issue by Hypnoes** [microsoft/vscode-remote-release#1760]
- VSCode Version: 1.39.2 (system setup)
- Local OS Version: Windows_NT x64 6.1.7601
- Remote OS Version: Ubuntu 18.04 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect a remote host using unstable network like LTE
2. Pannel "Check remote" constantly pop up, and get focus.
3. THAT! IS! ANNOYED! I have to move my mouse and let my hands leave the keyboard.
4. Some one please tell me how to fix....

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Not sure exactly what you're referring to. I assume you are seeing the "Reconnecting" dialog. Since your connection is unstable, we might lose the connection and have to set it up again.

**Comment by RobertBlackhart** [comment]
This is what the symptoms look like:
![image](https://user-images.githubusercontent.com/5414318/68705976-06a81e80-055d-11ea-8867-aea3a7913bf4.png)

I've not figured out what the rhyme or reason this pops up is. No text ever appears in the terminal window.

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH extension when this happens?

**Comment by RobertBlackhart** [comment]
I just had it happen this morning, almost right away after I reloaded the window after reconnecting to the network, then again just as I was trying to gather your log.

This is the text from the output window titled "Remote - SSH":

```
[05:51:08.152] remote-ssh-nightly@2019.10.42662
[05:51:08.152] win32 x64
[05:51:08.157] SSH Resolver called for "ssh-remote+vscode_remote", attempt 1
[05:51:08.158] SSH Resolver called for host: vscode_remote
[05:51:08.158] Setting up SSH remote "vscode_remote"
[05:51:08.266] Using commit id "213bdddb72ff7a6c8eed071420de8ddac4293cb1" and quality "insider" for server
[05:51:08.269] Testing ssh with ssh -V
[05:51:08.738] ssh exited with code: 0
[05:51:08.738] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[05:51:08.753] Running script with connection command: ssh -T -D 60812 vscode_remote bash
[05:51:08.764] Install and start server if needed
[05:51:08.770] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[05:51:09.332] > 
[05:51:09.333] Got some output, clearing connection timeout
[05:51:10.611] > stty: standard input: Inappropriate ioctl for device
> 0660133aa2c7: running
> Acquiring lock on /u/mcdermor/.vscode-server-insiders/bin/213bdddb72ff7a6c8eed07
> 1420de8ddac4293cb1/vscode-remote-lock.213bdddb72ff7a6c8eed071420de8ddac4293cb1
> Found old VS Code install 31f577ec88dc96ad2028699fb597b19022224b46, attempting t
> o clean up
> Install still has running processes, not deleting: 31f577ec88dc96ad2028699fb597b
> 19022224b46
> Found old VS Code install b53811e67e65c6a564a80e1c412ca2b13de02907, attempting t
> o clean up
> Failed to acquire lock for install, not deleting: b53811e67e65c6a564a80e1c412ca2
> b13de02907
> Found existing installation at /u/mcdermor/.vscode-server-insiders/bin/213bdddb7
> 2ff7a6c8eed071420de8ddac4293cb1...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[05:51:10.638] > Checking server status on port 39710 with wget
> 0660133aa2c7: start
> sshAuthSock====
> agentPort==39710==
> webViewServerPort====
> osReleaseId==rhel==
> arch==x86_64==
> webUiAccessToken====
> 0660133aa2c7: end
> 
[05:51:10.639] Received install output: 
sshAuthSock====
agentPort==39710==
webViewServerPort====
osReleaseId==rhel==
arch==x86_64==
webUiAccessToken====

[05:51:10.640] Remote server is listening on port 39710
[05:51:10.640] Parsed server configuration: {"agentPort":39710,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":""}
[05:51:10.653] Starting forwarding server. localPort 60818 -> socksPort 60812 -> remotePort 39710
[05:51:10.655] Forwarding server listening on 60818
[05:51:10.656] Waiting for ssh tunnel to be ready
[05:51:10.663] Tunneled remote port 39710 to local port 60818
[05:51:10.663] Resolved "ssh-remote+vscode_remote" to "127.0.0.1:60818"
[05:51:10.668] ------




[05:51:10.669] [Forwarding server 60818] Got connection 0
[05:51:10.735] [Forwarding server 60818] Got connection 1
[05:51:10.737] [Forwarding server 60818] Got connection 2
[05:51:11.680] [Forwarding server 60818] Got connection 3
[05:54:10.658] > 
[05:57:10.665] > 
```

That was the output right after I saw the window appear the first time. As I was writing this, like I mentioned above, it appeared again. When I checked the Remote - SSH output after that, this was the only additional line:

```
[06:00:10.658] >
```

Again, while writing this, it happened two more times and again all I see are blank lines added:

```
[06:03:10.668] > 
[06:06:10.667] >
```

None of the other logs are getting updated (by looking at their timestamps), but if any of the others would be useful, let me know.

**Comment by roblourens** [comment]
@Tyriar any idea why this would happen when I set `hideFromUser` on this terminal?

**Comment by Tyriar** [comment]
They're on Windows 7 so my guess is it's this problem https://github.com/microsoft/vscode/issues/43169

**Comment by RobertBlackhart** [comment]
I'm using Windows 10 1809 (OS Build 17763.805) currently, not 7.

**Comment by Tyriar** [comment]
Oh OK, I saw this and assumed it was talking about Windows 7:

> [05:51:08.738] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

So it works on the initial connection and all reconnects from the same window fail? Or just some?

**Comment by RobertBlackhart** [comment]
I'm not sure what you mean by "all reconnects from the same window fail". I haven't experienced a lot of reconnect failures that I would currently pin on VSCode. This symptoms of this bug don't seem to be related to reconnects. It seems to happen even without them.

I just updated to 1.41.0 today so I will have to let you know how it goes.

**Comment by roblourens** [comment]
@Tyriar I mean the problem is, the terminal is never supposed to be shown to the user at all because I set that flag and never try to reveal it.

**Comment by RobertBlackhart** [comment]
As of version 1.41.0, this is still occurring for me.

**Comment by RobertBlackhart** [comment]
I don't have any good way to measure this, but I do feel like it hasn't been happening nearly as often as it was when I first started watching this thread.

**Comment by Hypnoes** [comment]
> I don't have any good way to measure this, but I do feel like it hasn't been happening nearly as often as it was when I first started watching this thread.

Yes, same as I met.

**Comment by RobertBlackhart** [comment]
I haven't seen this error in any recent times. Some update must have fixed it at or around 1.41.0. This issue can be closed.

**Comment by roblourens** [comment]
Thanks for following up!

**Comment by RobertBlackhart** [comment]
Hmm, bad news. I just saw this pop up again. I'm currently running this version:

```
Version: 1.41.0-insider (user setup)
Commit: 87c2e0be5d7359ce110c4c9ec9f6df71be996f8a
Date: 2019-12-06T21:36:11.793Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by RobertBlackhart** [comment]
Something new I've noticed. It used to be that the "Check Remote" window was blank. Now when it appears, it has the text "source <path_to_my_pyenv>" in it. Could this window be related to something in the Python extension?

**Comment by Hypnoes** [comment]
> Something new I've noticed. It used to be that the "Check Remote" window was blank. Now when it appears, it has the text "source <path_to_my_pyenv>" in it. Could this window be related to something in the Python extension?
> 
> This text is not always present. Sometimes when the window appears it's still blank, but I've seen it more than once.

Same

**Comment by roblourens** [comment]
Are you sure it's the terminal that says "check remote" and not a terminal related to the python extension?

**Comment by Hypnoes** [comment]
![test](https://user-images.githubusercontent.com/13956546/70686124-442bd300-1ce6-11ea-9709-fed0d39eb28b.PNG)
I'm writing a scala project and i got this problem too.

**Comment by roblourens** [comment]
Can you share your settings?

**Comment by Hypnoes** [comment]
settings.json
```json
{
    "git.enableSmartCommit": true,
    "editor.cursorBlinking": "phase",
    "editor.fontFamily": "'Cascadia Code', 'PingFang SC Regular'",
    "editor.fontLigatures": true,
    "editor.minimap.enabled": false,
    "editor.mouseWheelZoom": true,
    "editor.rulers": [
        80,
        100,
        120
    ],
    "zenMode.centerLayout": false,
    "zenMode.hideTabs": false,
    "explorer.confirmDelete": false,
    "git.confirmSync": false,
    "git.autofetch": true,
    "workbench.iconTheme": "vscode-icons",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.enableBell": true,
    "remote.SSH.showLoginTerminal": true,
    "remote.SSH.enableDynamicForwarding": true,
    "remote.SSH.allowLocalServerDownload": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "files.autoGuessEncoding": false
}
```

**Comment by roblourens** [comment]
Does it still happen if you disable `remote.SSH.showLoginTerminal`?

**Comment by RobertBlackhart** [comment]
Here is my settings.json. I don't have the remote.SSH.showLoginTerminal set. I think the default is  false though (because that's what the editor fills in for me when I put that key name in). I will set it to false explicitly and see what happens.

```
{
    "editor.rulers": [80],
    "editor.multiCursorModifier": "ctrlCmd",
    "files.eol": "\n",
    "window.zoomLevel": 0,
    "editor.renderWhitespace": "none",
    "workbench.colorCustomizations": {
        "statusBar.background": "#666666"
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/bedrock": true
    },
    "workbench.iconTheme": "vscode-icons",
    "vsicons.projectDetection.disableDetect": true,
    "editor.suggestSelection": "first",
    "files.watcherExclude": {
        "**/bedrock/**": true
    },
    "files.associations": {
        "*.thpl": "perl",
        "*.ut": "cpp"
    },
    "python.insidersChannel": "off",
    "trailing-spaces.trimOnSave": true,
    "vsicons.dontShowNewVersionMessage": true,
    "extensions.ignoreRecommendations": false,
    "remote.SSH.allowLocalServerDownload": true,
    "python.testing.pytestEnabled": true,
    "python.analysis.memory.keepLibraryAst": true,
    "python.analysis.memory.keepLibraryLocalVariables": true,
    "python.linting.pylintUseMinimalCheckers": false,
    "python.analysis.openFilesOnly": false,
    "python.dataScience.sendSelectionToInteractiveWindow": false,
    "trailing-spaces.deleteModifiedLinesOnly": true,
    "git.autofetch": true
}
```

**Comment by RobertBlackhart** [comment]
Just an update that even after setting remote.SSH.showLoginTerminal to false, I still see this window pop up sometimes. Today, it was right after I reconnected to the network and did a reload of the window so that VSCode would reconnect.

**Comment by adawalli** [comment]
I also see this random switch to the "Check remote" tab. Some days I don't see it at all, sometimes I can barely keep it suppressed. I am on OSx (Mojave), but I am also primarily doing python development when I see the issue. I often get the single line "source /../bin/activate" printed out as well.

**Comment by ychechik** [comment]
> I also see this random switch to the "Check remote" tab. Some days I don't see it at all, sometimes I can barely keep it suppressed. I am on OSx (Mojave), but I am also primarily doing python development when I see the issue. I often get the single line "source /../bin/activate" printed out as well.
> 
> My **settings.json**
> 
> ```json
> {
>     "editor.fontFamily": "'Hack Nerd Font Mono',Menlo, Monaco, 'Courier New', monospace",
>     "editor.fontSize": 14,
>     "terminal.integrated.fontSize": 13,
>     "terminal.integrated.fontWeightBold": "normal",
>     "remote.SSH.lockfilesInTmp": true,
>     "workbench.startupEditor": "newUntitledFile",
>     "editor.fontLigatures": true,
>     "terminal.external.osxExec": "iTerm.app",
>     "workbench.colorCustomizations":{
>         "terminal.ansiBlue": "#ADADAD",
>         "terminal.ansiBlack": "#000000",
>         "terminal.background": "#121212",
>         "terminal.foreground": "#DEDEDE"
>     },
>     "python.formatting.provider": "yapf",
>     "git.autofetch": true,
>     "workbench.colorTheme": "An Old Hope",
>     "workbench.iconTheme": "material-icon-theme",
>     "window.zoomLevel": 0,
>     "remote.SSH.useLocalServer": true,
>     "terminal.integrated.fontFamily": "'FuraCode Nerd Font'",
>     "terminal.integrated.scrollback": 10000,
>     "workbench.panel.defaultLocation": "right",
>     "workbench.fontAliasing": "auto",
>     "python.linting.mypyEnabled": true,
>     "terminal.integrated.macOptionClickForcesSelection": true,
>     "autoDocstring.docstringFormat": "google",
>     "files.trimTrailingWhitespace": true,
>     "python.venvPath": "/Users/awallis/Library/Caches/pypoetry/virtualenvs/",
>     "python.linting.mypyPath": "~/bin/mypy",
>     "python.linting.flake8Path": "~/bin/flake8",
>     "python.linting.pylintEnabled": false,
>     "latex-workshop.view.pdf.viewer": "tab",
>     "terminal.integrated.shell.linux": "/usr/bin/byobu",
>     "terminal.integrated.macOptionIsMeta": true
> }
> ```
> 
> One thing of note, although I am using **byobu** as my login shell at the moment, the same thing happened when used **zsh** directly as well


same for me in windows10, ssh, vscode 1.41.1

**Comment by roblourens** [comment]
Does changing any of the settings work, like `remote.SSH.useLocalServer`?

**Comment by ZachNew** [comment]
Hi all, I am also experiencing this issue. Windows 10, ssh, vscode 1.41.1.

More detail: 

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by hoshinomahiro** [comment]
I'am also annoyed by this problem. It always pops out a "Check remote" panel and interrupt my work.

Environment:
Version: 1.41.1 (system setup)
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
I pushed a fix to prevent the showLoginTerminal setting from affecting this terminal. I know that's not the case for all of you but lets see if it helps. Will be in the next nightly build tomorrow.

**Comment by adawalli** [comment]
> Does changing any of the settings work, like `remote.SSH.useLocalServer`?

I tried setting to `false` - I then restarted VSCode, but I unfortunately, still get the same behavior.

**Comment by bhughes339** [comment]
I'm having the same issue, and it seems to only happen when I'm using a Python Virtual Environment, as the "Check remote" shell always shows the activate code:

`source /var/www/flask_server/venv/bin/activate`

It only started happening recently, probably within the last two VSCode versions or so. If i set my Python version to a non-venv version, the issue seems to stop. I have not been able to identify a pattern as to when the shell appears, it seems to be random.

- VSCode Version: 1.41.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Debian 10 (buster)
- Remote Extension/Connection Type: SSH

**Comment by roblourens** [comment]
I see 2 other people in this thread using Python/virtualenv, that's interesting. Also that `source` command is not part of the terminal that I spawn. @Tyriar is it possible that the Python extension is creating these terminals but they are getting the wrong title, from my terminals?

**Comment by Pakbon** [comment]
I can confirm it's happening with me too. And yes, also Python in a virtual environment

**Comment by adawalli** [comment]
@roblourens - I can't remember where I picked up this trick, but I have had the following in my `~/.zshev` for quite a long time

```
if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
```

This worked fine in VSCode (+python) for quite a long time. I will comment it out for now to make sure it's merely a symptom and not the culprit.

**Comment by adawalli** [comment]
> @roblourens - I can't remember where I picked up this trick, but I have had the following in my `~/.zshenv` for quite a long time
> 
> ```
> if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
>   source "${VIRTUAL_ENV}/bin/activate"
> fi
> ```
> 
> This worked fine in VSCode (+python) for quite a long time. I will comment it out for now to make sure it's merely a symptom and not the culprit.

Sorry for updating so close to my original post, but I have already had a popup since I removed that from my environment file. I think that the `source` command is coming from VSCode initializing the virtual environment.

**Comment by quartox** [comment]
Python extension user here with conda virtual environments. Tried insider version from today and still seeing the issue.

I have a few behaviors to note. Primarily the same new terminal `Check remote` which intermittently runs the activate command for python. The python environment activate command is visible when a python file is open and missing when I am editing a different file type. This is the same behavior as manually opening a new terminal, so I suspect that it is not triggered by the python extension but uses the python extension logic for a new terminal.

I have also seen a terminal named `Install` that is often followed by another new terminal named `Check remote`. The `Install` terminal always has a lot of logic listed but I don't have an example ready to share (will edit if this happens again). Sometimes dozens of `Install` terminals are created back-to-back.

In both cases it looks like this new terminal does not have an active prompt. I can give it input from the keyboard but nothing happens.

* VSCode Version: 1.42.0-insider (also appears on older versions)
* Local OS Version: MacOS Catalina 10.15.2 (19C57)
* Remote OS Version: Ubuntu 16.04.5 LTS (Xenial Xerus)
* Remote Extension/Connection Type: SSH

**Comment by Tyriar** [comment]
> @Tyriar is it possible that the Python extension is creating these terminals but they are getting the wrong title, from my terminals?

> but I am also primarily doing python development when I see the issue. I often get the single line "source /../bin/activate" printed out as well.

I think the Python extension tries to activate the venv regardless of the type of terminal which should certainly not be happening with the SSH connection ones. https://github.com/microsoft/vscode/issues/63052 was done to help the Python extension know when it should and shouldn't be activating the env. @DonJayamanne

**Comment by adawalli** [comment]
While this is not a solution, it might help you alleviate the symptom of this a bit

If you update your keybinding for `workbench.action.terminal.focusAtIndex1` to a keyboard shortcut, you can at least toggle back to your working terminally very quickly when this issue crops up. For me, this is a huge improvement, since grabbing the mouse and having to click through really disrupts my workflow

**Comment by adawalli** [comment]
The issue also goes away for me I when set
```json
"python.terminal.activateEnvironment": false
```

This makes sense as I was constantly seeing that `source <venv>/bin/activate` output message.   This is also confirmed by t[he documentation](https://code.visualstudio.com/docs/python/settings-reference) 

>Indicates whether to automatically activate the environment you select using the Python: Select Interpreter command. For example, when this setting is true and you select a virtual environment, the extension automatically runs the environment's activate command (source env/bin/activate on macOS/Linux; env\scripts\activate on Windows).

I don't know why the remote plugin is so actively trying to re-run this source command or why it started up recently. 

If you really need to be in that virtual environment, it's just as easy as manually sourcing that `activate` script in your env. or run `pipenv shell` or `poetry shell` or however your workflow allows

**Comment by terminalh2t3** [comment]
@adawalli Your solution really did the trick. I would rather manually activate conda environment than let that panel keep annoying. Thank you.

**Comment by roblourens** [comment]
Filed upstream: https://github.com/microsoft/vscode-python/issues/9503

**Comment by jessicaplant** [comment]
I'm a PHP dev working on Laravel apps and it's constantly popping up and distracting me - I'd switch to another IDE but we rely on Remote SSH because of our ISO standpoint. I don't have anything unusual in `.zshrc` except a ton of exports and the NVM initialisation code. Any ideas? 

It's relentless 😢 like multiple times an hour over multiple windows.

**Comment by adawalli** [comment]
@jessicaplant - did you try the suggestion by @ngolin ? This is the first I have heard of this happening outside of python dev

**Comment by negorath** [comment]
I was having the same problem, and @ngolin's suggestion fixed it for me, but that means I now have to retype my password constantly.

My dev environment consists of Javascript and Go, so I think the problem is unrelated to Python.

**Comment by errietta** [comment]
I have this issue too, it doesn't seem related to the language although I do use python

**Comment by jhliu17** [comment]
I meet the same issue too, and I try to terminate it but I failed.

**Comment by julien-c** [comment]
Also affected by this.

**Comment by aaronyun** [comment]
Here is the same problem, but the ouput in Check Remote is different:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=GB2312" />
    <title></title>
</head>

<body>
    
    <script type="text/javascript">
        carrier = '';
        sv = 0; sv1 = 0; v6 = 'http://ip6.dr.com:9002/v6                               '; myv6ip = '                                       '; v4serip = '10.254.7.4'; m46 = 0; v46ip = '10.236.11.10';
        vid = 0; mip = 010236011010; Gno = 0000; vlanid = "0"; AC = ""; ipm = "0afe0704"; ss1 = "000d4808642f"; ss2 = "0000"; ss3 = "0aec0b0a"; ss4 = "000000000000"; ss5 = "10.236.11.10"; ss6 = "10.254.7.4"; timet = 1584168703;

        authexenable = 0;
        authtype = 1;
        authloginport = 80;
        authloginpath = '';
        authloginparam = '';
        authlogoutpath = '';
        authlogoutport = 80;
        queryport = 80;
        isquery = 0;
        querypath = '';
        queryparam = '';
        authhost = '';
        authoffpost = '';
        authsuccess = 'Dr.COMWebLoginID_3.htm';
        authuserfield = 'DDDDD';
        authpassfield = 'upass';

        portalid = 'CQ0301403_000';
        serialno = '';
        portalname = '锟斤拷锟斤拷锟窖э拷锟较�校锟斤拷';
        logourl = '';
        bannerurl = 'a59.png';
        welcome = '';
        businessurl = '';
        portalver = '0010300000';

        var reg = new RegExp("(^|&)drcomver([^&]*)(&|$)", "i");
        var r = window.location.search.substr(1).match(reg);
        if (r != null) {
            document.write("portalname=" + portalname + "<br>");
            document.write("portalide=" + portalid + "<br>");
            document.write("portalver=" + portalver + "<br>");
        } else

            if ((navigator.userAgent.indexOf('iPad') > 0) || (navigator.userAgent.indexOf('Windows NT') > 0))
                location.href = "0.htm"
            else if ((navigator.userAgent.indexOf('Mobile') > 0))
                location.href = "a30.htm"
            else
                location.href = "0.htm"

    </script>
    <div>锟斤拷锟斤拷锟借备锟窖撅拷锟斤拷止JAVASCRIPT<br>
        PC锟斤拷锟斤拷<a href="0.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br>
        锟狡讹拷锟秸讹拷锟斤拷锟斤拷<a href="a30.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br></div>
</body>

</html>`

I found that this output will appear every time i tried to reconnect to remote machine. Also, i use conda on that remote machine.

**Comment by aaronyun** [comment]
Here is the same problem, but the ouput in Check Remote is different:
`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=GB2312" />
    <title></title>
</head>

<body>
    
    <script type="text/javascript">
        carrier = '';
        sv = 0; sv1 = 0; v6 = 'http://ip6.dr.com:9002/v6                               '; myv6ip = '                                       '; v4serip = '10.254.7.4'; m46 = 0; v46ip = '10.236.11.10';
        vid = 0; mip = 010236011010; Gno = 0000; vlanid = "0"; AC = ""; ipm = "0afe0704"; ss1 = "000d4808642f"; ss2 = "0000"; ss3 = "0aec0b0a"; ss4 = "000000000000"; ss5 = "10.236.11.10"; ss6 = "10.254.7.4"; timet = 1584168703;

        authexenable = 0;
        authtype = 1;
        authloginport = 80;
        authloginpath = '';
        authloginparam = '';
        authlogoutpath = '';
        authlogoutport = 80;
        queryport = 80;
        isquery = 0;
        querypath = '';
        queryparam = '';
        authhost = '';
        authoffpost = '';
        authsuccess = 'Dr.COMWebLoginID_3.htm';
        authuserfield = 'DDDDD';
        authpassfield = 'upass';

        portalid = 'CQ0301403_000';
        serialno = '';
        portalname = '锟斤拷锟斤拷锟窖э拷锟较�校锟斤拷';
        logourl = '';
        bannerurl = 'a59.png';
        welcome = '';
        businessurl = '';
        portalver = '0010300000';

        var reg = new RegExp("(^|&)drcomver([^&]*)(&|$)", "i");
        var r = window.location.search.substr(1).match(reg);
        if (r != null) {
            document.write("portalname=" + portalname + "<br>");
            document.write("portalide=" + portalid + "<br>");
            document.write("portalver=" + portalver + "<br>");
        } else

            if ((navigator.userAgent.indexOf('iPad') > 0) || (navigator.userAgent.indexOf('Windows NT') > 0))
                location.href = "0.htm"
            else if ((navigator.userAgent.indexOf('Mobile') > 0))
                location.href = "a30.htm"
            else
                location.href = "0.htm"

    </script>
    <div>锟斤拷锟斤拷锟借备锟窖撅拷锟斤拷止JAVASCRIPT<br>
        PC锟斤拷锟斤拷<a href="0.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br>
        锟狡讹拷锟秸讹拷锟斤拷锟斤拷<a href="a30.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br></div>
</body>

</html>
`
I found that this output will appear every time i tried to reconnect to remote machine. Also, i use conda on that remote machine.

**Comment by aaronyun** [comment]
Here is the same problem, but the output is html code.
I also use conda on my remote machin.

``<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=GB2312" />
    <title></title>
</head>

<body>
    
    <script type="text/javascript">
        carrier = '';
        sv = 0; sv1 = 0; v6 = 'http://ip6.dr.com:9002/v6                               '; myv6ip = '                                       '; v4serip = '10.254.7.4'; m46 = 0; v46ip = '10.236.11.10';
        vid = 0; mip = 010236011010; Gno = 0000; vlanid = "0"; AC = ""; ipm = "0afe0704"; ss1 = "000d4808642f"; ss2 = "0000"; ss3 = "0aec0b0a"; ss4 = "000000000000"; ss5 = "10.236.11.10"; ss6 = "10.254.7.4"; timet = 1584168703;

        authexenable = 0;
        authtype = 1;
        authloginport = 80;
        authloginpath = '';
        authloginparam = '';
        authlogoutpath = '';
        authlogoutport = 80;
        queryport = 80;
        isquery = 0;
        querypath = '';
        queryparam = '';
        authhost = '';
        authoffpost = '';
        authsuccess = 'Dr.COMWebLoginID_3.htm';
        authuserfield = 'DDDDD';
        authpassfield = 'upass';

        portalid = 'CQ0301403_000';
        serialno = '';
        portalname = '锟斤拷锟斤拷锟窖э拷锟较�校锟斤拷';
        logourl = '';
        bannerurl = 'a59.png';
        welcome = '';
        businessurl = '';
        portalver = '0010300000';

        var reg = new RegExp("(^|&)drcomver([^&]*)(&|$)", "i");
        var r = window.location.search.substr(1).match(reg);
        if (r != null) {
            document.write("portalname=" + portalname + "<br>");
            document.write("portalide=" + portalid + "<br>");
            document.write("portalver=" + portalver + "<br>");
        } else

            if ((navigator.userAgent.indexOf('iPad') > 0) || (navigator.userAgent.indexOf('Windows NT') > 0))
                location.href = "0.htm"
            else if ((navigator.userAgent.indexOf('Mobile') > 0))
                location.href = "a30.htm"
            else
                location.href = "0.htm"

    </script>
    <div>锟斤拷锟斤拷锟借备锟窖撅拷锟斤拷止JAVASCRIPT<br>
        PC锟斤拷锟斤拷<a href="0.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br>
        锟狡讹拷锟秸讹拷锟斤拷锟斤拷<a href="a30.htm">锟斤拷锟斤拷</a>锟斤拷锟斤拷<br></div>
</body>

</html>``

**Comment by HsunGong** [comment]
Same issue. Seems the remote part will establish a new console when reconnecting to the remote `while the remote server still has some progresses for vscode`.

**Comment by zzhou612** [comment]
Same issue. I am using pyenv. Check remote panel just keep popping out. Really annoying.

**Comment by shamoons** [comment]
Using `pipenv`, getting this as well:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/1019677/77254393-1afcd600-6c37-11ea-8ec9-283189971bb9.png">

```

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by telemmaite** [comment]
Same issue here, crazy annoying, also I notice that when using virtualenv there are two tabs.
```
1: bash
2: Check remote
```
On the first one (bash) my virtualenv is **not auto activated** if I open another (3: bash) `New Terminal` it **is auto activated**. It is quicker for me to activate a new one, than to use the default `1:bash`.

**Comment by ceejwalker** [comment]
[Ngolin's fix](https://github.com/microsoft/vscode-remote-release/issues/1760#issuecomment-575424386) worked great for me. Just popped it in settings, closed and reopened VS Code and bash loads correctly with no check remote screen.

**Comment by tomrunia** [comment]
I am also still experiencing this issue. The fix suggested by @ngolin does not solve the problem for me. Sometimes after a while working there are 10+ "check remote" tabs open in the output window in the bottom of the screen. I am running VSCode 1.43.2 on my Mac and connecting to a Linux machine with a virtualenv.

**Comment by roblourens** [comment]
I had expected that this would be fixed upstream by now. Anyone still seeing it, please check that you have the latest version of the Python extension, and if so, could you follow up on the Python extension's repo? https://github.com/microsoft/vscode-python/issues/9503

**Comment by hoechenberger** [comment]
@roblourens 
Experiencing the same issue, still, with latest VS Code and Python extension. Will check out the issue you linked.

**Comment by wangxianrui** [comment]
I also encountered this problem. Has it been solved？

**Comment by liziwl** [comment]
I also have the problem on Windows 10, ver 1.44.0

**Comment by liziwl** [comment]
> This works for me:
> 
> ```
>     "remote.SSH.enableDynamicForwarding": false
> ```

this really work for me

**Comment by roblourens** [comment]
So people are seeing this in `2020.3.71113` or newer?

**Comment by narfanar** [comment]
@roblourens Seeing it still on 2020-04-10

**Comment by roblourens** [comment]
I'm asking about the Python extension version

**Comment by tomrunia** [comment]
> I'm asking about the Python extension version

Yes, problem occurs here with Python extension `2020.3.71659` and VSCode `1.44.0`

**Comment by jkryanchou** [comment]
+1 Same problem with the issuer. Is there any solution or methods to close the check remote tab?

**Comment by catexis** [comment]
```
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Same problem

<details><summary>Screenshot</summary>

[![](https://i.imgur.com/ByhHkjbm.jpg)](https://i.imgur.com/ByhHkjb.png)

</details>

<details><summary>Expand (Remote ssh log)</summary>

```
[09:44:50.964] Log Level: 2
[09:44:50.969] remote-ssh@0.51.0
[09:44:50.969] win32 x64
[09:44:50.971] SSH Resolver called for "ssh-remote+work-ubu", attempt 1
[09:44:50.971] SSH Resolver called for host: work-ubu
[09:44:50.972] Setting up SSH remote "work-ubu"
[09:44:51.028] Using commit id "2aae1f26c72891c399f860409176fe435a154b13" and quality "stable" for server
[09:44:51.031] Install and start server if needed
[09:44:51.038] Checking ssh with "ssh -V"
[09:44:51.098] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:44:51.101] Running script with connection command: ssh -T -o ClearAllForwardings=true work-ubu bash
[09:44:51.108] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:44:51.174] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:44:51.175] Got some output, clearing connection timeout
[09:44:51.181] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:44:56.640] > 862b642af7ac: running
> 
[09:44:56.779] > Acquiring lock on /home/anderson/.vscode-server/bin/2aae1f26c72891c399f860409176
> fe435a154b13/vscode-remote-lock.anderson.2aae1f26c72891c399f860409176fe435a154b1
> 3
> 
[09:44:56.805] > \ln /home/anderson/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/v
> scode-remote-lock.anderson.2aae1f26c72891c399f860409176fe435a154b13.target /home
> /anderson/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/vscode-rem
> ote-lock.anderson.2aae1f26c72891c399f860409176fe435a154b13
> 
[09:44:56.859] > Found existing installation at /home/anderson/.vscode-server/bin/2aae1f26c72891c
> 399f860409176fe435a154b13...
> 
[09:44:56.910] > Found running server...
> 
[09:44:56.922] > 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[09:44:56.970] > Checking server status on port 33315 with wget
> 
[09:44:57.054] > 862b642af7ac: start     
> agentPort==33315==      
> osReleaseId==ubuntu==   
> arch==x86_64==
> webUiAccessToken====    
> tmpDir==/run/user/1000==
> platform==linux==
> 862b642af7ac: end
> 
[09:44:57.055] Received install output:      
agentPort==33315==      
osReleaseId==ubuntu==   
arch==x86_64==
webUiAccessToken====    
tmpDir==/run/user/1000==
platform==linux==

[09:44:57.057] Remote server is listening on port 33315
[09:44:57.057] Parsed server configuration: {"agentPort":33315,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","tmpDir":"/run/user/1000","platform":"linux"}
[09:44:57.070] Running script with connection command: ssh -T -L 127.0.0.1:60942:127.0.0.1:33315 work-ubu bash
[09:44:57.072] Spawning tunnel with: type "C:\Users\ander\AppData\Local\Temp\vscode-linux-multi-line-command-work-ubu-219092226.sh" | ssh -T -L 127.0.0.1:60942:127.0.0.1:33315 work-ubu bash
[09:44:57.073] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:44:57.154] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:44:57.171] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:44:57.425] "install" terminal command done
[09:44:57.426] Install terminal quit with output: 
[09:45:01.930] > SSH_AUTH_SOCK=
> 
[09:45:01.945] > Connected to SSH Host - Please do not close this terminal
> 
[09:45:01.945] Spawned SSH tunnel between local port 60942 and remote port 33315
[09:45:01.945] Waiting for ssh tunnel to be ready
[09:45:01.951] Tunneled remote port 33315 to local port 60942
[09:45:01.954] Resolved "ssh-remote+work-ubu" to "127.0.0.1:60942"
[09:45:01.962] ------

```

</details>

**Comment by ryanfwy** [comment]
This problem will always occur when I choose a python interpreter created by virtual environment, say `conda`, and then close the remote server with a python script active.

Both VSCode version and Python extension version are the latest as mentioned above.

**Comment by binchick-in** [comment]
This is getting out of hand.

This happens on all operating systems I use VSCode on. ChromeOS (deb package install), MacOS, and Windows.

```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.87-07826-g55ab70aff690
```

![Screenshot 2020-04-18 at 11 57 12 AM](https://user-images.githubusercontent.com/5251954/79668775-0d6e3980-816c-11ea-84cf-e1aa074018bd.png)

**Comment by plwalsh** [comment]
I was still seeing this error for several weeks after the fix had been pushed. The other day, my VS Code Insiders was failing to connect to my remote due to an Insiders bug (fixed by [44c51853](https://github.com/microsoft/vscode/commit/44c5185373d5f209cd6c0b5d29a216fb801da34e)). Before realizing it was a bug, I [uninstalled VS Code Server on the remote](https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote) several times while trying to get it to work again. Once the fix was pushed and the new Insiders release was installed on my local machine, my remote connection worked and the "Check remote" issue was finally gone.

_TL;DR_: Try uninstalling VS Code Server on the remote and reconnect to let VS Code reinstall it.

**Comment by ryanfwy** [comment]
> I was still seeing this error for several weeks after the fix had been pushed. The other day, my VS Code Insiders was failing to connect to my remote due to an Insiders bug (fixed by [44c51853](https://github.com/microsoft/vscode/commit/44c5185373d5f209cd6c0b5d29a216fb801da34e)). Before realizing it was a bug, I [uninstalled VS Code Server on the remote](https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote) several times while trying to get it to work again. Once the fix was pushed and the new Insiders release was installed on my local machine, my remote connection worked and the "Check remote" issue was finally gone.
> 
> _TL;DR_: Try uninstalling VS Code Server on the remote and reconnect to let VS Code reinstall it.

I have tried uninstalling and reinstalling it, but nothing changed. Problem still occurs when I close the connection with a python script active in the front and reconnect it.

**Comment by plwalsh** [comment]
Thanks for the feedback, @ryanfwy. Was worth a shot. Not sure what else it could've been then, since all my extensions were already up to date before that happened.

**Comment by pedrodallav** [comment]
Same problem here:
```
VSCode Version: 1.44.2
Local OS Version: macOS Catalina 10.15.4
Remote OS Version: Ubuntu 18.04.3 LTS
Remote Extension/Connection Type: SSH
```

**Comment by belskikh** [comment]
Same here:

```VSCode Version: 1.44.2
Local OS Version: macOS Catalina 10.15.4
Remote OS Version: Ubuntu 18.04.3 LTS
Remote Extension/Connection Type: SSH```

**Comment by tomrunia** [comment]
This is getting out of hand :(

![Screenshot 2020-04-25 at 20 04 59](https://user-images.githubusercontent.com/5536129/80287151-1b095d80-8730-11ea-86f7-0503c8877695.png)

**Comment by tbright17** [comment]
Same here. But looks like if I uninstall the "Python" extension, it will not pop up again.

**Comment by benlindsay** [comment]
[Ngolin's fix](https://github.com/microsoft/vscode-remote-release/issues/1760#issuecomment-575424386) as mentioned [by ceejwalker](https://github.com/microsoft/vscode-remote-release/issues/1760#issuecomment-604539108) worked for me for now too. We'll see if it keeps working and if it has any consequences down the line.

**Comment by tomrunia** [comment]
I see a lot of people having this problem, but is anyone actually working on a solution? Seems a bit quiet on the VSCode remote team side. @roblourens any updates on this?

**Comment by roblourens** [comment]
I filed https://github.com/microsoft/vscode-python/issues/11122 on the python extension. Earlier I was able to reproduce it, now I am not able to. Can someone check whether setting `"python.terminal.activateEnvironment": false` still fixes it?

**Comment by catexis** [comment]
> still fixes it

Nope

**Comment by benlindsay** [comment]
@roblourens I added that setting a few days ago, and I don't think I've run into the problem since, but I'll update you if it happens again. Given the above comment though it seems like that doesn't fix it for everyone

**Comment by mswiatlo** [comment]
I'm running into this, with the latest 1.45.0 version. Happy to provide my configs if helpful.

**Comment by David-Dawei** [comment]
this is still happening after I uninstall all the extensions except the remote-ssh

VSCode Version: 1.45.0
Local OS Version: windows 10
Remote OS Version: Ubuntu 18.04.3 LTS
Remote Extension/Connection Type: SSH

**Comment by David-Dawei** [comment]
> this is still happening after I uninstall all the extensions except the remote-ssh
> @roblourens does anyone working on this ？or do we have any work-around?
> 
> VSCode Version: 1.45.0
> Local OS Version: windows 10
> Remote OS Version: Ubuntu 18.04.3 LTS
> Remote Extension/Connection Type: SSH

finally

> this is still happening after I uninstall all the extensions except the remote-ssh
> @roblourens does anyone working on this ？or do we have any work-around?
> 
> VSCode Version: 1.45.0
> Local OS Version: windows 10
> Remote OS Version: Ubuntu 18.04.3 LTS
> Remote Extension/Connection Type: SSH

disable ipv6 is the reason in my case.
so I enabled IPV6 and then reboot, it get working again.

**Comment by antonwnk** [comment]
I hit a personal record.

![remotedev](https://user-images.githubusercontent.com/23464453/82024767-948dcf00-9690-11ea-980b-4a9592ef6176.png)

**Comment by ikariwing** [comment]
I am encountering the same issue constantly, and I found that adding a shortcut to switch focus of terminals can mitigate this issue a bit.

Create shortcut key to switch between terminals in vs code. · Issue #37937 · microsoft/vscode
https://github.com/microsoft/vscode/issues/37937

**Comment by carlthome** [comment]
I'm (almost) getting used to this:

![image](https://user-images.githubusercontent.com/1595907/83648551-77289280-a5b6-11ea-8950-407fc74e9ac0.png)

**Comment by penguinbing** [comment]
I add below code to settings.json file and it seems working for me, you guys can have a try.
```
{
    "terminal.integrated.inheritEnv": false
}
```

**Comment by hoechenberger** [comment]
> Can someone check whether setting `"python.terminal.activateEnvironment": false` still fixes it?

Yes this does fix it for me.

<img width="520" alt="Screenshot 2020-06-05 at 09 48 12" src="https://user-images.githubusercontent.com/2046265/83851007-fed6e400-a711-11ea-808b-5fe0bebb03d0.png">

I don't have the issue with this setting. Once I set `"python.terminal.activateEnvironment": true`, the issue resurfaces.

**Comment by durandg12** [comment]
The problem appeared to me this morning, whereas I have been working in remote SSH for weeks now (and on the same remote computer). Maybe a new version of the Python extension has made it appear?

Anyway the above fix worked on the remote version of the extension.

My VSCode info : 

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

My local OS is macOS 10.13.6 and my remote OS is Linux x64 4.15.0-1065-aws. I have the Python extension v2020.6.90262 installed on both.

**Comment by jamt9000** [comment]
Also happens on Mac 10.14.1, causes hundreds of open terminals.

```

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.2.0
```

<img width="376" alt="Screenshot 2020-06-30 at 15 57 26" src="https://user-images.githubusercontent.com/1186841/86142306-f6907f80-baea-11ea-8ed6-6b7ac4d76402.png">

**Comment by liqizhang0011** [comment]
still...

**Comment by MurphyPone** [comment]
> I don't have the issue with this setting. Once I set `"python.terminal.activateEnvironment": true`, the issue resurfaces.

This works as an interim solution for me.

**Comment by Suida** [comment]
> > I don't have the issue with this setting. Once I set `"python.terminal.activateEnvironment": true`, the issue resurfaces.
> 
> This works as an interim solution for me.

The same here. It looks like that vscode terminal automatically activating python envs will spawn it.

**Comment by liqizhang0011** [comment]
> > I don't have the issue with this setting. Once I set `"python.terminal.activateEnvironment": true`, the issue resurfaces.
> 
> This works as an interim solution for me.

Thanks!

**Comment by glebarez** [comment]
Is there any workarounds without setting python.terminal.activateEnvironment to false?

**Comment by cyrlop** [comment]
Having the same issue here on VSCode 1.47.0

**Comment by neuronflow** [comment]
same here, newest osx on host accessing ubuntu 1804 remote and using conda as env manager.

**Comment by bonfire62** [comment]
Having the same issue here.

**Comment by roblourens** [comment]
The Python team has released a fix in the latest build of the extension. Could someone check that you are on at least `2020.7.94776` and verify that it is fixed?

**Comment by brbecker** [comment]
I am on VSCode `1.47.2` with Python `2020.7.94776` and I'm still getting a Check remote terminal, even after a full restart of VScode. I do have `"python.terminal.activateEnvironment": true`.

**Comment by benlindsay** [comment]
Same experience as @brbecker. I'm on the latest version, and when I have `"python.terminal.activateEnvironment": true`, I get the multiple "Check remote" terminals. Setting `"python.terminal.activateEnvironment": false` fixes it, but that's frustrating because it is really nice to have the terminal automatically activate the environment

**Comment by virtuald** [comment]
I have a similar issue on VSCode 1.47.2 with an OSX Host, Ubuntu 18.04 remote. 2020.7.96456 python extension.

**Comment by karrtikr** [comment]
We can confirm it's not been fixed yet. We have [identified](https://github.com/microsoft/vscode-python/issues/11122#issuecomment-663593132) the issue and will be releasing the fix soon. Thanks for cooperating.

**Comment by roblourens** [comment]
This should be fixed with the latest VS Code Insiders https://code.visualstudio.com/insiders and the latest version of the Python extension. Can anyone confirm?

**Comment by karrtikr** [comment]
I can confirm I no longer see the issue.

**Comment by Aetherbase** [comment]
@roblourens when would this be merged with the non-insiders version?

**Comment by roblourens** [comment]
This week - Wednesday or Thursday.
