### ISSUE TITLE
Remote-SSH: Opening terminal display Starting...

### ISSUE THREAD

**Issue by crpig** [microsoft/vscode-remote-release#2313]
- VSCode Version: 1.42.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 16.04.6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect ubuntu via ssh, browsing and edit remote file work fine.
2. open a new terminal, it display 'Starting...'

Please refer to the attachment trace log for more information.
[vscode trace log.txt](https://github.com/microsoft/vscode-remote-release/files/4171830/vscode.trace.log.txt)

**Comment by crpig** [comment]
It seems this issue is related with ssh tunnel.
Can you help confirm what vscode exactly did when trying to prepare the ssh tunnel?

e.g.
[01:29:55.533] Remote server is listening on port 34100
[01:29:55.533] Parsed server configuration: {"agentPort":34100,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000"}
**[01:29:55.539] Starting forwarding server. localPort 53817 -> socksPort 53812 -> remotePort 34100**
**[01:29:55.543] Forwarding server listening on 53817**
[01:29:55.543] Waiting for ssh tunnel to be ready
**[01:29:55.548] Tunneled remote port 34100 to local port 53817**
[01:29:55.549] Resolved "ssh-remote+crpig" to "127.0.0.1:53817"

**Comment by Tyriar** [comment]
If the rest of VS Code works it shouldn't be related to the SSH tunnel. It's likely a race condition in the terminal.

**Comment by pshroff04** [comment]
Same issue. It was working fine 2-3 days back. But after the update restarted the IDE and SSH is stuck at starting.... 
VSCode Version: (initial) : 1.41.1
Local OS Version: Windows 10
Remote OS Version: centOS
Remote Extension/Connection Type: SSH

**Comment by CodingPapi** [comment]
same issue, I am not sure if this issue belongs to vscode, because I tested using two ubuntu server, one is good and another one keep starting in open remote terminal, I can open remote folders and browse files, but almost all remote extensions not work, in ubuntu server I can see lots of socket in close wait state

tcp        0      0 127.0.0.1:48071         127.0.0.1:36445         CLOSE_WAIT  -
tcp        0      0 127.0.0.1:48071         127.0.0.1:36471         CLOSE_WAIT  -
tcp        0      0 127.0.0.1:48071         127.0.0.1:35171         CLOSE_WAIT  -
tcp        0      0 127.0.0.1:50670         127.0.0.1:59445         CLOSE_WAIT  -
tcp        0      0 127.0.0.1:50670         127.0.0.1:59494         CLOSE_WAIT  -
tcp        0      0 127.0.0.1:48071         127.0.0.1:35215         CLOSE_WAIT  -

**Comment by abhijeetmanhas** [comment]
I'm also facing this same issue, whenever I use remote ssh. 
![Screenshot from 2020-07-27 12-46-09](https://user-images.githubusercontent.com/43112347/88514223-52292c80-d007-11ea-929d-68a73502145f.png)
Any shell options are not shown

**Comment by cncolder** [comment]
I have the same issue.
Fixed after ssh as `root`

**Comment by RanjeetEppa18** [comment]
I connected via .pem file as ssh. It is connected successfully but the terminal always keeps showing Starting...

**Comment by gowtham614** [comment]
I am seeing the same issue as well. Remote ssh terminal is not opening, my remote ssh server is ubuntu, client is windows 10. Attached the vscode version file as PNG
![client](https://user-images.githubusercontent.com/8025047/98906386-cf22c980-2471-11eb-95a1-c8b7dcdf4c7c.PNG)
![remoteServer](https://user-images.githubusercontent.com/8025047/98906389-cfbb6000-2471-11eb-8632-8337369182a8.PNG)



 the Log(Window) shows:

[2020-11-11 22:57:27.543] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] reconnected!
[2020-11-11 22:57:47.138] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
[2020-11-11 22:57:47.549] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-11-11 22:57:47.549] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] waiting for 5 seconds before reconnecting...
[2020-11-11 22:57:52.550] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] resolving connection...
[2020-11-11 22:57:52.550] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] connecting to 127.0.0.1:53773...
[2020-11-11 22:57:52.807] [renderer1] [info] [remote-connection][ExtensionHost][39d24…][reconnect] reconnected!

Log(Remote Server) shows this

[2020-11-11 22:57:32.307] [remoteagent] [info] [127.0.0.1][39d24d89][ExtensionHostConnection] The client has reconnected.
[2020-11-11 22:57:57.571] [remoteagent] [info] [127.0.0.1][39d24d89][ExtensionHostConnection] The client has reconnected.
[2020-11-11 22:58:22.678] [remoteagent] [info] [127.0.0.1][39d24d89][ExtensionHostConnection] The client has reconnected.
[2020-11-11 22:58:48.544] [remoteagent] [info] [127.0.0.1][39d24d89][ExtensionHostConnection] The client has reconnected.

**Comment by 4F2E4A2E** [comment]
on centos8.2-minimal the dev pkgs are required in order for vscode-server to be installed correctly:  
```bash
sudo yum -y update
sudo yum -y groupinstall "Development Tools"
```

**Comment by mimikun** [comment]
I have same issue.
but, my remote host is WSL.

Versions:
```
version: 1.52.1 (user setup)
commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

```
Remote OS version: Ubuntu 20.04
Remote Extension/Connection Type: WSL
```

**Comment by DiegoMagdaleno** [comment]
+1 for this in WSL

**Comment by Tyriar** [comment]
This may get better/fixed in 1.53 due to https://github.com/microsoft/vscode/pull/113938

**Comment by DiegoMagdaleno** [comment]
I debugged this issue at least for WSL and I dont know if this could be helpful:

What I do because I get annoyed if I have to type my SSH passphrase for Git, is setting up SSH_AUTH_SOCK to another socket that forwards the request to the SSH agent on Windows, here is the setup:

SSH agent forwarding: 
```sh
diego@DiegoComputer:/mnt/c/Users/DiegoMagdaleno$ cat ~/.zsh/ssh-agent.sh
function is_wsl() {
    [ -n "$WSL_DISTRO_NAME" ] && return 0 || return 1
}

if is_wsl; then
    relayexe="$(wslpath 'C:/Users/DiegoMagdaleno/AppData/Roaming/wsl2-ssh-gpg-agent-relay.exe')"
    export SSH_AUTH_SOCK="$HOME/.ssh/agent.sock"
        rm -f "$SSH_AUTH_SOCK"
        setsid --fork socat UNIX-LISTEN:"$SSH_AUTH_SOCK,fork" EXEC:"$relayexe -ei -ep -s //./pipe/openssh-ssh-agent",nofork
    unset relayexe
fi```

GPG agent forwarding 
```sh
function is_wsl() {
    [ -n "$WSL_DISTRO_NAME" ] && return 0 || return 1
}

if is_wsl; then
    relayexe="$(wslpath 'C:/Users/DiegoMagdaleno/AppData/Roaming/wsl2-ssh-gpg-agent-relay.exe')"
    for sock in "$HOME/.gnupg/S.gpg-agent"; do
            rm -f "$sock"
            mkdir -p "$(dirname "$sock")"
            setsid --fork socat UNIX-LISTEN:"$sock,fork" EXEC:"$relayexe -ei -ep -s -a 'C:/Users/DiegoMagdaleno/AppData/Roaming/gnupg/S.gpg-agent'",nofork
    done
    unset sock
    unset relayexe
fi```

This however breaks VScode, not only the terminal but it also breaks stuff like the Rust extension, however, when I tell bash to don't source this configuration files, everything works again, I don't know if its possible to make VScode use its own GPG and SSH sockets so it doesn't conflict with my forwarded sockets (I really don't know if that's the issue but it seems like it).

I can share logs but I don't notice a relevant difference:

With no GPG or SSH agent forwarding:

```[2021-01-12 12:44:14.323] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-01-12 12:44:14.323] [remoteagent] [info] Extension host agent started.
[2021-01-12 12:44:14.493] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] New connection established.
[2021-01-12 12:44:14.494] [remoteagent] [info] [::ffff:172.22.128.1][6855c6d6][ManagementConnection] New connection established.
[2021-01-12 12:44:14.541] [remoteagent] [info] Listing 0 persistent terminals, 0 total terminals
[2021-01-12 12:44:15.011] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] <6442> Launched Extension Host Process.
[2021-01-12 12:44:23.818] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/mnt/c/Users/DiegoMagdaleno/AppData/Local/Application Data" points to "/mnt/c/Users/DiegoMagdaleno/AppData/Local"
[2021-01-12 12:55:22.993] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] The client has reconnected.
[2021-01-12 12:55:44.283] [remoteagent] [info] [::ffff:172.22.128.1][6855c6d6][ManagementConnection] The client has reconnected.
[2021-01-12 12:55:48.190] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] The client has reconnected.
[2021-01-12 12:56:55.165] [remoteagent] [info] [::ffff:172.22.128.1][6855c6d6][ManagementConnection] The client has reconnected.
[2021-01-12 12:57:03.738] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] The client has reconnected.
[2021-01-12 12:57:28.874] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] The client has reconnected.
[2021-01-12 12:57:53.999] [remoteagent] [info] [::ffff:172.22.128.1][e6dea9d3][ExtensionHostConnection] The client has reconnected.
```

With GPG and SSH forwarding:

```
[2021-01-12 13:01:16.397] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-01-12 13:01:16.397] [remoteagent] [info] Extension host agent started.
[2021-01-12 13:01:16.911] [remoteagent] [info] [::ffff:172.22.128.1][b43edb17][ManagementConnection] New connection established.
[2021-01-12 13:01:16.917] [remoteagent] [info] [::ffff:172.22.128.1][71c2ebb8][ExtensionHostConnection] New connection established.
[2021-01-12 13:01:17.149] [remoteagent] [info] Listing 0 persistent terminals, 0 total terminals
[2021-01-12 13:01:26.483] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/mnt/c/Users/DiegoMagdaleno/AppData/Local/Application Data" points to "/mnt/c/Users/DiegoMagdaleno/AppData/Local"
```

**Comment by DiegoMagdaleno** [comment]
Fixed the issue above, basically I don't know why but I was always forwarding stuff again and again, now it only does it once, I added the following line as an if condition in the scripts above:  
`ps -eo args= | grep -q "^socat UNIX-LISTEN:$sock";`

This fixed everything! If someone has a similar WSL setup to mine or similar SSH setup, this is a good solution.

**Comment by ykfq** [comment]
Still exists with latest version `1.54.3`
![image](https://user-images.githubusercontent.com/20741596/111285481-2634e700-867c-11eb-80c7-05eb9ff9fe14.png)

![image](https://user-images.githubusercontent.com/20741596/111285428-1917f800-867c-11eb-9c70-c11e271f34d1.png)

**Comment by GeorgeXCV** [comment]
Also seeing this issue. Not using SSH, working on a web project, restarted `localhost` a few times and now terminal is stuck on "Starting...", restarting VS Code doesn't fix the issue. ` Log (Window)` output is empty.
<img width="281" alt="Screenshot 2021-05-06 17 14 19" src="https://user-images.githubusercontent.com/13811547/117331323-8f6ff400-ae8e-11eb-9e25-6325288a3668.png">

**Comment by spoole50** [comment]
Not sure if it will help anyone, but I experienced a similar problem with no luck troubleshooting. Come to find out, I had enabled a script to run every time I ssh into my server to log all terminal input and output using the Linux `script` command. After disabling, vscode started working as usual.

**Comment by QGB** [comment]
vscode remotessh terminal "starting..."
我知道原因了，因为本机127.0.0.1无法访问，所以无法进行下一步连接。
解决办法：重启
netsh int ipv4 reset
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 邻居，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 路径，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
请求的操作需要提升(作为管理员运行)。
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。
