### ISSUE TITLE
Failed to find a non-Windows SSH installed. Password prompts may not be displayed properly! Disable `remote.SSH.useLocalServer` if needed.

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode-remote-release#2525]
![111](https://user-images.githubusercontent.com/35714131/76390027-947b0580-63a7-11ea-81be-99744f81098c.PNG)

- VSCode Version: 1.44.0
- Local OS Version: win10
- Remote OS Version: centos 7
- Remote Extension/Connection Type: SSH/Docker/WSL：  ssh

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by playcock** [comment]
@lfjbb I am getting this message on the nightly build as well.

**Comment by playcock** [comment]
And then when I go to recursively remove the .vscode-server directly, I get the message "device or resource busy". So, then I kill the bash and wget processes in the .vscode-server/bin directory. After that, I remove the .vscode-server recursively and attempt to connect to the host, which still results in the "Failed to find a non-Windows SSH installed" message being displayed again. I am unable to connect to the host at all, when, before today, I was able to. Also, the bash and wget processes in the .vscode-server/bin directory lock up again.

**Comment by playcock** [comment]
![image](https://user-images.githubusercontent.com/9416592/76421821-a1cdcb00-637a-11ea-99c3-0832ca6eb444.png)

**Comment by playcock** [comment]
I rolled back to vscode version 1.42.1, reinstalled Remote - SSH Nightly, and still experience this issue.

**Comment by playcock** [comment]
If it helps the devs at all, I get stuck on the wget process in my terminal window:
"Downloading with wget"

**Comment by playcock** [comment]
Here are a couple of messages in the terminal window that might be useful:
```
[09:45:10.052] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:45:10.108] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:45:10.108] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:45:10.109] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[09:45:10.110] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[09:45:10.111] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
```

**Comment by RobCannon** [comment]
I don't understand the message.  I have Windows OpenSSH installed and it (still) works with Remote SSH.

**Comment by csjjzhou** [comment]
I have ths same question. waiting answer.

**Comment by yliuhb** [comment]
i also have this problem

**Comment by iiimashiii** [comment]
I get the same error message in my environment.

The error message indicated that the hard link failed.
`ln` failed because the link already exists.
The file looks like this:.
`~/.vscode -server/bin/{some alnums}/vscode -remote-lock. {user name}. {some alnums}`

I could not determine the need for these files, but they were removed and an SSH connection was established.

For your information.

**Comment by MountainLovers** [comment]
I have this problem either. Waiting for solutions.😭

**Comment by MountainLovers** [comment]
> I have this problem either. Waiting for solutions.😭

Alright, I found the solution in another issue. Please check here:
https://github.com/microsoft/vscode-remote-release/issues/2523#issuecomment-597551802
It seems like that the update has some bugs. Reinstall the old version.
Best wishes!

**Comment by tokikanno** [comment]
I've encountered the same situation. I solved by the delete lock files method via @iiimashiii 

I've also tried re-install an older version of ssh remote extension but got no lucks here. 
also cc @MountainLovers

**Comment by gdlx** [comment]
Deleting the lock files fixed the connection issue but I still have the "Failed to find a non-Windows SSH installed" message (no visible consequence though)

**Comment by lfjbb** [comment]
I just update vscode again then I can connect to the remote.  don't know why.

**Comment by sfsccn** [comment]
Have you tried changing `remote.SSH.path`  to `C:\WINDOWS\System32\OpenSSH\ssh.exe` as described in https://github.com/microsoft/vscode-remote-release/issues/2521#issuecomment-598178584 and https://github.com/microsoft/vscode-remote-release/issues/2522#issuecomment-598043939?

**Comment by playcock** [comment]
> Have you tried changing `remote.SSH.path` to `C:\WINDOWS\System32\OpenSSH\ssh.exe` as described in [#2521 (comment)](https://github.com/microsoft/vscode-remote-release/issues/2521#issuecomment-598178584) and [#2522 (comment)](https://github.com/microsoft/vscode-remote-release/issues/2522#issuecomment-598043939)?

Thank you for this. This is good information, but I am still stuck.

I changed the setting "remote.SSH.path" to use "C:\WINDOWS\System32\OpenSSH\ssh.exe" after confirming that ssh.exe exists in the OpenSSh directory.

I uninstalled Remote - SSH (nightly) then reinstalled it.

I attempt to "Connect to Host..". The "Failed to find a non-Windows SSH installed" is no longer there, but then I get stuck on "Downloading VS Code Server".

![image](https://user-images.githubusercontent.com/9416592/76651290-91644e80-653a-11ea-9a9b-b2a584f47c62.png)

So then, I try to recursively remove the .vscode-server directly and get the message "device or resource busy". So, then I kill the bash and wget processes in the .vscode-server/bin directory. After that, I remove the .vscode-server recursively.

I attempt to "Connect to Host..". I get stuck on "Downloading VS Code Server".

I get stuck on the wget process in my terminal window:
"Downloading with wget".

![image](https://user-images.githubusercontent.com/9416592/76651918-e18fe080-653b-11ea-81c9-eb9b20de20fd.png)

**Comment by YitianChen1996** [comment]
Same issue...
Looking forward to a solution...

**Comment by HakunanMatatat** [comment]
What's wrong?I found out that remote SSH is the best not long ago.

**Comment by ArchNew** [comment]
> > I have this problem either. Waiting for solutions.😭
> 
> Alright, I found the solution in another issue. Please check here:
> [#2523 (comment)](https://github.com/microsoft/vscode-remote-release/issues/2523#issuecomment-597551802)
> It seems like that the update has some bugs. Reinstall the old version.
> Best wishes!

Thanks! Downgrading the Remote - SSH extension to 0.49.0 solved my problem.

**Comment by alexign** [comment]
Set _Remote.SSH: Use Local Server_ to **off** works for me. After that vscode continue to work with ssh agent smoothly. With this setting in **on** vscode throw me passphrase dialog. Also I think that this option is troublesome because I remembed that with multiple windows opened it cause some troubles when say laptop is woke up from sleep mode and some windows have crashed.
Version 1.43

**Comment by wuyouning** [comment]
I have ths same question. waiting answer.

**Comment by jgxs** [comment]
I have ths same question. waiting answer.

**Comment by ryanlrobinson** [comment]
My problem was fixed by the solution by alexign above, turning off the Use Local Server setting. Thanks!

**Comment by roblourens** [comment]
This notification means just what it says. We try to use some other SSH build (usually, the one that comes with Git). If not, you may get a password popup with no prompt message. If this is not applicable to you, you can click "don't show again"
