### ISSUE TITLE
ProxyCommand option failed with 0.50.0

### ISSUE THREAD

**Issue by VoVAllen** [microsoft/vscode-remote-release#2541]
- VSCode Version: 1.43.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

ssh config file:
```
Host proxy-target
    HostName IP ADDRESSS
    User ubuntu
    IdentityFile D:\key\key.pem
    ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -q -W %h:%p proxy1
```

Worked well with 0.49.0 but failed on 0.50.0. 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by xgdgsc** [comment]
changing `C:\Windows\System32\OpenSSH\ssh.exe` to `ssh` fixed in my case.

**Comment by VoVAllen** [comment]
Change to `ssh` doesn't fix in my case and it doesn't work with powershell's `ssh`

**Comment by roblourens** [comment]
Seems to be a known issue on windows: https://github.com/microsoft/vscode-remote-release/issues/18
