### ISSUE TITLE
Slow server startup on qemu

### ISSUE THREAD

**Issue by m5ls7h** [microsoft/vscode-remote-release#3485]
- VSCode Version: 1.47.3
- Local OS Version: Debian 10.3
- Remote OS Version: [ubuntu-20.04-server-cloudimg-amd64](https://cloud-images.ubuntu.com/releases/20.04/release/ubuntu-20.04-server-cloudimg-amd64.img) running on qemu
- Remote Extension/Connection Type: SSH (Remote-ssh 0.51.0)

Steps to Reproduce:

1. Connect to remote system by remote-ssh extension
2. vscode server is downloaded to remote system
3. Starting `server.sh` on the remote system fails with exception in `buffer.js:573`. The same exception is thrown if `server.sh` is started manually at the remote system by

```text
/home/ubuntu/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0
```

Any ideas how to fix this exception?

```text
[18:05:12.994] > ubuntu@debqemu.lan's password:
[18:05:12.994] Showing password prompt
[18:05:15.744] Got password response
[18:05:15.744] "install" wrote data to terminal: "********"
[18:05:15.756] >
>
[18:05:23.260] > 9b1f68776169: running
>
[18:05:23.678] > Acquiring lock on /home/ubuntu/.vscode-server/bin/91899dcef7b8110878ea59626991a1
> 8c8a6a1b3e/vscode-remote-lock.ubuntu.91899dcef7b8110878ea59626991a18c8a6a1b3e
>
[18:05:23.717] > \ln /home/ubuntu/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vsc
> ode-remote-lock.ubuntu.91899dcef7b8110878ea59626991a18c8a6a1b3e.target /home/ubu
> ntu/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/vscode-remote-lo
> ck.ubuntu.91899dcef7b8110878ea59626991a18c8a6a1b3e
>
[18:05:23.811] > Found existing installation at /home/ubuntu/.vscode-server/bin/91899dcef7b811087
> 8ea59626991a18c8a6a1b3e...
>
[18:05:24.020] > SHELL=/bin/bash
> PWD=/home/ubuntu
> LOGNAME=ubuntu
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/home/ubuntu
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server  
> SSH_CONNECTION=192.168.171.133 54448 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=ubuntu
> SHLVL=1
> XDG_SESSION_ID=7
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=192.168.171.133 54448 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
> r/local/games
[18:05:24.026] >
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> _=/usr/bin/printenv
> Starting server with command... /home/ubuntu/.vscode-server/bin/91899dcef7b81108
> 78ea59626991a18c8a6a1b3e/server.sh --host=127.0.0.1 --enable-remote-auto-shutdow
> n  --port=0 &> "/home/ubuntu/.vscode-server/.91899dcef7b8110878ea59626991a18c8a6
> a1b3e.log" < /dev/null
[18:05:24.035] >
>
[18:05:24.209] > Waiting for server log...
>
[18:05:24.895] > Waiting for server log...
>
[18:05:25.523] > Waiting for server log...
>
[18:05:26.213] > Waiting for server log...
>
[18:05:26.863] > Waiting for server log...
>
[18:05:27.404] >  
> *
[18:05:27.411] >
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[18:05:27.420] >
> *
>  
[18:05:27.429] >
>
[18:05:27.620] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-serve
> r/.91899dcef7b8110878ea59626991a18c8a6a1b3e.log >>>
>
[18:05:27.649] > buffer.js:573
>       if (encoding === 'utf8') return buf.utf8Slice(start, end);
>                                           ^
>
> RangeError: Index out of range
>     at stringSlice (buffer.js:573:43)
>     at Buffer.toString (buffer.js:643:10)
>     at Object.readFileSync (fs.js:393:41)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:784:22)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
>     at internal/main/run_main_module.js:17:11 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> <<< End of server log
> 9b1f68776169##32##
[18:05:27.649] Received install output: 9b1f68776169##32##
[18:05:27.650] Resolver error: The VS Code Server failed to start
[18:05:27.653] ------




[18:05:27.873] >
>
[18:05:28.142] "install" terminal command done
[18:05:28.143] Install terminal quit with output:

```

**Comment by gyzerok** [comment]
@bpasero this looks to me like an that might be connected with the encodings work.

**Comment by bpasero** [comment]
I am not convinced because this seems to be the native node.js `Buffer` acting up. 

@roblourens @alexdima any clues?

**Comment by m5ls7h** [comment]
My impression is, that it is some kind of timing problem.
As mentioned in the system environment above, I'm running ubuntu-20.04-server-cloudimg-amd64 on qemu.
- If I run qemu without virtualization acceleration, the error occurs that vscode-server can not be started
- If i run qemu with virtualization accelaration (speeds up the system with factor 5), vscode-server starts up fine
So maybe the log file creation code includes some timing conditions?

btw, other applications like git, compiling code, ... run well from the command line also in the slow qemu mode.

**Comment by swebs** [comment]
I have this same problem, also in a non-accelerated QEMU remote, so perhaps that is further evidence of some kind of timing issue...

**Comment by alexdima** [comment]
Here's what I found https://github.com/nodejs/node/issues/34709

**Comment by m5ls7h** [comment]
@alexdima thank you for the hint, nodejs/node#34709 seems to be similar to my problem. Unfortunately no solution provided.

**Comment by m5ls7h** [comment]
An update with some tests with vscode 1.48.2
The first connection attempt to the qemu virtual machine runs in a time out:
```text
[13:22:28.944] Showing password prompt
[13:22:33.315] Got password response
[13:22:33.316] "install" wrote data to terminal: "********"
[13:22:33.316] > 31a86ebd1258: running
> 
[13:22:33.316] > Acquiring lock on /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6
> e9ea56afa657e454193f72aef85bd0
> 
[13:22:33.316] > \ln /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6e9ea56afa657e4
> 54193f72aef85bd0.target /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a047
> 9759d6e9ea56afa657e454193f72aef85bd0
> 
[13:22:33.317] > Installing to /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0...
> 
[13:22:33.318] > 31a86ebd1258%%1%%
> 
[13:22:33.318] > Downloading with wget
> 
[13:22:35.579] > 54193f72aef85bd0.target /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6e9ea56afa657e454193f72aef85bd0
> Installing to /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0...
> 31a86ebd1258%%1%%
> Downloading with wget
> 
> 
[13:22:37.435] > Download complete
> 
[13:22:37.479] > 31a86ebd1258%%2%%
> 
[13:22:39.761] > Installing to /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0...
> 31a86ebd1258%%1%%
> Downloading with wget
> Download complete
> 31a86ebd1258%%2%%

[13:22:42.223] > SHELL=/bin/bash
> PWD=/home/ubuntu
> LOGNAME=ubuntu
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/home/ubuntu
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server
> SSH_CONNECTION=157.163.215.170 49944 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=ubuntu
> SHLVL=1
> XDG_SESSION_ID=7
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=157.163.215.170 49944 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> _=/usr/bin/printenv
> OLDPWD=/home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0
> 
[13:22:42.275] > Starting server with command... /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log" < /dev/null
> 
[13:22:42.394] > Waiting for server log...
> 
[13:22:43.115] > Waiting for server log...
> 
[13:22:43.891] > Waiting for server log...
> 
[13:22:44.656] > Waiting for server log...
> 
[13:22:45.443] > Waiting for server log...
> 
[13:22:45.975] >  
> *
> 
[13:22:46.023] > * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[13:22:46.342] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log >>>
> 
[13:22:46.411] > *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
[13:22:46.453] > <<< End of server log
> 31a86ebd1258##32##   
> 
[13:22:46.453] Received install output: 31a86ebd1258##32##
[13:22:46.454] Resolver error: The VS Code Server failed to start
[13:22:46.460] ------
```
But this time the vscode server is successfully installed and up and running.
Therefore, a second connection attempt succeeds:
```text
Warning: Permanently added '[192.168.171.219]:5001' (ECDSA) to the list of known hosts.
ubuntu@192.168.171.219's password:
32cd8ad7e042: running
Acquiring lock on /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6e9ea56afa657e454193f72aef85bd0
\ln /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6e9ea56afa657e454193f72aef85bd0.target /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ubuntu.a0479759d6e9ea56afa657e454193f72aef85bd0
Found existing installation at /home/ubuntu/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0...
Found running server...

*
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

Checking server status on port 40491 with wget
32cd8ad7e042: start
sshAuthSock====
agentPort==40491==      
osReleaseId==ubuntu==   
arch==x86_64==
webUiAccessToken====    
tmpDir==/run/user/1000==
platform==linux==       
32cd8ad7e042: end     
```
So for now, I can use vscode with this two connection attempts. Seems like the nodejs behavior has changed in the last days.
Is it possible to increase the vscode server connection timeout to get the connection on the first attempt?

**Comment by alexdima** [comment]
Just a few days ago I increased the initial timeout from 30s to 120s -- https://github.com/microsoft/vscode/commit/40cb0f3433de79be3bc63eef6430c957884c8ae9

So our upcoming stable release or the current insiders already has the timeout increased.

**Comment by swebs** [comment]
I just tried again and I can go from selecting "Remote-SSH: Connect to host" to having it fail in less than 30 seconds...

**Comment by alexdima** [comment]
@swebs To clarify, what version are you trying with? (the stable channel does not contain the change yet).

@roblourens Is there some other timeout on the SSH side?

**Comment by roblourens** [comment]
@swebs could you open a new issue with a log? Unless you have exactly the same log output as the OP it's probably a different issue. SSH does have its own timeout and this implies that there was just no response from our ssh command (or a bad response or something else entirely)

**Comment by swebs** [comment]
I have remote-ssh version 0.51.0. The reason I mentioned the 30 second thing is that if the OLD timeout was 30 seconds, and my attempt fails in less than that, then it seems to me that the timeout isn't the issue... it isn't getting that far? But I am not even really sure where the timeout fits into this.

I haven't created a new issue yet, because I think my output looks extremely similar to the original report. Here it is below. The contents of the log file follows (which just seems to be a small subset of this output).

"Output" visible in vscode: (some blank lines with only ">" removed)
```
[16:55:20.952] Log Level: 2
[16:55:20.960] remote-ssh@0.51.0
[16:55:20.960] win32 x64
[16:55:20.962] SSH Resolver called for "ssh-remote+127.0.0.1", attempt 1
[16:55:20.962] SSH Resolver called for host: 127.0.0.1
[16:55:20.962] Setting up SSH remote "127.0.0.1"
[16:55:20.997] Using commit id "a0479759d6e9ea56afa657e454193f72aef85bd0" and quality "stable" for server
[16:55:21.001] Install and start server if needed
[16:55:21.644] Checking ssh with "ssh -V"
[16:55:21.754] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[16:55:21.757] Running script with connection command: ssh -T -D 56953 127.0.0.1 bash
[16:55:21.762] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:55:22.294] > oper@127.0.0.1's password:]0;C:\WINDOWS\System32\cmd.exe
[16:55:22.294] Got some output, clearing connection timeout
[16:55:22.295] Showing password prompt
[16:55:25.996] Got password response
[16:55:25.997] "install" wrote data to terminal: "************"
[16:55:26.012] > 
[16:55:26.602] > f1623e7f9e39: running
[16:55:27.120] > Acquiring lock on /home/oper/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72
> aef85bd0/vscode-remote-lock.oper.a0479759d6e9ea56afa657e454193f72aef85bd0       
[16:55:27.204] > \ln /home/oper/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscod
> e-remote-lock.oper.a0479759d6e9ea56afa657e454193f72aef85bd0.target /home/oper/.v
> scode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/vscode-remote-lock.ope
> r.a0479759d6e9ea56afa657e454193f72aef85bd0
[16:55:27.317] > Found existing installation at /home/oper/.vscode-server/bin/a0479759d6e9ea56afa
> 657e454193f72aef85bd0...
[16:55:27.593] > SHELL=/bin/bash
> LANGUAGE=en_CA:en
> PWD=/home/oper
> LOGNAME=oper
> XDG_SESSION_TYPE=tty
> HOME=/home/oper
> LANG=en_CA.UTF-8
> VSCODE_AGENT_FOLDER=/home/oper/.vscode-server
> SSH_CONNECTION=10.0.2.2 54070 10.0.2.15 22   
> XDG_SESSION_CLASS=user
> USER=oper
> SHLVL=1
> XDG_SESSION_ID=5
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=10.0.2.2 54070 22
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> MAIL=/var/mail/oper
> _=/usr/bin/printenv
> Starting server with command... /home/oper/.vscode-server/bin/a0479759d6e9ea56af
> a657e454193f72aef85bd0/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown 
[16:55:27.599] > 
>  --port=0 &> "/home/oper/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd
> 0.log" < /dev/null
[16:55:27.611] > 
[16:55:27.834] > Waiting for server log...
[16:55:28.003] > MAIL=/var/mail/oper
> _=/usr/bin/printenv
> Starting server with command... /home/oper/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh --host=127.0.0.1 
> --enable-remote-auto-shutdown  --port=0 &> "/home/oper/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log" < /dev/null  
> Waiting for server log...
> 
[16:55:28.501] > Waiting for server log...
[16:55:29.180] > Waiting for server log...
[16:55:29.435] > Starting server with command... /home/oper/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh --host=127.0.0.1 
> --enable-remote-auto-shutdown  --port=0 &> "/home/oper/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log" < /dev/null  
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
> 
> 
[16:55:29.843] > Waiting for server log...
[16:55:30.248] > Starting server with command... /home/oper/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/server.sh --host=127.0.0.1 
> --enable-remote-auto-shutdown  --port=0 &> "/home/oper/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log" < /dev/null  
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
> 
> 
[16:55:30.517] > Waiting for server log...
[16:55:31.043] >  
> *
[16:55:31.061] > * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[16:55:31.242] > Server did not start successfully. Full server log at /home/oper/.vscode-server/.a0479759d6e9ea56afa657e454193f72aef85bd0.log >>>
[16:55:31.278] > buffer.js:573
>       if (encoding === 'utf8') return buf.utf8Slice(start, end);
>                                           ^
> 
> RangeError: Index out of range
>     at stringSlice (buffer.js:573:43)
>     at Buffer.toString (buffer.js:643:10)
>     at Object.readFileSync (fs.js:393:41)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:784:22)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)        
>     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)      
>     at internal/main/run_main_module.js:17:11 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> <<< End of server log
> f1623e7f9e39##32##
[16:55:31.279] Received install output: f1623e7f9e39##32##
[16:55:31.280] Resolver error: The VS Code Server failed to start
[16:55:31.287] ------



[16:55:31.783] > 
[16:55:32.110] "install" terminal command done
[16:55:32.111] Install terminal quit with output: 
```

Log file from remote server:
```
buffer.js:573
      if (encoding === 'utf8') return buf.utf8Slice(start, end);
                                          ^

RangeError: Index out of range
    at stringSlice (buffer.js:573:43)
    at Buffer.toString (buffer.js:643:10)
    at Object.readFileSync (fs.js:393:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:784:22)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by m5ls7h** [comment]
With the current insider build 
```text
Version: 1.50.0-insider (user setup)
Commit: e13875b77c89b95f20ccb5667e14ff164c198e57
Date: 2020-09-15T05:35:57.362Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134
```
the timeout (or some other failure?) did not change for me.
The first connection attempt fails
```text
[08:25:58.204] Log Level: 2
[08:25:58.217] remote-ssh@0.55.0
[08:25:58.217] win32 x64
[08:25:58.219] SSH Resolver called for "ssh-remote+ubuntu-qemu", attempt 1
[08:25:58.219] SSH Resolver called for host: ubuntu-qemu
[08:25:58.219] Setting up SSH remote "ubuntu-qemu"
[08:25:58.276] Using commit id "e13875b77c89b95f20ccb5667e14ff164c198e57" and quality "insider" for server
[08:25:58.280] Install and start server if needed
[08:25:58.285] Checking ssh with "ssh -V"
[08:25:58.391] > OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

[08:25:58.394] Running script with connection command: ssh -T -D 59840 ubuntu-qemu bash
[08:25:58.402] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:25:58.591] > 
[08:25:58.591] Got some output, clearing connection timeout
[08:25:59.183] > Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts
> .
> 
[08:25:59.465] > ubuntu@127.0.0.1's password:
[08:25:59.465] Showing password prompt
[08:26:06.151] Got password response
[08:26:06.152] "install" wrote data to terminal: "********"
[08:26:06.152] > Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts.
> ubuntu@127.0.0.1's password:
> 
[08:26:06.152] Showing password prompt
[08:26:13.447] Got password response
[08:26:13.448] "install" wrote data to terminal: "********"
[08:26:13.448] > 
> 
[08:26:17.028] > abe3d2c55fb0: running
> 
[08:26:17.746] > Acquiring lock on /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/vscode-remote-lock.ubuntu.e13875b77c89b95f20ccb5667e14ff164c198e57
> 
[08:26:17.872] > Found existing installation at /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57...
> 
[08:26:18.182] > SHELL=/bin/bash
> PWD=/home/ubuntu
> LOGNAME=ubuntu
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/home/ubuntu
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server-insiders
> SSH_CONNECTION=157.163.215.170 35810 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=ubuntu
> SHLVL=1
> XDG_SESSION_ID=1
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=157.163.215.170 35810 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> _=/usr/bin/printenv
> Starting server with command... /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server-insid
> ers/.e13875b77c89b95f20ccb5667e14ff164c198e57.log" < /dev/null
> 
[08:26:18.383] > Waiting for server log...
> 
[08:26:19.148] > Waiting for server log...
> 
[08:26:19.902] > Waiting for server log...
> 
[08:26:20.649] > Waiting for server log...
> 
[08:26:21.462] > Waiting for server log...
> 
[08:26:22.054] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> 
[08:26:22.090] > *
> 
> 
[08:26:22.404] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-server-insiders/.e13875b77c89b95f20ccb5667e14ff164c198e57.log >>>
> 
[08:26:22.464] > 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> <<< End of server log
> abe3d2c55fb0##32##
> 
[08:26:22.464] Received install output: abe3d2c55fb0##32##
[08:26:22.471] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[08:26:22.475] ------
[08:26:23.174] "install" terminal command done
[08:26:23.175] Install terminal quit with output: 
```
but the second attempt succeeds
```text
[08:27:42.501] Log Level: 2
[08:27:42.514] remote-ssh@0.55.0
[08:27:42.514] win32 x64
[08:27:42.515] SSH Resolver called for "ssh-remote+ubuntu-qemu", attempt 1
[08:27:42.516] SSH Resolver called for host: ubuntu-qemu
[08:27:42.516] Setting up SSH remote "ubuntu-qemu"
[08:27:42.572] Using commit id "e13875b77c89b95f20ccb5667e14ff164c198e57" and quality "insider" for server
[08:27:42.574] Install and start server if needed
[08:27:42.578] Checking ssh with "ssh -V"
[08:27:42.694] > OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

[08:27:42.699] Running script with connection command: ssh -T -D 59892 ubuntu-qemu bash
[08:27:42.707] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:27:42.905] > 
[08:27:42.905] Got some output, clearing connection timeout
[08:27:43.396] > Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts
> .
> 
[08:27:43.589] > ubuntu@127.0.0.1's password:
[08:27:43.590] Showing password prompt
[08:27:49.821] Got password response
[08:27:49.822] "install" wrote data to terminal: "********"
[08:27:49.868] > 
> 
[08:27:57.403] > 372ad0c23ea3: running
> 
[08:27:58.058] > Acquiring lock on /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb
> 5667e14ff164c198e57/vscode-remote-lock.ubuntu.e13875b77c89b95f20ccb5667e14ff164c
> 198e57
> 
[08:27:58.181] > Found existing installation at /home/ubuntu/.vscode-server-insiders/bin/e13875b7
> 7c89b95f20ccb5667e14ff164c198e57...
> 
[08:27:58.430] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[08:27:58.804] > Checking server status on port 38423 with wget
> 
[08:27:59.404] > 372ad0c23ea3: start
> sshAuthSock====
> listeningOn==38423==
> osReleaseId==ubuntu==
> arch==x86_64==
> 
[08:27:59.431] > webUiAccessToken====
> tmpDir==/run/user/1000==
> platform==linux==
> 372ad0c23ea3: end
> 
[08:27:59.431] Received install output: 
sshAuthSock====
listeningOn==38423==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==

[08:27:59.432] Remote server is listening on 38423
[08:27:59.432] Parsed server configuration: {"remoteListeningOn":{"port":38423},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000","platform":"linux"}
[08:27:59.434] Starting forwarding server. localPort 59900 -> socksPort 59892 -> remotePort 38423
[08:27:59.436] Forwarding server listening on 59900
[08:27:59.436] Waiting for ssh tunnel to be ready
[08:27:59.438] Tunneled 38423 to local port 59900
[08:27:59.438] Resolved "ssh-remote+ubuntu-qemu" to "127.0.0.1:59900"
[08:27:59.439] [Forwarding server 59900] Got connection 0
[08:27:59.462] ------




[08:27:59.503] [Forwarding server 59900] Got connection 1
[08:27:59.505] [Forwarding server 59900] Got connection 2
[08:30:59.350] > 
```
So I can work with that for the moment.

**Comment by m5ls7h** [comment]
@swebs The `buffer.js:573  if (encoding === 'utf8') return buf.utf8Slice(start, end);` exception was the original problem when I opened this issue. But I didn't have this exception anymore within the last 10 days.

**Comment by alexdima** [comment]
@roblourens From looking at the log, it looks like we wait for the server to be up and running in 4 seconds (from `08:26:18.182` to `08:26:22.404`). I guess for this machine (perhaps qemu is slow?) 4 seconds is not sufficient, so that's why the second attempt at `08:27:58.430` finds a running server.

```
[08:26:18.182] 
> Starting server with command... /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server-insiders/.e13875b77c89b95f20ccb5667e14ff164c198e57.log" < /dev/null
[08:26:18.383] > Waiting for server log...
[08:26:19.148] > Waiting for server log...
[08:26:19.902] > Waiting for server log...
[08:26:20.649] > Waiting for server log...
[08:26:21.462] > Waiting for server log...
[08:26:22.054] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> 
[08:26:22.090] > *
[08:26:22.404] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-server-insiders/.e13875b77c89b95f20ccb5667e14ff164c198e57.log >>>
> 
```

**Comment by roblourens** [comment]
Thanks @m5ls7h, I wonder if you could try starting the server manually with the command

`/home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0`

and check how long it takes before it prints "extension host agent listening on..."? I can't wait forever because there seem to be a lot of issues where the server fails to start and this will delay us detecting that. I can also just bump it to 8s to see if that is enough for you.

**Comment by m5ls7h** [comment]
@roblourens Starting the server manually takes about 3 seconds:
```text
ubuntu@ubuntu:~$ date; /home/ubuntu/.vscode-server-insiders/bin/e13875b77c89b95f20ccb5667e14ff164c198e57/server.sh --enable-remote-auto-shutdown --port=0
Thu Sep 17 13:55:44 UTC 2020
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*
IP Address: 10.0.2.15
Extension host agent listening on 41047
[13:55:47] Extension host agent started.
```

If started from vscode insiders, timeout is thrown after 4 seconds. 
```text
[15:58:52.455] > SHELL=/bin/bash
> PWD=/home/ubuntu
> LOGNAME=ubuntu
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/home/ubuntu
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server-insiders
> SSH_CONNECTION=157.163.215.170 42890 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=ubuntu
> SHLVL=1
> XDG_SESSION_ID=4
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=157.163.215.170 42890 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> _=/usr/bin/printenv
> OLDPWD=/home/ubuntu/.vscode-server-insiders/bin/d1f267742169584db010716d92addf50d4cd8139
> Starting server with command... /home/ubuntu/.vscode-server-insiders/bin/d1f267742169584db010716d92addf50d4cd8139/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server-insid
> ers/.d1f267742169584db010716d92addf50d4cd8139.log" < /dev/null
> 
[15:58:52.641] > Waiting for server log...
> 
[15:58:53.354] > Waiting for server log...
> 
[15:58:54.075] > Waiting for server log...
> 
[15:58:54.989] > Waiting for server log...
> 
[15:58:55.731] > Waiting for server log...
> 
[15:58:56.267] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[15:58:56.581] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-server-insiders/.d1f267742169584db010716d92addf50d4cd8139.log >>>
> 
[15:58:56.643] > 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> <<< End of server log
> e9dfa590c726##32##
> 
[15:58:56.644] Received install output: e9dfa590c726##32##
[15:58:56.650] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[15:58:56.654] ------

[15:58:57.139] "install" terminal command done
[15:58:57.140] Install terminal quit with output: 
```

**Comment by roblourens** [comment]
So I just pushed an update that changes the timeout to 8 seconds, and we can see whether that helps you. It's in the "nightly" version of the ssh extension (you'll have to uninstall the stable version first)

**Comment by swebs** [comment]
@m5ls7h 's issue seems to have changed since this bug was first filed... and the title has been adjusted... but I still get the "buffer.js" problem, as evidenced by the log I posted. Do we think these are the same issue? They seem quite possibly related, since we are both using very slow qemu VMs etc... but now we get different error messages, right?

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and check me whether it happens there? https://code.visualstudio.com/insiders

**Comment by swebs** [comment]
It looks like I still have the original issue on Insiders.

Here is what I get on:
Version: 1.50.0-insider (user setup)
Commit: 3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
Date: 2020-09-17T17:22:44.035Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Remote-SSH 0.5.0

"Output" (some empty lines removed):
```
[14:49:19.193] Log Level: 2
[14:49:19.211] remote-ssh@0.55.0
[14:49:19.211] win32 x64
[14:49:19.215] SSH Resolver called for "ssh-remote+127.0.0.1", attempt 1
[14:49:19.216] SSH Resolver called for host: 127.0.0.1
[14:49:19.216] Setting up SSH remote "127.0.0.1"
[14:49:19.268] Using commit id "3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8" and quality "insider" for server
[14:49:19.273] Install and start server if needed
[14:49:20.681] Checking ssh with "ssh -V"
[14:49:20.796] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:49:20.805] Running script with connection command: ssh -T -D 51231 127.0.0.1 bash
[14:49:20.812] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:49:22.190] > oper@127.0.0.1's password:]0;C:\WINDOWS\System32\cmd.exe
[14:49:22.191] Got some output, clearing connection timeout
[14:49:22.193] Showing password prompt
[14:49:33.916] Got password response
[14:49:33.917] "install" wrote data to terminal: "************"
[14:49:33.939] > 
[14:49:35.847] > oper@127.0.0.1's password:
> 
> 
> 
[14:49:35.848] Showing password prompt
[14:50:39.826] "install" terminal command done
[14:50:39.827] Install terminal quit with output: oper@127.0.0.1's password:
[14:50:39.827] Received install output: oper@127.0.0.1's password:
[14:50:39.829] Stopped parsing output early. Remaining text: oper@127.0.0.1's password:
[14:50:39.830] Failed to parse remote port from server output
[14:50:39.854] Resolver error: Error: 
	at Function.Create (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at I (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[14:50:39.859] ------



[14:50:47.764] Password dialog canceled
[14:50:47.769] "install" terminal command canceled
[14:50:47.771] > d4d805dfa19d: running
[14:50:47.773] > oper@127.0.0.1's password:
> d4d805dfa19d: running
> 
> 
> 
[14:50:47.776] Showing password prompt
[14:51:27.550] Password dialog canceled
[14:51:27.551] "install" terminal command canceled
[14:51:27.553] > Acquiring lock on /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/vscode-remote-lock.oper.3156f1fb
> fcbb7bdd5f7aa24b4cde71526d1980c8
[14:51:27.554] > Installing to /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8...
[14:51:27.555] > d4d805dfa19d%%1%%
[14:51:27.558] > Downloading with wget
[14:51:27.559] > oper@127.0.0.1's password:
> d4d805dfa19d: running
> Acquiring lock on /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/vscode-remote-lock.oper.3156f1fb
> fcbb7bdd5f7aa24b4cde71526d1980c8
> Installing to /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8...
> d4d805dfa19d%%1%%
> Downloading with wget
> 
> 
> 
[14:51:27.561] > oper@127.0.0.1's password:
> d4d805dfa19d: running
> Acquiring lock on /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/vscode-remote-lock.oper.3156f1fb
> fcbb7bdd5f7aa24b4cde71526d1980c8
> Installing to /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8...
> d4d805dfa19d%%1%%
> Downloading with wget
> 
> 
> 
[14:51:27.562] > oper@127.0.0.1's password:
> d4d805dfa19d: running
> Acquiring lock on /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/vscode-remote-lock.oper.3156f1fb
> fcbb7bdd5f7aa24b4cde71526d1980c8
> Installing to /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8...
> d4d805dfa19d%%1%%
> Downloading with wget
> 
> 
> 
[14:51:27.564] > Download complete
[14:51:27.565] > d4d805dfa19d%%2%%
> tar --version:   
[14:51:27.567] > tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[14:51:27.570] > SHELL=/bin/bash
> LANGUAGE=en_CA:en
> PWD=/home/oper
> LOGNAME=oper
> XDG_SESSION_TYPE=tty
> HOME=/home/oper
> LANG=en_CA.UTF-8
> VSCODE_AGENT_FOLDER=/home/oper/.vscode-server-insiders
> SSH_CONNECTION=10.0.2.2 54506 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=oper
> SHLVL=1
> XDG_SESSION_ID=1
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=10.0.2.2 54506 22
[14:51:27.572] > 
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> MAIL=/var/mail/oper
[14:51:27.573] > 
> _=/usr/bin/printenv
> OLDPWD=/home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
> Starting server with command... /home/oper/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/server.sh --host=1
[14:51:27.574] > 
> 27.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/oper/.vscode-server-insiders/.3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8.
> log" < /dev/null
[14:51:27.576] > 
[14:51:27.577] > Waiting for server log...
[14:51:27.578] > Waiting for server log...
[14:51:27.580] > Waiting for server log...
[14:51:27.581] > Waiting for server log...
[14:51:27.582] > Waiting for server log...
[14:51:27.584] > *
> * Reminder: You may only use this software with Visual Studio family products,
[14:51:27.585] > 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[14:51:27.586] > 
[14:51:27.588] > Server did not start successfully. Full server log at /home/oper/.vscode-server-insiders/.3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
> .log >>>
[14:51:27.589] > buffer.js:585
>     slice: (buf, start, end) => buf.utf8Slice(start, end),
>                                     ^
> 
> RangeError: Index out of range
>     at Object.slice (buffer.js:585:37)
>     at Buffer.toString (buffer.js:782:14)
>     at Object.readFileSync (fs.js:386:41)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:990:22)
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
[14:51:27.591] > 
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
>     at internal/main/run_main_module.js:17:11 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> <<< End of server log
> d4d805dfa19d##32##
[14:51:27.592] > 
```

Log file on remote:
```
buffer.js:585
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:585:37)
    at Buffer.toString (buffer.js:782:14)
    at Object.readFileSync (fs.js:386:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:990:22)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by m5ls7h** [comment]
With respect to the timeout, the timeout period still remains at 4 sec (still 5 messages "Waiting for server log...") with the latest version
```text
Version: 1.50.0-insider (user setup)
Commit: 3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
Date: 2020-09-17T17:22:44.035Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134
```
vscode output
```text
[09:33:12.413] Log Level: 2
[09:33:12.423] remote-ssh@0.55.0
[09:33:12.424] win32 x64
[09:33:12.425] SSH Resolver called for "ssh-remote+ubuntu-qemu", attempt 1
[09:33:12.425] SSH Resolver called for host: ubuntu-qemu
[09:33:12.425] Setting up SSH remote "ubuntu-qemu"
[09:33:12.488] Using commit id "3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8" and quality "insider" for server
[09:33:12.489] Install and start server if needed
[09:33:12.493] Checking ssh with "ssh -V"
[09:33:12.607] > OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

[09:33:12.610] Running script with connection command: ssh -T -D 27690 ubuntu-qemu bash
[09:33:12.620] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:33:12.794] > 
[09:33:12.795] Got some output, clearing connection timeout
[09:33:13.320] > Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts
> .
> 
[09:33:14.098] > Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts.
> 
> 
[09:33:21.295] > 5d437281cbc3: running
> 
[09:33:22.110] > Acquiring lock on /home/ubuntu/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/vscode-remote-lock.ubuntu.3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
> 
[09:33:22.237] > Installing to /home/ubuntu/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8...
> 5d437281cbc3%%1%%
[09:33:22.259] > 
> 
[09:33:22.320] > Downloading with wget
> 
[09:33:26.942] > Download complete
> 5d437281cbc3%%2%%
> tar --version:
> 
[09:33:27.012] > tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> 
[09:33:31.354] > SHELL=/bin/bash
> PWD=/home/ubuntu
> LOGNAME=ubuntu
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/home/ubuntu
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server-insiders
> SSH_CONNECTION=157.163.215.170 43614 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=ubuntu
> SHLVL=1
> XDG_SESSION_ID=4
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=157.163.215.170 43614 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> _=/usr/bin/printenv
> OLDPWD=/home/ubuntu/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
> 
[09:33:31.408] > Starting server with command... /home/ubuntu/.vscode-server-insiders/bin/3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server-insid
> ers/.3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8.log" < /dev/null
> 
[09:33:31.543] > Waiting for server log...
> 
[09:33:32.260] > Waiting for server log...
> 
[09:33:32.979] > Waiting for server log...
> 
[09:33:33.732] > Waiting for server log...
> 
[09:33:34.472] > Waiting for server log...
> 
[09:33:35.044] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[09:33:35.348] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-server-insiders/.3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8.log >>>
> 
[09:33:35.406] > 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> <<< End of server log
> 5d437281cbc3##32##
> 
[09:33:35.406] Received install output: 5d437281cbc3##32##
[09:33:35.412] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\sm3141\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[09:33:35.416] ------
[09:33:36.115] "install" terminal command done
[09:33:36.115] Install terminal quit with output: 
```
So the behavior is unchanged: Timeout on first connect, successful connection on second attempt.

**Comment by roblourens** [comment]
@m5ls7h my change is in the nightly version of the extension, it looks like you are still on the stable version. You'll have to uninstall the stable version.

**Comment by m5ls7h** [comment]
@roblourens Sorry, I was not aware that vscode insiders does not use the nightly version of the SSH extension.
Using Remote-SSH (Nightly) v2020.9.23940 the connection can now be established without timeout.
Thank you for your great support.
```text
Warning: Permanently added '[127.0.0.1]:5001' (ECDSA) to the list of known hosts.
ubuntu@127.0.0.1's password:
ff215e6458c4: running
Acquiring lock on /home/ubuntu/.vscode-server-insiders/bin/e6a742d2407c4a94c6540b49aa5f801468dbd1c8/vscode-remote-lock.ubuntu.e6a742d2407c4a94c6540b49aa5f801468dbd1c8
Installing to /home/ubuntu/.vscode-server-insiders/bin/e6a742d2407c4a94c6540b49aa5f801468dbd1c8...
ff215e6458c4%%1%%
Downloading with wget
Download complete
ff215e6458c4%%2%%
tar --version:
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
SHELL=/bin/bash
PWD=/home/ubuntu
LOGNAME=ubuntu
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/ubuntu
LANG=C.UTF-8
VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server-insiders
SSH_CONNECTION=157.163.215.170 53728 10.0.2.15 22
XDG_SESSION_CLASS=user
USER=ubuntu
SHLVL=1
XDG_SESSION_ID=7
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=157.163.215.170 53728 22
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
_=/usr/bin/printenv
OLDPWD=/home/ubuntu/.vscode-server-insiders/bin/e6a742d2407c4a94c6540b49aa5f801468dbd1c8
Starting server with command... /home/ubuntu/.vscode-server-insiders/bin/e6a742d2407c4a94c6540b49aa5f801468dbd1c8/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/ubuntu/.vscode-server-insiders/.e6a742d2407c4a94c6540b49aa5f801468dbd1c8.log" < /dev/null
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...

*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

ff215e6458c4: start
sshAuthSock====
listeningOn==46629==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==
ff215e6458c4: end
```

**Comment by roblourens** [comment]
Thanks for verifying!
