### ISSUE TITLE
file name (tool tip) uses backslashes for file path

### ISSUE THREAD

**Issue by uishon** [microsoft/vscode-remote-release#460]
Issue Type: <b>Bug</b>

Open a remote file (via SSH)
Both on the sidebar (under "OPEN EDITORS") as well in the file name tab tooltips (move the cursor to the respective file tab header and see) - file name is displayed with backslashes instead of UNIX forward slash.

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9, 2019-05-27T05:19:20.616Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.88GB (0.85GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm-uri-ubuntu|
|OS|Linux x64 4.15.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (2 x 2591)|
|Memory (System)|9.61GB (1.67GB free)|
|VM|0%|
</details>
.

**Comment by uishon** [comment]
Just noted this only happens for file vscode "remembers" from my previous session. Files I open just now are displayed with forward slash as expected. FYI.

**Comment by isidorn** [comment]
This should be fixed via https://github.com/microsoft/vscode/commit/4486388383b561083f4e2d47c4cfbac3e94c506a

**Comment by mjbvz** [comment]
I'm still seeing this issue

![Screen Shot 2019-05-30 at 1 27 00 PM](https://user-images.githubusercontent.com/12821956/58662261-a0954b00-82de-11e9-92e7-0516efee007b.png)

**Comment by isidorn** [comment]
Dup of 1513
