### ISSUE TITLE
Preview in Editor directs to remote address when statically forwarded with custom local address

### ISSUE THREAD

**Issue by halflight0** [microsoft/vscode-remote-release#4920]
**Reproducible steps**

**1.** Host an HTTP server in the remote with address `192.168.200.7:8081`

**2.** To create a static forward with a local address other than localhost, add `LocalForward 127.0.1.1:8080 192.168.200.7:8081` to SSH config of the target remote

**3.** Connect to the remote

**4.** Click on `Preview in Editor`

**Expected behaviors vs. actual behaviors**

`127.0.1.1:8080` is expected to be opened in the editor.

However, the remote address, `192.168.200.7:8081`, is opened. Furthermore, instead of the editor, it is opened in the external browser

**Gif Demonstration**

![openineditor](https://user-images.githubusercontent.com/26127286/115529851-d6be8800-a2c5-11eb-943c-6d2eb65be106.gif)

**Used SSH config**

```
Host aremotehost
    HostName hostname
    Port 22
    User user
    IdentityFile ~/.ssh/ident
    LocalForward 127.0.1.1:8080 192.168.200.7:8081
```

<details><summary>Additional Env Information</summary><p>

**Version of VS Code:**

```
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Type of remote connection:** SSH

**OS:** Windows 10 Pro N Version 20H2 (OS Build 10.0.19042.867)

**Remote OS:** Deepin 20.1

**Extensions installed on remote:**

```
2gua.rainbow-brackets
alefragnani.Bookmarks
bierner.github-markdown-preview
bierner.markdown-checkbox
bierner.markdown-emoji
bierner.markdown-preview-github-styles
bierner.markdown-yaml-preamble
donjayamanne.githistory
eamodio.gitlens
GabrielBB.vscode-lombok
golang.go
haskell.haskell
James-Yu.latex-workshop
jcanero.hoogle-vscode
justusadam.language-haskell
KnisterPeter.vscode-github
mads-hartmann.bash-ide-vscode
ms-python.anaconda-extension-pack
ms-python.python
ms-toolsai.jupyter
ms-vscode.cpptools
redhat.java
redhat.vscode-yaml
shengchen.vscode-checkstyle
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
yaozheng.vscode-pde
zxh404.vscode-proto3
```

</p></details>

**Comment by alexr00** [comment]
This issue has already been fixed in VS Code insiders. You can install the insiders build to get the fix now, or you can wait until the 1.56 release.

**Comment by halflight0** [comment]
Thanks for your quick reply, but I'm sorry to say that I'm still seeing the same issue in the latest VS Code Insiders.

See picture below for the reference:

![openineditor2](https://user-images.githubusercontent.com/26127286/115809341-7e4ece00-a41e-11eb-8af7-1ae76325d3f0.gif)

**Version of VS Code Insiders:**

```
Version: 1.56.0-insider (user setup)
Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
Date: 2021-04-22T05:13:14.711Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by alexr00** [comment]
@halflight0 thanks for the gifs! A few things are happening:
- Preview in Editor only supports localhost and all interfaces, so since the local address is 127.0.1.1, it won't open in the preview editor. I read your original issue too quickly the first time and didn't notice that this wasn't localhost. 
- The fallback is then to open in the browser. However, looks like there's a bug here and I'm using the wrong address. I will push a fix for this.

**Comment by halflight0** [comment]
Wow, that fix is amazingly fast.

Now that the wrong address bug is settled, I'm still unsure about the first point you've made. Is it actually by design that Preview in Editor only supports localhost and all interfaces? In my case, there are a lot of remote machines that need to be mapped into the same port. Thus using forwards with local addresses like 127.0.1.1 and 127.0.1.2 becomes essential.

I'm curious as to why this is the case/if it is possible to make Preview in Editor support custom addresses?

**Comment by alexr00** [comment]
@mjbvz can you answer the questions about why the simple browser doesn't want to support anything other than localhost and all interfaces?

**Comment by halflight0** [comment]
As a continuation of my exploration, I've just examined the accessibility of "all interfaces" you've mentioned. It seems none of the IPs of my physical or virtual interfaces(`100.66.16.82`, and `10.147.17.41`) nor `0.0.0.0` is accepted by the simple browser.

I've checked out the code of the simple browser, [enabledHosts](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/simple-browser/src/extension.ts#L17-L20) does only contains `127.0.0.1` and `localhost`, which is referenced by [canOpenExternalUri](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/simple-browser/src/extension.ts#L49-L59). When you enter a custom IP in the simple browser's address bar, it bypasses the check, thus making custom IPs work with the simple browser. This check logic doesn't look intuitive to me.

Furthermore, Open in Browser tries to open `0.0.0.0:8080` in the external browser, which apparently points to nothing. Personally, I think when forwarding with local address `0.0.0.0`, we may simply choose `localhost` as the URI to be opened.



Code of `enabledHosts`

```typescript
const enabledHosts = new Set<string>([
	'localhost',
	'127.0.0.1'
]);
```

Code of `canOpenExternalUri`

```typescript
context.subscriptions.push(vscode.window.registerExternalUriOpener(openerId, {
	canOpenExternalUri(uri: vscode.Uri) {
		const originalUri = new URL(uri.toString());
		if (enabledHosts.has(originalUri.hostname)) {
			return isWeb()
				? vscode.ExternalUriOpenerPriority.Default
				: vscode.ExternalUriOpenerPriority.Option;
		}

		return vscode.ExternalUriOpenerPriority.None;
	},
```

**Comment by alexr00** [comment]
I updated `enabledHosts` recently, so in our insiders build (and in the next stable release) 0.0.0.0 is supported: 

https://github.com/Microsoft/vscode/blob/2437313ca469a2ca27bb53f598e8a662913bb1cc/extensions/simple-browser/src/extension.ts#L17-L29

**Comment by mjbvz** [comment]
`enabledHosts` only tracks the host the simple browser want to participate in opened for. It it not meant to block other hosts from being loaded, either because of a user setting or because an extension explicitly requested the simple browser be used.

You can see behavior by setting:

```ts
"workbench.externalUriOpeners": {
  "*": "simpleBrowser.open"
}
```

**Comment by halflight0** [comment]
That's fantastic! It's working like a charm. Thanks guys, this is a tremendous help.
