### ISSUE TITLE
Container opened from Remote-SSH not stopping after closing the window

### ISSUE THREAD

**Issue by Uguudei** [microsoft/vscode-remote-release#6056]
Dev containers that reopened from the Remote-SSH extension are kept running after closing the window. It should be stopped as how opening a container in cloned volume does.

I have even tried setting `"shutdownAction": "stopContainer" ` in devcontainer.json, however, it didn't help.

- VSCode Version: 1.63.0
- Local OS Version: Windows 10 Build 18363
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: Remote - SSH v0.68.0; Remote - Container v0.209.5
- Remote Docker Version: 20.10.11, build dea9396
- Docker Extension Version: v1.18.0
- Logs: Not sure where to get logs after closing the VS Code.

Steps to Reproduce:

1. Open repo on Remote host SSH
2. Reopen in Containers
3. Successful opens/builds containers
4. Close VS Code window.

**Comment by felipecrs** [comment]
I can also confirm this issue. It happens with both Dockerfile and docker-compose (when using `shutdownAction: stopCompose`.

**Comment by ventor-dev** [comment]
Is there any workaround before a fix will be available?

**Comment by leohxj** [comment]
Now I manual stop container as workaround. it maybe not urgent.

**Comment by AlexanderPashuk** [comment]
Is there any workaround before a fix will be available?

**Comment by armaanPy** [comment]
@chrmarti Is there any ETA on this fix?

**Comment by cyangle** [comment]
I have been using my workaround for quite a while.

https://github.com/microsoft/vscode-remote-release/issues/3512#issuecomment-991473473

**Comment by SmallhillCZ** [comment]
> I have been using my workaround for quite a while.
> 
> [#3512 (comment)](https://github.com/microsoft/vscode-remote-release/issues/3512#issuecomment-991473473)

But this stops only the main container, not other containers from docker compose, right?

**Comment by SmallhillCZ** [comment]
And yes, the issue is still there in 2023…

**Comment by SmallhillCZ** [comment]
This issue should be solved with https://github.com/microsoft/vscode-remote-release/issues/7754

**Comment by jahed** [comment]
> This issue should be solved with #7754

Doesn't look like it. I'm still encountering this issue on VS Code v1.78.2, Dev Containers v0.292.0, Remote SSH v0.102.0.

**Comment by SmallhillCZ** [comment]
Try the pre-release version (v0.294.0), it works for me okay. Also you have to wait like 10 seconds before the containers get stopped.

**Comment by jahed** [comment]
> Try the pre-release version (v0.294.0), it works for me okay. Also you have to wait like 10 seconds before the containers get stopped.

Tried that, no change. It's possible the fix you're referring to only fixed it for `stopCompose` and not for `stopContainer`. It's difficult to know since #7754 doesn't have a PR linked to it.

**Comment by SmallhillCZ** [comment]
Maybe 🤷‍♀️

**Comment by thebhef** [comment]
I think I'm seeing this issue or a related one. I have two containers running with docker-compose and everything is basically working as desired, except for the `docker-compose stop`.

OS: Win11 23H2 22621.2283
VSCode: 1.82.2
Devcontainer: 0.309.0
Docker Desktop version: 4.23.0
Docker: 24.0.6
Docker-compose: 2.21.0-desktop.1
WSL version: 1.2.5.0
WSL OS: Ubuntu 20.04.5

I can see in the log that the stop is attempted, but it fails and I can't get it to tell me why.

```
[2023-09-29T16:53:38.768Z] Cleaning up after 23186 ms...
[2023-09-29T16:53:38.768Z] Delaying for 10000 ms.
[2023-09-29T16:53:48.781Z] Start: Run in container: /bin/sh
[2023-09-29T16:53:48.809Z] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2023-09-29T16:53:48.986Z] Stop (177 ms): Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2023-09-29T16:53:48.988Z] Start: Run: docker-compose --project-name devcontainer -f /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/5733c52769e8a47bdf73664b055191686ccbcda35160d7f4bae7ebab630bf052/devcontainer/docker-compose.yml stop -t 0
[2023-09-29T16:53:49.048Z] Stop (60 ms): Run: docker-compose --project-name devcontainer -f /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/5733c52769e8a47bdf73664b055191686ccbcda35160d7f4bae7ebab630bf052/devcontainer/docker-compose.yml stop -t 0
[2023-09-29T16:53:49.048Z] Unexpected error: Command failed: docker-compose --project-name devcontainer -f /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/5733c52769e8a47bdf73664b055191686ccbcda35160d7f4bae7ebab630bf052/devcontainer/docker-compose.yml stop -t 0
[2023-09-29T16:56:26.248Z] Stop (157467 ms): Run in container: /bin/sh
```

The command is successful with no changes when I copy it from this log and execute it in WSL myself, and sudo is not required. I have `dev.containers.executeInWSL=true`

I've tried turning up the logging level to trace to see if I could get the output of the failing docker-compose command but the 'unexpected error' line hasn't changed.

**Comment by themw123** [comment]
I am getting following error with f1 of Dev Containers Developer: Show Alll Logs

 Unexpected error: Error: Exectuable 'docker' not found on PATH '.....'
at cs (c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:29:1355)
    at async c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:30:550
    at async Mt (c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:23:3480)
    at async Zg (c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:30:3446)
    at async rw (c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:30:6189)
    at async c:\Users\Marvin\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\shutdown\shutdownMonitorProcess.js:30:5424

I am using devcontainers with a remote connection to my linux server.

**Comment by GlacierFox** [comment]
Getting this same problem also with "shutdownAction": "stopContainer". I'm having to manually stop hanging containers after a while before my system gets choked up.

**Comment by JtMotoX** [comment]
Here is a workaround I have come up with. It is less than ideal but it has been almost 3 years that this issue has been open and still no word on a fix.

.devcontainer
```json
{
	...
	"postCreateCommand": "while true; do sleep 20; ps aux | grep -E 'vscode.*[b]ootstrap-fork.*extensionHost.*' > /dev/null || kill -15 1; done",
	"runArgs": [
		"--rm"
	]
	...
}
```

This particular dev container does not have a Dockerfile.  If you have a Dockerfile, you can probably refer to https://github.com/microsoft/vscode-remote-release/issues/3512#issuecomment-2131354971

**Comment by JWWolstenholme** [comment]
> Here is a workaround I have come up with. It is less than ideal but it has been almost 3 years that this issue has been open and still no word on a fix.
> 
> .devcontainer
> 
> {
> 	...
> 	"postCreateCommand": "while true; do sleep 20; ps aux | grep -E 'vscode.*[b]ootstrap-fork.*extensionHost.*' > /dev/null || kill -15 1; done",
> 	"runArgs": [
> 		"--rm"
> 	]
> 	...
> }
> This particular dev container does not have a Dockerfile. If you have a Dockerfile, you can probably refer to [#3512 (comment)](https://github.com/microsoft/vscode-remote-release/issues/3512#issuecomment-2131354971)

Thanks for this workaround! I found that vscode would continue to report that it was in the process of configuring the container when I included this, so I've edited it slightly to run in the background instead (as per [these docs](https://code.visualstudio.com/remote/advancedcontainers/start-processes#_video-run-npm-install-when-a-container-is-created)).

When starting the container, it still leaves you on the terminal where this command was run instead of a fresh CLI, requiring you to press any key to dismiss it, which is a little annoying (you could start bash automatically from within `postAttachCommand` but that also leaves vscode "configuring").

```json
{
	...
	"postCreateCommand": "nohup bash -c 'while true; do sleep 20; ps aux | grep -E 'vscode.*[b]ootstrap-fork.*extensionHost.*' > /dev/null || kill -15 1; done &' > /dev/null",
	"runArgs": [
		"--rm"
	]
	...
}
```
