### ISSUE TITLE
VS Code Remote session gives error

### ISSUE THREAD

**Issue by preethamrajk** [microsoft/vscode-remote-release#6450]
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

- VSCode Version: Details above 
- Local OS Version: Windows
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: SSH
- Logs: [startup.log](https://github.com/microsoft/vscode-remote-release/files/8248940/startup.log)

Background:
VMs in our org can only be accessed via PAM - a solution which can allow secured access into Azure resources using MFA based authentication with AAD. When authenticating into this VM via ssh, it works fine. But when accessing it via VSCode Remote, it is returning the issue as seen in the logs - I am unable to see what script it is trying to run on startup that is causing this issue.

Steps to Reproduce:

1. Using SSH connection in VSCode, login to the Azure VM remotely.
2. When asked for MFA authentication, authenticate using your preferred mechanism. (Authenticator etc)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/16648593/158274933-45152e31-860c-43f6-9cce-b9e125d00103.png)

**Comment by roblourens** [comment]
Can you try switching to the "pre-release" version of the extension, (right click on the extension in the extensions view) and let me know whether that fixes it? This may be an issue that was just fixed.

**Comment by preethamrajk** [comment]
Hi @roblourens,

This is still an issue in the pre-release version of the extension.

**Comment by roblourens** [comment]
Ok, then the error message confuses me. Can you try setting `"remote.SSH.useLocalServer": true`?

**Comment by preethamrajk** [comment]
Tried with the setting. Same issue.

**Comment by ayangd** [comment]
Same here. Tried remote-ssh to my raspberry pi, but failed. Same commit.

On remote ssh:

    wget download failed
    failed: Connection timed out.

On local:

    Resolver error: Error: XHR failed

Seems like I either cannot reach the server or the server gives error.

**Comment by tanhakabir** [comment]
@preethamrajk could you please share your logs that you see see from using the pre-release version of the extension?

**Comment by preethamrajk** [comment]
[startup.log](https://github.com/microsoft/vscode-remote-release/files/8274871/startup.log)
@tanhakabir Please find attached.

There doesn't appear to be any difference in the two logs (pre-release+vscode insiders) or (release+vscode GA)..

**Comment by tanhakabir** [comment]
Sorry with `useLocalServer` set to `true` as well

**Comment by preethamrajk** [comment]
[startup.log](https://github.com/microsoft/vscode-remote-release/files/8274902/startup.log)
Here!

**Comment by tanhakabir** [comment]
Hm do you have any proxies involved? Are you using a jump server?

Could you share what your SSH Config looks like?

**Comment by preethamrajk** [comment]
``` Host eebsandbox
    User pkancher@mappsebrpa02%lpidv01@ldeebsandboxdevvm.azr
    Port 22
    HostName [redacted]
    IdentityFile "C:\Users\pkancher\.ssh\id_rsa-remote-ssh"
    LogLevel INFO 
```
Yes we are behind a proxy. The proxy is set in an environment variable.

**Comment by preethamrajk** [comment]
Any findings @tanhakabir?

**Comment by tanhakabir** [comment]
Hm could you explain in more detail about your proxy setup? Something in the way it's set up is preventing us from successfully installing the VS Code server on your remote.

I see in the `useLocalServer: false` case that only a portion of the installation script is passed in so it's complaining about an incomplete script.

In the `useLocalServer: true` case none of the script seems to be passed in at all.

Also what is the default shell of your remote?

**Comment by preethamrajk** [comment]
I don't believe the VM has access to the internet. Security in the org, doesn't allow for that - at least not in normal scenarios.

So the `useLocalServer: true` is the right way of doing it. Also, I have tried downloading the server locally for that commit and `scp`ed it to the remote in the `/home/mappsebrpa02/.vscode-server/bin` folder. No luck.

My default shell in remote is bash (/bin/bash).

Proxy is setup using ZScaler as follows. 
This is from the documentation we have internally.
![image](https://user-images.githubusercontent.com/16648593/159378261-efc38e19-b135-438c-b2b5-d5673d150c92.png)

My host proxy settings:
![image](https://user-images.githubusercontent.com/16648593/159377775-9940f132-812d-460e-a509-3d4dcd68637b.png)

**Comment by tanhakabir** [comment]
Hm I'm sorry it still doesn't make sense to me why you see that your remote isn't able to receive a piped in install script. Do you have any idea of anything unusual in your end to end setup that would cause us issues piping scripts to your remote?

Otherwise I don't have any idea why you're seeing this issue :/
