### ISSUE TITLE
source control for remote ssh keep displaying a message "The folder currently open doesn't have a git repository"

### ISSUE THREAD

**Issue by AmirHussain93** [microsoft/vscode-remote-release#6637]
I am using the latest version of vs code **1.66.2**, which I have updated a week back. Everything was working fine until last Friday.

I am using remote ssh to connect to my host ubuntu machine.  Source control is displaying a message "The folder currently open doesn't have a git repository. You can initialise a repository........ "

The folders which I have open are already git initialised. 

Also If i am using vs code inside my Virtual machine than I am not facing this issue. 

Could you please look into this ?

**Comment by bamurtaugh** [comment]
Do you see anything in the Git output channel (command `Git: Show Git Output`)?

**Comment by AmirHussain93** [comment]
@bamurtaugh please see the screenshot below 

<img width="1421" alt="Screenshot 2022-04-26 at 10 53 11 AM" src="https://user-images.githubusercontent.com/27803197/165227488-050e741e-1f61-4292-80d6-c3a2b369110e.png">

**Comment by bamurtaugh** [comment]
cc @lszomoru

**Comment by lszomoru** [comment]
@AmirHussain93, thank you very much for the information that you have shared.

> Also If i am using vs code inside my Virtual machine than I am not facing this issue.

Could you please elaborate on this? Do you mean that if you use remote desktop to login to the machine, and you start VS Code on the machine then everything is working as expected? So the issue can only be reproduced when you are using the SSH extension to access the machine?

**Comment by andrey18106** [comment]
Facing the same issue using WSL Ubuntu (with all the latest updates). Is there any solution or workaround?

**Comment by vishalovercome** [comment]
Facing the same issue when accessing repo either with remote ssh (host level) as well as inside devcontainer (container level). Remote host and container host OS are both Ubuntu 20.04. 

Remote - SSH - v0.78.0
Remote - Containers - v0.231.6 (or v0.233.0)

**Comment by AmirHussain93** [comment]
> 1:2.25.1-1ubuntu3

Hi @lszomoru Yes this issue can only be reproduced when you are using the SSH extension to access the machine.

I have confirmed this issue with other colleagues in my team as well.

**Comment by AmirHussain93** [comment]
> @AmirHussain93, thank you very much for the information that you have shared.
> 
> > Also If i am using vs code inside my Virtual machine than I am not facing this issue.
> 
> Could you please elaborate on this? Do you mean that if you use remote desktop to login to the machine, and you start VS Code on the machine then everything is working as expected? So the issue can only be reproduced when you are using the SSH extension to access the machine?

Hi @lszomoru
Yes this issue can only be reproduced when you are using the SSH extension to access the machine.

I have confirmed this issue with other colleagues in my team as well.

**Comment by AmirHussain93** [comment]
I followed @andrey18106 approach by changing git version from 1:2.25.1-1ubuntu3.4 (focal-updates) to 1:2.25.1-1ubuntu3 (focal) in my remote machine. Issue is resolved but only if I am **opening single folder.**

If I am opening **single folder** I am able to see the source control changes but If I am opening **multiple folders** than I source control changes are not available.

Any update on this @lszomoru @bamurtaugh ?

**Comment by andrey18106** [comment]
@AmirHussain93 You can try also another workaround, that was mentioned in other related issues: `git config --global --add safe.directory '*'`, or only for concrete directory `git config --global --add safe.directory /path/to/repo`. Also, pay attention from which user VS Code remote server is working on - for that user you should configure `safe.directory`.

For me, it works on WSL Ubuntu 22.04 with the latest git 2.34.1.

**Comment by lszomoru** [comment]
@AmirHussain93, apologies for not getting back to you on this. In case you are still experiencing the issue, can you please enable `trace` logging as described in [this wiki](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting), open the repository in question, and then share the contents of [the git output channel](https://code.visualstudio.com/docs/editor/versioncontrol#_git-output-window). Thanks!
