### ISSUE TITLE
The workbench failed to connect to the server

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#7046]
When launching the VS Code Server from an Ubuntu 20.04 WSL distro, I get the following when I open the vscode.dev link:

![image](https://user-images.githubusercontent.com/25310137/183982058-f3814de0-e827-4db2-862e-1090b08256fd.png)

`The workbench failed to connect to the server (Error: Could not successfully authenticate into account that has access to sleepy-penguin:31545. Please make sure you are logged into the correct account. You can reload and try again.)`.

This was working as of yesterday. I checked for updates but don't seem to have any.

**Comment by bamurtaugh** [comment]
I just tried launching the server in Windows, and I received the same error:

![image](https://user-images.githubusercontent.com/25310137/183983194-08ac1500-9ec0-4345-a46f-2fccd5aeeb1d.png)

**Comment by nukdcbear** [comment]
I am also getting this error in an existing install on an EC2 instance and on a clean install.

**Comment by tanhakabir** [comment]
Will have a fix for this out soon.

**Comment by bamurtaugh** [comment]
This should now be fixed (thanks @tanhakabir!), and it works on my end. Please let me know if that isn't the case for others!

**Comment by nukdcbear** [comment]
It is working for me now. Thanks

**Comment by Co1lin** [comment]
@bamurtaugh Hi! I still encountered this issue today on a `Ubuntu 20.04.1 LTS` server. Here's the log.

```shell
$ code-server --verbose
[2022-08-12 20:42:20] debug Server args: CodeServerArgs { host: None, port: None, socket_path: None, telemetry_level: None, log: None, accept_server_license_terms: true, verbose: true, install_extensions: [], uninstall_extensions: [], list_extensions: false, show_versions: false, category: None, pre_release: false, force: false, start_server: false, connection_token: None, connection_token_file: None, without_connection_token: false }
[2022-08-12 20:42:20] trace Found token in keyring
[2022-08-12 20:42:21] debug Starting tunnel with command... basis ["host", "vmdr90r0"]
[2022-08-12 20:42:22] trace [basis.0] HTTP: GET https://global.rel.tunnels.api.visualstudio.com/api/v1/tunnels/vmdr90r0?includePorts=true&tokenScopes=host,connect
[2022-08-12 20:42:22] trace [basis.0] HTTP: Authorization: Tunnel <tunnel=vmdr90r0.asse, scopes=[host], issuer=https://tunnels.api.visualstudio.com/, expiration=2022-08-13T12:42:21Z (23:59:59 remaining)>
[2022-08-12 20:42:22] trace [basis.0] HTTP: User-Agent: vscode-server-launcher/20220810.1
[2022-08-12 20:42:22] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-CLI/1.0.170+708de6c4e9
[2022-08-12 20:42:22] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-SDK/1.0.7287+ded92acf20
[2022-08-12 20:42:23] trace [basis.0] HTTP: 200 OK (778 ms)
[2022-08-12 20:42:23] trace [basis.0] HTTP: Date: Fri, 12 Aug 2022 12:42:23 GMT
[2022-08-12 20:42:23] trace [basis.0] HTTP: Transfer-Encoding: chunked
[2022-08-12 20:42:23] trace [basis.0] HTTP: Connection: keep-alive
[2022-08-12 20:42:23] trace [basis.0] HTTP: X-Content-Type-Options: nosniff
[2022-08-12 20:42:23] trace [basis.0] HTTP: RateLimit-Limit: ApiQueryRatePerIPAddress:40/s
[2022-08-12 20:42:23] trace [basis.0] HTTP: RateLimit-Remaining: ApiQueryRatePerIPAddress:39
[2022-08-12 20:42:23] trace [basis.0] HTTP: RateLimit-Reset: ApiQueryRatePerIPAddress:1s
[2022-08-12 20:42:23] trace [basis.0] HTTP: VsSaaS-Request-Id: a6bdafc1-3a35-4cfc-9009-a7315c958b56
[2022-08-12 20:42:23] trace [basis.0] HTTP: Strict-Transport-Security: max-age=31536000; includeSubDomains
[2022-08-12 20:42:23] trace [basis.0] HTTP: X-Served-By: tunnels-prod-rel-asse-v3-cluster
[2022-08-12 20:42:23] trace [basis.0] HTTP: {
[2022-08-12 20:42:23] trace [basis.0]   "clusterId": "asse",
[2022-08-12 20:42:23] trace [basis.0]   "tunnelId": "vmdr90r0",
[2022-08-12 20:42:23] trace [basis.0]   "name": "",
[2022-08-12 20:42:23] trace [basis.0]   "description": "",
[2022-08-12 20:42:23] trace [basis.0]   "tags": [
[2022-08-12 20:42:23] trace [basis.0]     "aliyun-hk",
[2022-08-12 20:42:23] trace [basis.0]     "vscode-server-launcher"
[2022-08-12 20:42:23] trace [basis.0]   ],
[2022-08-12 20:42:23] trace [basis.0]   "accessTokens": {},
[2022-08-12 20:42:23] trace [basis.0]   "options": {},
[2022-08-12 20:42:23] trace [basis.0]   "status": {
[2022-08-12 20:42:23] trace [basis.0]     "hostConnectionCount": 0,
[2022-08-12 20:42:23] trace [basis.0]     "lastHostConnectionTime": "2022-08-12T12:42:02Z"
[2022-08-12 20:42:23] trace [basis.0]   },
[2022-08-12 20:42:23] trace [basis.0]   "endpoints": [
[2022-08-12 20:42:23] trace [basis.0]     {
[2022-08-12 20:42:23] trace [basis.0]       "hostRelayUri": "wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/vmdr90r0",
[2022-08-12 20:42:23] trace [basis.0]       "clientRelayUri": "wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/vmdr90r0",
[2022-08-12 20:42:23] trace [basis.0]       "connectionMode": "TunnelRelay",
[2022-08-12 20:42:23] trace [basis.0]       "hostId": "4227250f-f41f-4501-ac1e-ef8bdc127c11",
[2022-08-12 20:42:23] trace [basis.0]       "hostPublicKeys": [
[2022-08-12 20:42:23] trace [basis.0]         "AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBEnQfeYqNYqdCkjo6pTAt0YCOypFBIG4+XetNV5KYodLX7eLVpBPDT3QglUgms/RqlclztGJ+QYXrv0QS85ysvZ1Rd27FKkY/bUkm+PvWwVu5Uae33Djmwfmp7gGit5aGw=="
[2022-08-12 20:42:23] trace [basis.0]       ],
[2022-08-12 20:42:23] trace [basis.0]       "portUriFormat": "https://vmdr90r0-{port}.asse.rel.tunnels.api.visualstudio.com/",
[2022-08-12 20:42:23] trace [basis.0]       "portSshCommandFormat": "ssh vmdr90r0-{port}@asse.rel.tunnels.api.visualstudio.com"
[2022-08-12 20:42:23] trace [basis.0]     }
[2022-08-12 20:42:23] trace [basis.0]   ],
[2022-08-12 20:42:23] trace [basis.0]   "ports": [
[2022-08-12 20:42:23] trace [basis.0]     {
[2022-08-12 20:42:23] trace [basis.0]       "clusterId": "asse",
[2022-08-12 20:42:23] trace [basis.0]       "tunnelId": "vmdr90r0",
[2022-08-12 20:42:23] trace [basis.0]       "portNumber": 31545,
[2022-08-12 20:42:23] trace [basis.0]       "protocol": "http",
[2022-08-12 20:42:23] trace [basis.0]       "options": {},
[2022-08-12 20:42:23] trace [basis.0]       "status": {}
[2022-08-12 20:42:23] trace [basis.0]     }
[2022-08-12 20:42:23] trace [basis.0]   ],
[2022-08-12 20:42:23] trace [basis.0]   "created": "2022-08-12T12:34:54.3929422Z"
[2022-08-12 20:42:23] trace [basis.0] }
[2022-08-12 20:42:23] trace [basis.0] HTTP: DELETE https://asse.rel.tunnels.api.visualstudio.com/api/v1/tunnels/vmdr90r0/endpoints/4227250f-f41f-4501-ac1e-ef8bdc127c11/TunnelRelay
[2022-08-12 20:42:23] trace [basis.0] HTTP: Authorization: Tunnel <tunnel=vmdr90r0.asse, scopes=[host], issuer=https://tunnels.api.visualstudio.com/, expiration=2022-08-13T12:42:21Z (23:59:58 remaining)>
[2022-08-12 20:42:23] trace [basis.0] HTTP: User-Agent: vscode-server-launcher/20220810.1
[2022-08-12 20:42:23] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-CLI/1.0.170+708de6c4e9
[2022-08-12 20:42:23] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-SDK/1.0.7287+ded92acf20
[2022-08-12 20:42:24] trace [basis.0] HTTP: 204 NoContent (171 ms)
[2022-08-12 20:42:24] trace [basis.0] HTTP: Date: Fri, 12 Aug 2022 12:42:24 GMT
[2022-08-12 20:42:24] trace [basis.0] HTTP: Connection: keep-alive
[2022-08-12 20:42:24] trace [basis.0] HTTP: X-Content-Type-Options: nosniff
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Limit: ApiQueryRatePerIPAddress:40/s
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Remaining: ApiQueryRatePerIPAddress:38
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Reset: ApiQueryRatePerIPAddress:1s
[2022-08-12 20:42:24] trace [basis.0] HTTP: VsSaaS-Request-Id: 52127539-fa21-4219-96bf-aa48438be0f1
[2022-08-12 20:42:24] trace [basis.0] HTTP: Strict-Transport-Security: max-age=31536000; includeSubDomains
[2022-08-12 20:42:24] trace [basis.0] HTTP: X-Served-By: tunnels-prod-rel-asse-v3-cluster
[2022-08-12 20:42:24] trace [basis.0] HTTP: PUT https://asse.rel.tunnels.api.visualstudio.com/api/v1/tunnels/vmdr90r0/endpoints/bbee2135-54fd-4793-96b3-2c2c5b978c42/TunnelRelay
[2022-08-12 20:42:24] trace [basis.0] HTTP: Authorization: Tunnel <tunnel=vmdr90r0.asse, scopes=[host], issuer=https://tunnels.api.visualstudio.com/, expiration=2022-08-13T12:42:21Z (23:59:57 remaining)>
[2022-08-12 20:42:24] trace [basis.0] HTTP: User-Agent: vscode-server-launcher/20220810.1
[2022-08-12 20:42:24] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-CLI/1.0.170+708de6c4e9
[2022-08-12 20:42:24] trace [basis.0] HTTP: User-Agent: Visual-Studio-Tunnel-Service-SDK/1.0.7287+ded92acf20
[2022-08-12 20:42:24] trace [basis.0] HTTP: {
[2022-08-12 20:42:24] trace [basis.0]   "connectionMode": "TunnelRelay",
[2022-08-12 20:42:24] trace [basis.0]   "hostId": "bbee2135-54fd-4793-96b3-2c2c5b978c42",
[2022-08-12 20:42:24] trace [basis.0]   "hostPublicKeys": [
[2022-08-12 20:42:24] trace [basis.0]     "AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBG516oOeAtFoVCLAGqTTJbc36iOCisWC0Q5c9YTEp7Vwm4lAiTrWhHrdTSr/RrUvCzZhz8AljTybMUkxGEDmgykuy34dVhhewByp7Jryf2Pq7IdlZST/F89oJqoGJ350Tg=="
[2022-08-12 20:42:24] trace [basis.0]   ]
[2022-08-12 20:42:24] trace [basis.0] }
[2022-08-12 20:42:24] trace [basis.0] HTTP: 200 OK (56 ms)
[2022-08-12 20:42:24] trace [basis.0] HTTP: Date: Fri, 12 Aug 2022 12:42:24 GMT
[2022-08-12 20:42:24] trace [basis.0] HTTP: Transfer-Encoding: chunked
[2022-08-12 20:42:24] trace [basis.0] HTTP: Connection: keep-alive
[2022-08-12 20:42:24] trace [basis.0] HTTP: X-Content-Type-Options: nosniff
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Limit: ApiQueryRatePerIPAddress:40/s
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Remaining: ApiQueryRatePerIPAddress:39
[2022-08-12 20:42:24] trace [basis.0] HTTP: RateLimit-Reset: ApiQueryRatePerIPAddress:1s
[2022-08-12 20:42:24] trace [basis.0] HTTP: VsSaaS-Request-Id: 72719c41-33b0-43c5-9afa-74c525a5c6f3
[2022-08-12 20:42:24] trace [basis.0] HTTP: Strict-Transport-Security: max-age=31536000; includeSubDomains
[2022-08-12 20:42:24] trace [basis.0] HTTP: X-Served-By: tunnels-prod-rel-asse-v3-cluster
[2022-08-12 20:42:24] trace [basis.0] HTTP: {
[2022-08-12 20:42:24] trace [basis.0]   "hostRelayUri": "wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/vmdr90r0",
[2022-08-12 20:42:24] trace [basis.0]   "clientRelayUri": "wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/vmdr90r0",
[2022-08-12 20:42:24] trace [basis.0]   "connectionMode": "TunnelRelay",
[2022-08-12 20:42:24] trace [basis.0]   "hostId": "bbee2135-54fd-4793-96b3-2c2c5b978c42",
[2022-08-12 20:42:24] trace [basis.0]   "hostPublicKeys": [
[2022-08-12 20:42:24] trace [basis.0]     "AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBG516oOeAtFoVCLAGqTTJbc36iOCisWC0Q5c9YTEp7Vwm4lAiTrWhHrdTSr/RrUvCzZhz8AljTybMUkxGEDmgykuy34dVhhewByp7Jryf2Pq7IdlZST/F89oJqoGJ350Tg=="
[2022-08-12 20:42:24] trace [basis.0]   ],
[2022-08-12 20:42:24] trace [basis.0]   "portUriFormat": "https://vmdr90r0-{port}.asse.rel.tunnels.api.visualstudio.com/",
[2022-08-12 20:42:24] trace [basis.0]   "portSshCommandFormat": "ssh vmdr90r0-{port}@asse.rel.tunnels.api.visualstudio.com"
[2022-08-12 20:42:24] trace [basis.0] }
[2022-08-12 20:42:24] trace [basis.0] Connecting to host tunnel relay wss://asse-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/vmdr90r0
[2022-08-12 20:42:24] trace [basis.0] HostSSH: SshSession:26458746 ConnectAsync
[2022-08-12 20:42:24] trace [basis.0] HostSSH: Local version: SSH-2.0-Microsoft.VisualStudio.Ssh_3.7, remote version: SSH-2.0-Microsoft.VisualStudio.Ssh_3.7
[2022-08-12 20:42:24] trace [basis.0] Hosting port 31545 at https://vmdr90r0-31545.asse.rel.tunnels.api.visualstudio.com/
[2022-08-12 20:42:24] trace [basis.0] Ready to accept connections for tunnel: vmdr90r0
[2022-08-12 20:42:24] debug VS Code Server is listening on 127.0.0.1:31545

Open this link in your browser https://insiders.vscode.dev/+ms-vscode.remote-server/aliyun-hk
```
