### ISSUE TITLE
DevContainer tries to Inspect docker-compose provided image before initializeCommand

### ISSUE THREAD

**Issue by yefetBenTili** [microsoft/vscode-remote-release#7651]
- VSCode Version: 1.73.1 
- Local OS Version: Issue Occurs across multiple OS (Ubuntu WSL/Mac ..)
- Remote OS Version: Issue Occurs across multiple remote OS  (Ubuntu WSL/Mac ..)

We currently have our set-up in a way that `.devcontainer\Dockerfile.dev` is built using a base image as an argument that we pre-build in the initializeCommand, 

    ├── .devcontainer
    │   ├── Dockerfile.dev     "
    │   ├── docker-compose.yml`
    ├──  project-app       
    │   ├── Dockerfile

first lines of `.devcontainer\Dockerfile.dev`:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE as stage-dev
```
Some snippet of `.devcontainer\docker-compose.yml` where we pass the base image argument:

```
version: "3.7"

services:
  project-devc:
    image: project-devc-img:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # base_image is built in devcontainer.json in the initializeCommand
        BASE_IMAGE: project-test-img:latest
        USERNAME: user_test
        USER_UID: 1000
    volumes:
      - ..:/workspace:rw
    ports:
      - "8888:8888"
```
And in the `.devcontainer\devcontainer.json` `initializeCommand` we cd to the folder of base image and build it:

  `  "initializeCommand": "cd project-app && docker build --platform=linux/amd64 --target project-test-env --tag project-test-img .",`

`project-app folder` contains a standard Dockerfile 

It used to work perfectly before, but lately we got the issue that for some reason DevContainer tries to inspect image provided in the docker-compose.yml before running the `initializeCommand` and complains that no such `project-test-img` exists

Error Logs:

```
[2679531 ms] Start: Run: docker inspect --type image project-test-img:latest
[2680610 ms] Error fetching image details: No manifest found for docker.io/library/project-test-img:latest.
[2680611 ms] Start: Run: docker pull project-test-img:latest
Error response from daemon: pull access denied for project-test-img, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[2694335 ms] []
[2694335 ms] Error: No such image: project-test-img:latest

[2694335 ms] Command failed: docker inspect --type image project-test-img:latest
[2694343 ms] Exit code 1
```
Current workaround: is to manually run the `initializeCommand `then start the DevContainer but that's not so nice

**Comment by chrmarti** [comment]
This should be fixed in recent versions (latest versions are 0.266.1 and 0.267.0-pre-release). Could you retry with those?

**Comment by yefetBenTili** [comment]
> This should be fixed in recent versions (latest versions are 0.266.1 and 0.267.0-pre-release). Could you retry with those?

@chrmarti Indeed

**Comment by PAbernet** [comment]
Still experiencing this on `v0.266.1` when using a remote host to build/run the container.

[remoteContainers-2022-12-14T20-21-43.914Z.log](https://github.com/microsoft/vscode-remote-release/files/10231418/remoteContainers-2022-12-14T20-21-43.914Z.log)
