### ISSUE TITLE
Cannot download VS Code Remote Development via SSH when proxy is needed

### ISSUE THREAD

**Issue by dlordi** [microsoft/vscode-remote-release#78]
I've setup a SSH connection following instructions on https://code.visualstudio.com/docs/remote/ssh. It seems I can login on remote host but I got this error:
Downloading VS Code Server failed. Please try again later.
I've checked requirements for VS Code Remote and I can both reach update.code.visualstudio.com and marketplace.visualstudio.com from remote host
Thanks!

**Comment by kieferrm** [comment]
@dlordi can you pls open the Remote-SSH output channel and paste here what's in there?

**Comment by bissonex** [comment]
Same issue, I am behind a corporate proxy. Can reach update.code.visualstudio.com from remote host.
httping -h https://update.code.visualstudio.com -x XX.XX.XX --proxy-user XXX --proxy-password XXX
PING https:0 (//update.code.visualstudio.com/):
connected to https:0 (309 bytes), seq=0 time=  1.94 ms 

[Remote-SSH output channel]
> Installing...
> Downloading with wget
> 
> wget: unable to resolve host address ‘update.code.visualstudio.com’
> 5cd49d91-8bdb-4263-af9f-91c68761b5ff##25##
> 
"install" terminal command done
Received install output: 5cd49d91-8bdb-4263-af9f-91c68761b5ff##25##
Server download failed
Downloading VS Code Server failed. Please try again later.

**Comment by kevinchow1993** [comment]
same issue，


>269 packages can be updated.
210 updates are security updates.
bash: cannot set terminal process group (174222): Inappropriate ioctl for device
bash: no job control in this shell
Installing...
Downloading with wget

**Comment by Ludorg** [comment]
Same issue for me (I'm behind a corporate proxy).
wget: unable to resolve host address ‘update.code.visualstudio.com’

Could you provide an offline installation for all dependencies for this extension.
All is fine when installing in a personal environment and I found it marvelous !!

**Comment by dlordi** [comment]
@kieferrm 
SSH Resolver called for "ssh-remote+XXXXXXXX"
SSH Resolver called for host: XXXXXXXX
Setting up SSH remote "XXXXXXXX"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> bash: no job control in this shell
> Installing...
> Downloading with wget
> 
> 
> Unable to establish SSL connection.
> 2838eebe-5b14-4e73-bde8-7ce8d6d514d4##25##
> 
"install" terminal command done
Received install output: 2838eebe-5b14-4e73-bde8-7ce8d6d514d4##25##
Server download failed
Downloading VS Code Server failed. Please try again later.

**Comment by hkarpf** [comment]
This can be fixed by setting your proxies wget will use in .wgetrc in your home directory:  ~/.wgetrc
Example:
```
use_proxy=on
http_proxy=http://myproxy.proxy.net:3128
https_proxy=http://myproxy.proxy.net:3128
```
This fixed my issue of wget hanging and it worked after doing this.

**Comment by bissonex** [comment]
@hkarpf  Thanks that solve my problem. Now it is the extensions that won't install on SSH:remote

**Comment by hkarpf** [comment]
@dlordi @kieferrm @perid007 Similar to what I had above for the proxy issue, add 
`check-certificate=off`
 to your .wgetrc.  **NOTE**: this is a security issue and will apply that to wget EVERY time you run it.

**Comment by dlordi** [comment]
@hkarpf this is still not working for me. Also, I don't like it.
As far as I can understand, this extension would download some sort of Remote Development Server using wget from the remote server I'm going to SSH into: why not downloading it from my PC and then transfer it to the remote server? Some remote servers have very strict rules on what sites they can connect. Also, once downloaded on my PC, it can be cached and reused... it would basically be part of the extension itself. Did I missed something?

**Comment by gooker** [comment]
ping update.code.visualstudio.com
PING waws-prod-bay-109.cloudapp.net (104.42.78.153) 56(84) bytes of data.

--- waws-prod-bay-109.cloudapp.net ping statistics ---
227 packets transmitted, 0 received, 100% packet loss, time 226091ms

**Comment by gusioo** [comment]
> @dlordi @kieferrm @perid007 Similar to what I had above for the proxy issue, add
> `check-certificate=off`
> to your .wgetrc. **NOTE**: this is a security issue and will apply that to wget EVERY time you run it.

@hkarpf works like a charm!

**Comment by alexrjs** [comment]
.wgetrc only works if wget is available on the remote host... On our machines there is no wget only curl... It fails for me, cause I need to set a proxy... Any solution for that?

My output:
`remote-ssh@0.42.0
SSH Resolver called for "ssh-remote+xxxx"
SSH Resolver called for host: xxxx
Setting up SSH remote "xxxx"
Using commit id "553cfb2c2205db5f15f3ee8395bbd5cf066d357d" and quality "stable" for server
Install and start server if needed`
> 
> Installing to /xxxx/.vscode-server/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d...
> 
> Downloading with curl
> 
> curl: (6) Could not resolve host: update.code.visualstudio.com; Unbekannter Fehler 000
> fa2d8ab4-2480-4785-9d5c-4ad132608d19##25##
> 
`"install" terminal command done
Received install output: fa2d8ab4-2480-4785-9d5c-4ad132608d19##25##
Server download failed
Downloading VS Code Server failed. Please try again later.
`

**Comment by hkarpf** [comment]
@alexrjs There is a similar file for curl.... ~/.curlrc:

`~/.curlrc file (create it if it does not exist)`
`proxy = <proxy_host>:<proxy_port>`

**Comment by yongwn** [comment]
I do this ,and sloved my problem;
I add a .wgetrc in ~/.wgetrc
content is :
`use_proxy=on

check-certificate=off

http_proxy=http://username:passwd@proxy.xxx.com:8080

https_proxy=http://username:passwd@proxy.xxx.com:8080`

**Comment by jby** [comment]
Oh, you might want to update this page: https://code.visualstudio.com/docs/remote/linux
with the requirement that the remote host needs internet access to be able to download and setup the 'server-parts' for VSCode. Since it today clearly states:

```
If you are using a recent 64-bit x86 stable/LTS version of:

    Ubuntu (14.04+)
    Debian (8+)
    CentOS / RHEL (7+)

then the VS Code Remote Development extensions should work without additional dependencies.
```
And that's apparently clearly _not true_, since you need this 'server component' as well...

**Comment by jrderuiter** [comment]
I'm experiencing a similar issue, where the wget command for downloading the server component is timing out because it can't get through the proxy. I have the `http_proxy` and `https_proxy` env variables set to point to the correct proxy, but it still doesn't seem to work. 

What kind of shell is vscode using to download the remote server? (This might explain in my cae why these environment variables aren't being picked up?)

**Comment by desar** [comment]
Having the same issue here.

`"install" terminal command done
Received install output: e6c3b59e-02bf-4fe7-afef-17f97df04c74##25##
Server download failed
Downloading VS Code Server failed. Please try again later.
------`

setting check-certificate=off on .wgetrc doesn't work either. not using proxy.
Ubuntu 18.04

As productivity tools, this is wasting my time.

**Comment by AlistairHardy** [comment]
> 
> And that's apparently clearly _not true_, since you need this 'server component' as well...
>
IMO, they should have the VSCode extension push the files over using SCP.

**Comment by tuloski** [comment]
IMO it's really weird that the extension tries to download something with wget in the server.
The server can not have internet connection (it's on local network) or network restrictions.

**Comment by dlordi** [comment]
Can anyone confirm last releases fixed this issue? I think it now uses VSCode extension installed on client workstation as source for the remote server... so, they basically implemented it as described in these comments

**Comment by jvanheugten** [comment]
It doesn't work for me:
```
Server download failed
Downloading VS Code Server failed. Please try again later
```

VS Code Insiders:
```
Version: 1.37.0-insider (user setup)
Commit: cf03ea3729dc37e439d724267ad29dc5840f903a
Date: 2019-07-30T07:15:22.972Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by somecallmemike** [comment]
We are running into this issue when sshing into an environment that is airgapped from the internet due to security reasons.  Wget or any other protocol attempting to reach an internet based resource will fail.  Can this feature be turned off to allow the ssh session to be established?  I just downloaded the latest release and it's giving the error:

`Server download failed
Downloading VS Code Server failed. Please try again later`

So it does not appear to be pushing the needed files from VScode itself as mentioned above.

**Comment by alfonsomhc** [comment]
I have also found this issue. My linux server can't connect to the internet, so it would be great that the extension would install VS Code Server pushing the install file through scp.

**Comment by niiiksh** [comment]
I have the same problem. It says
```
Downloading with wget
> wget download failed
> wget: Unknown command “locale” in /etc/wgetrc at line 123. Unable to establish SSL connection.
Server download failed
Downloading VS Code Server failed. Please try again later.
```

**Comment by adamidon** [comment]
I am also facing this issue. And in addition, I checked whether wget is actually working on my remote machine, and it is working.

```
wget update.code.visualstudio.com
URL transformed to HTTPS due to an HSTS policy
--2019-08-16 09:05:25--  https://update.code.visualstudio.com/
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 24 [text/plain]
Saving to: ‘index.html’

index.html                    100%[=================================================>]      24  --.-KB/s    in 0s

2019-08-16 09:05:26 (2.87 MB/s) - ‘index.html’ saved [24/24]
```

However, through VS code:
```
...
> Downloading with wget
> 
[01:13:16.270] > wget download failed
> wget: unable to resolve host address ‘update.code.visualstudio.com’
...
```

**Comment by jia2** [comment]
I found out, there is a redirection from https://update.code.visualstudio.com to https://az764295.vo.msecnd.net/. So the download url https://update.code.visualstudio.com/commit:f06011ac164ae4dc8e753a3fe7f9549844d15e35/server-linux-x64/stable will redirect to https://az764295.vo.msecnd.net/stable/f06011ac164ae4dc8e753a3fe7f9549844d15e35/vscode-server-linux-x64.tar.gz. If you are behind a proxy, you need ensure both update.code.visualstudio.com and .msecnd.net are in the proxy white list.

**Comment by jia2** [comment]
workaround: install vs code server manually

1. Through the vs code output panel you can get the commit it, then you can download the tar file
 https://update.code.visualstudio.com/commit:<commit-id>/server-linux-x64/stable
2. copy the download file vscode-server-linux-x64.tar.gz to your remote server.
3. make a direcotry .vscode-server/<commit-id> in your home directory, for example 
`mkdir -p ~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35`
4. untar the vscode-server-linux-x64.tar.gz, you will get a folder vscode-server-linux-x64. 
5. move all files under vscode-server-linux-x64  to ~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35

Now you can connect to remote vs code server!

**Comment by adamidon** [comment]
Thank you @jia2 . The workaround by installing vs code server manually works for me.

I only had problem with a script that vs code run afterwards, located in:

`C:\Users\<username>\AppData\Local\Temp\vscode-linux-multi-line-command-<remote-server-address>-XXXXXXXXX.sh`

So just copy it to the remote server and run it manually.

**Comment by chuck6** [comment]
@jia2 , thank you . i follow you trips , but i got other errors.   some like this:
"
[09:14:12.070] > Running remote connection script
> 
[09:14:12.095] > Acquiring lock on /home/docker/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f954
> 9844d15e35/vscode-remote-lock.f06011ac164ae4dc8e753a3fe7f9549844d15e35
> Found existing installation at /home/docker/.vscode-server/bin/f06011ac164ae4dc8
> e753a3fe7f9549844d15e35...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[09:14:12.131] > Checking server status on port 33501 with wget
> 
> 1677680c-5575-40fe-9c1c-ce2bd9e05d75##28##
> 
[09:14:12.131] Received install output: 1677680c-5575-40fe-9c1c-ce2bd9e05d75##28##
[09:14:12.131] Server status check failed - waiting and retrying 30
[09:14:12.382] "install" terminal command done
[09:14:12.382] Install terminal quit with output: 
[09:14:13.131] 
[09:14:13.132] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExhaustedRetries"},"measures":{"resolveAttempts":1}}
[09:14:13.133] ------
"

**Comment by renankaic** [comment]
I don't know if you already solved this issue. But I could solve by doing the following:

On ~/.wgetrc file I wrote the following code:
`ca_certificate = /home/administrator/certificate/my_ssl_certificate.crt
use_proxy = on
http_proxy=http://[proxy_user]:[proxy_pass]@[proxy_address]:[proxy_port]/
https_proxy=http://[proxy_user]:[proxy_pass]@[proxy_address]:[proxy_port]/
`

**Comment by T-One** [comment]
Same Problem in my company. The Dev-environment is completly locked down in VLANs without any proxy access at all, updates and package installation is managed via local RHEL Satellite Servers.
So there is no workaround for us via proxy-settings, the only methods working would be a "push" from the client or MS provides a RPM which we could integrate in our Satellite env.

**Comment by KoenChiu** [comment]
Get the same issue.
Add a line code:
`check-certificate=off`
to `~/.wgetrc` solve my problem.

**NOTE:** Disabling certificate check is not recommended as it can be a security threat. **Remove it** after you get what you want.

**Comment by cliffburdick** [comment]
> workaround: install vs code server manually
> 
> 1. Through the vs code output panel you can get the commit it, then you can download the tar file
>    `https://update.code.visualstudio.com/commit:<commit-id>/server-linux-x64/stable` in your local machine
> 2. copy the download file `vscode-server-linux-x64.tar.gz` to your remote server.
> 3. make a direcotry .vscode-server/ in your home directory, for example
>    `mkdir -p ~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35`
> 4. untar the `vscode-server-linux-x64.tar.gz`, you will get a folder `vscode-server-linux-x64`.
> 5. move all files under vscode-server-linux-x64  to `~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35`
> 
> Now you can connect to remote vs code server!

Step 5 shoudl be to move it into ~/.vscode-server/bin/... Maybe that's only for insiders, but that worked for me.

**Comment by qq731574722** [comment]
> > workaround: install vs code server manually
> > 
> > 1. Through the vs code output panel you can get the commit it, then you can download the tar file
> >    `https://update.code.visualstudio.com/commit:<commit-id>/server-linux-x64/stable` in your local machine
> > 2. copy the download file `vscode-server-linux-x64.tar.gz` to your remote server.
> > 3. make a direcotry .vscode-server/ in your home directory, for example
> >    `mkdir -p ~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35`
> > 4. untar the `vscode-server-linux-x64.tar.gz`, you will get a folder `vscode-server-linux-x64`.
> > 5. move all files under vscode-server-linux-x64  to `~/.vscode-server/f06011ac164ae4dc8e753a3fe7f9549844d15e35`
> > 
> > Now you can connect to remote vs code server!
> 
> Step 5 shoudl be to move it into ~/.vscode-server/bin/... Maybe that's only for insiders, but that worked for me.

not insider and worked

**Comment by roman-geraskin** [comment]
Same problem. May be better way to install vscode-server is to download that archive by VS Code editor and to transfer it to the target machine by ssh?

**Comment by dlordi** [comment]
@roman-geraskin that's my very same opinion see https://github.com/microsoft/vscode-remote-release/issues/78#issuecomment-491836452.
that's unfortunate, I'm still waiting for this to get fixed to use extensively vscode on my day-to-day work

**Comment by bilal-fazlani** [comment]
I am also facing this issue

**Comment by zulrang** [comment]
We're also needing an offline solution for this.  I'm getting a version mismatch error trying the manual options above.

**Comment by dpanic** [comment]
Same problem here...

**Comment by jiahaowu** [comment]
I have the same problem after updating the extension..  Now I downgraded "Remote - SSH" to 0.46.0 and "Remote Development" to 0.16.0 and then everything worked...

**Comment by trentn** [comment]
The steps commented above to install manually worked for me on the latest versions.
I enabled the 'remote.SSH.showLoginTerminal' option which allowed me to see which commit id the install script tried to download.
After it failed, I followed the steps described to manually install the remote server using that commit id (both in the download URL, and in the install path).

I expect that if there are any updates, I will need to reinstall manually with the new commit id.

**Comment by mesmat** [comment]
How can I manually download vscode-server-insiders commit id: bdd1971f2cd9d08a8a90e02740f1850afe03da66 specifically?

The download URL does not show up in the terminal logs!

**Comment by ikegentz** [comment]
> How can I manually download vscode-server-insiders commit id: bdd1971f2cd9d08a8a90e02740f1850afe03da66 specifically?
> 
> The download URL does not show up in the terminal logs!

I couldn't find it in my terminal logs either, but the "manual install" comment had this in it
`https://update.code.visualstudio.com/commit:<commit-id>/server-linux-x64/stable`
Notice the **<commit-id>** in that URL, put your ID in there.

On an unrelated note, I got that part working, but now it's failing with 
```
Got stderr from ssh: OpenSSH_7.7p1, OpenSSL 1.0.2o  27 Mar 2018
[21:15:57.234] Running script with connection command: ssh -D 56076 <server_name> bash
[21:15:57.247] Install and start server if needed
[21:16:14.248] Connecting with SSH timed out
[21:16:14.249] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout"},"measures":{"resolveAttempts":1,"retries":1}}
```

So close...

**Comment by ikegentz** [comment]
Also, is anyone else here trying to get this set up because VSCode is so slow when running over SSH/X11 Forwarding? Weirdly for me, if I fire up Pycharm or CLion through X11 they are fast, but not VS-Code, hence why I'm attempting this solution.

**Comment by CharcoStudios** [comment]
This did the job for me on debian jessie:

> sudo apt-get update
> sudo apt-get -y install apt-transport-https

**Comment by dimart** [comment]
Go to _Remote-SSH: Settings_ and turn on _Allow Local Server Download_ option.

**Comment by jia2** [comment]
For the option "Allow Local Server Download" I would like to have an option for setting proxy for download on client. Because I got this below, when I enabled "Allow Local Server Download"

`Error: Failed to download VS Code Server: HTTP 407 - Proxy Authentication Required
	at ClientRequest.a.get.t (c:\Users\xxxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.47.1\out\extension.js:1:291248)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:187:15)
	at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
	at Socket.socketOnData (_http_client.js:441:20)
	at Socket.emit (events.js:182:13)
	at ClientRequest.onsocket (d:\Entwicklung\VSCode\resources\app\node_modules.asar\https-proxy-agent\index.js:182:14)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:187:15)
	at tickOnSocket (_http_client.js:654:7)
	at onSocketNT (_http_client.js:693:5)
	at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by michellenw** [comment]
I'm still encountering this issue:
_[22:20:35.712] > Checking server status on port 37881 with wget
[22:20:35.718] > failed: Connection refused.
> 93973c70bb4f##28##
[22:20:35.989] "install" terminal command done
[22:20:35.989] Install terminal quit with output: 93973c70bb4f##28##
[22:20:35.989] Received install output: 93973c70bb4f##28##
[22:20:35.990] Server status check failed - waiting and retrying
[22:20:37.533] > Password: 
[22:20:37.533] Got some output, clearing connection timeout
[22:20:37.534] Showing password prompt_

None of the suggested fixes work

**Comment by davidsandilands** [comment]
I have the same issue as @jia2 but I'm not sure why its not authenticating as my understanding is vs code should just use chronium proxy settings which works for my normal vs code session.

"For the option "Allow Local Server Download" I would like to have an option for setting proxy for download on client. Because I got this below, when I enabled "Allow Local Server Download"

[17:15:53.938] Got request to download on client for x64
[17:16:01.634] Terminating local server
[17:16:01.637] Resolver error: Failed to download VS Code Server: HTTP 407 - Proxy Authentication Required
[17:16:01.638] ------

**Comment by danilaml** [comment]
@jia2 Huge thanks. It's maddening that 1) this is still an issue 2) the log is totally unhelpful, it just says "downloading abc". From where does it download? Where to? - have fun figuring out for yourself. No chance to diagnose the problem if something went wrong during download/unpacking (in my case my `tar` version appeared to be too old sor it rejected .gz archive). Not to mention that it's totally unnecessary and even wrong - if you have an SSH connection, just push the files over SCP. Remote doesn't mean connected to the web (it could be local network only, behind firewall or proxies).

**Comment by roblourens** [comment]
I think that I have fixed this in https://github.com/microsoft/vscode-remote-release/issues/1903 in the latest nightly version of the extension and would really appreciate it if someone would try it out.

If the download fails on the remote, it should download locally and now should respect your locally configured proxy. If you still have issues, please share the log from the Remote-SSH output channel.

**Comment by lpetre** [comment]
Thanks @roblourens! I can confirm this works on 2019.12.44160

**Comment by geekox86** [comment]
Greetings,

I still face the "Downloading VS Code Server failed" error trying to connect from my Mac to Windows Server 2016 (with OpenSSH v8.1.0.0p1-Beta). Any clue on how to fix it?

```
[22:58:47.593] Got some output, clearing connection timeout
[22:58:47.594] Showing password prompt
[22:58:51.003] Got password response
[22:58:51.004] "install" wrote data to terminal: "**********"
[22:58:51.016] > 
[22:58:51.674] > Looking for existing server in C:\Users\Administrator\.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729
[22:58:51.681] > Downloading VS Code Server
[22:58:52.656] > Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
> 64880044b08d##25##
[22:58:52.960] "install" terminal command done
[22:58:52.960] Install terminal quit with output: 64880044b08d##25##
[22:58:52.960] Received install output: 64880044b08d##25##
[22:58:52.960] Server download failed
[22:58:52.960] Resolver error: Downloading VS Code Server failed. Please try again later.
[22:58:52.963] ------
```

VS Code Insider:
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

Extensions:
Remote Development 0.19.0
Remote - SSH 0.48.0

**Comment by geekox86** [comment]
Greetings and thank you for the great extension.

I am getting the following error while trying to connect from my Mac to Windows Server 2016 (with OpenSSH v8.1.0.0p1-Beta). Any clue on how to solve this?

```
Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
```

```
[07:47:20.552] > Looking for existing server in C:\Users\Administrator\.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729
[07:47:20.558] > Downloading VS Code Server
[07:47:24.066] > Failed to download & extract vscode-server. - The underlying connection was closed: An unexpected error occurred on a send.
> e83e985ee2f7##25##
[07:47:24.403] "install" terminal command done
[07:47:24.404] Install terminal quit with output: e83e985ee2f7##25##
[07:47:24.404] Received install output: e83e985ee2f7##25##
[07:47:24.404] Server download failed
[07:47:24.404] Resolver error: Downloading VS Code Server failed. Please try again later.
[07:47:24.407] ------
```

I am using VS Code Insider:
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

Extensions:
```
Remote Development 0.19.0
Remote - SSH 0.48.0
```

**Comment by jsg2021** [comment]
I got the same error as @geekox86 I was attempting to remote into a Windows Server 2016 box in AWS on a corp domain. I got around it by copying the base64 ps script from the client log, then opening a remote desktop and put the decoded script on the box, adding `-SkipCertificateCheck` to the line with `Invoke-RestMethod @splat`:
```
Invoke-RestMethod -SkipCertificateCheck @splat
```

Then running the script with PowerShell 6 (`dotnet tool install --global PowerShell`). Once installed i can connect.

**Comment by roblourens** [comment]
Thanks @jsg2021, that's a really good hint. It's not safe to add that property by default but I'll investigate it in this issue: https://github.com/microsoft/vscode-remote-release/issues/2261

**Comment by jsg2021** [comment]
@roblourens yeah, I know. It was just meant to be additional information. The requested url when you hit with `curl -v {url}` shows a https => http redirect. I think that is the problem. (a downgrade)

**Comment by roblourens** [comment]
It should redirect you to `https://az764295.vo.msecnd.net`, also https, what do you get redirected to?

**Comment by jsg2021** [comment]
```
curl -v https://update.code.visualstudio.com/commit:c4b6a6b537de49a734d0eedea06152ea37dfdb6a/server-win32-x64/insider
*   Trying 104.42.78.153...
* TCP_NODELAY set
* Connected to update.code.visualstudio.com (104.42.78.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=update.code.visualstudio.com
*  start date: Oct 30 07:50:15 2018 GMT
*  expire date: Oct 30 07:50:15 2020 GMT
*  subjectAltName: host "update.code.visualstudio.com" matched cert's "update.code.visualstudio.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
> GET /commit:c4b6a6b537de49a734d0eedea06152ea37dfdb6a/server-win32-x64/insider HTTP/1.1
> Host: update.code.visualstudio.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Content-Length: 129
< Content-Type: text/plain; charset=utf-8
< Location: https://az764295.vo.msecnd.net/insider/c4b6a6b537de49a734d0eedea06152ea37dfdb6a/vscode-server-win32-x64.zip
< Vary: Accept
< request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
< X-Powered-By: Express
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Source-Commit: 5b1e6aaf6afec2feec218a378676e943da8f7885
< X-SHA256: d2035a6fb5908a935c3b4a4a5135542eb3800f9cae343f8e8c999dadf5732c50
< Set-Cookie: ARRAffinity=8baa90639b969d8df14774e1cd0fcbcad641ade960f94a7cc7176ee0ed99cc80;Path=/;HttpOnly;Domain=update.code.visualstudio.com
< Date: Wed, 29 Jan 2020 20:21:42 GMT
<
* Connection #0 to host update.code.visualstudio.com left intact
Found. Redirecting to https://az764295.vo.msecnd.net/insider/c4b6a6b537de49a734d0eedea06152ea37dfdb6a/vscode-server-win32-x64.zip* 
Closing connection 0
```

**Comment by jsg2021** [comment]
So, it is now https... but earlier today it was http.
