### ISSUE TITLE
Cannot connect to a remote host

### ISSUE THREAD

**Issue by poseidon974** [microsoft/vscode-remote-release#8335]
hello,

Since the last update, it is impossible for me to connect to my raspberry.

I have deleted the .vscode-server folder on the remote host and it does not change anything.

Here is the configuration and the logs obtained :

- VSCode Version: 1.77.1
- Local OS Version W10 22h2
- Remote OS Version: "Raspbian GNU/Linux 11 (bullseye)"
- Remote Extension/Connection Type: Server

- Logs:

```txt
[20:26:12.917] Log Level: 1
[20:26:12.929] remote-ssh@0.92.0
[20:26:12.929] win32 x64
[20:26:12.956] SSH Resolver called for "ssh-remote+192.168.0.22", attempt 1
[20:26:12.957] "remote.SSH.useLocalServer": false
[20:26:12.957] "remote.SSH.showLoginTerminal": false
[20:26:12.958] "remote.SSH.remotePlatform": {}
[20:26:12.959] "remote.SSH.path": undefined
[20:26:12.959] "remote.SSH.configFile": C:\Users\Léo\.ssh\configurationforvscode
[20:26:12.959] "remote.SSH.useFlock": false
[20:26:12.960] "remote.SSH.lockfilesInTmp": false
[20:26:12.960] "remote.SSH.localServerDownload": always
[20:26:12.961] "remote.SSH.remoteServerListenOnSocket": false
[20:26:12.961] "remote.SSH.showLoginTerminal": false
[20:26:12.961] "remote.SSH.defaultExtensions": []
[20:26:12.961] "remote.SSH.loglevel": 1
[20:26:12.962] "remote.SSH.enableDynamicForwarding": true
[20:26:12.963] "remote.SSH.enableRemoteCommand": false
[20:26:12.963] "remote.SSH.serverPickPortsFromRange": {}
[20:26:12.963] "remote.SSH.serverInstallPath": {}
[20:26:12.975] SSH Resolver called for host: 192.168.0.22
[20:26:12.975] Setting up SSH remote "192.168.0.22"
[20:26:12.986] Using commit id "b7886d7461186a5eac768481578c1d7ca80e2d21" and quality "stable" for server
[20:26:12.993] Install and start server if needed
[20:26:14.283] Checking ssh with "ssh -V"
[20:26:14.328] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[20:26:14.333] Using SSH config file "C:\Users\Léo\.ssh\configurationforvscode"
[20:26:14.333] Running script with connection command: ssh -T -D 57952 -F "C:\Users\Léo\.ssh\configurationforvscode" "192.168.0.22" bash
[20:26:14.336] Terminal shell path: C:\Windows\System32\cmd.exe
[20:26:14.722] "install" terminal received data: "[2J[m[H]0;C:\Windows\System32\cmd.exe[?25h"
[20:26:14.723] Got some output, clearing connection timeout
[20:26:14.940] "install" terminal received data: "leo@192.168.0.22's password: "
[20:26:14.941] Showing password prompt
[20:26:18.715] Got password response
[20:26:18.716] "install" wrote data to terminal: "***********"
[20:26:18.729] "install" terminal received data: ""
[20:26:19.485] "install" terminal received data: "1b35dffd3a03: running"
[20:26:19.551] "install" terminal received data: "Acquiring lock on /home/leo/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca
80e2d21/vscode-remote-lock.leo.b7886d7461186a5eac768481578c1d7ca80e2d21[K"
[20:26:19.570] "install" terminal received data: "\ln /home/leo/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/vscode
-remote-lock.leo.b7886d7461186a5eac768481578c1d7ca80e2d21.target /home/leo/.vsco
de-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/vscode-remote-lock.leo.b7
886d7461186a5eac768481578c1d7ca80e2d21[K"
[20:26:19.586] "install" terminal received data: "Found existing installation at /home/leo/.vscode-server/bin/b7886d7461186a5eac76
8481578c1d7ca80e2d21...[K
Checking /home/leo/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log 
and /home/leo/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.pid for a
 running server[K
Looking for server with pid: 24624[K"
[20:26:19.626] "install" terminal received data: "Starting server with command... /home/leo/.vscode-server/bin/b7886d7461186a5eac7
68481578c1d7ca80e2d21/bin/code-server --start-server --host=127.0.0.1 --accept-s
erver-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all
   &> "/home/leo/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log" <
 /dev/null[K
printenv:[K
    SHELL=/bin/bash[35X
    LANGUAGE=fr_FR.UTF-8[30X
    PWD=/home/leo[37X
    LOGNAME=leo[39X
    XDG_SESSION_TYPE=tty[30X
    MOTD_SHOWN=pam[36X
    HOME=/home/leo[36X
    LANG=fr_FR.UTF-8[34X
    VSCODE_AGENT_FOLDER=/home/leo/.vscode-server      
    SSH_CONNECTION=192.168.0.150 57971 192.168.0.22 22
    XDG_SESSION_CLASS=user
    USER=leo
    SHLVL=0
    XDG_SESSION_ID=32
    XDG_RUNTIME_DIR=/run/user/1000
    SSH_CLIENT=192.168.0.150 57971 22"
[20:26:19.634] "install" terminal received data: "
    LC_ALL=fr_FR.UTF-8
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    _=/usr/bin/printenv"
[20:26:19.646] "install" terminal received data: "
Removing old logfile at /home/leo/.vscode-server/.b7886d7461186a5eac768481578c1d
7ca80e2d21.log
Spawned remote server: 26779"
[20:26:19.660] "install" terminal received data: "
Waiting for server log..."
[20:26:19.701] "install" terminal received data: "Waiting for server log..."
[20:26:19.742] "install" terminal received data: "Waiting for server log..."
[20:26:19.783] "install" terminal received data: "Waiting for server log..."
[20:26:19.832] "install" terminal received data: "Waiting for server log..."
[20:26:19.882] "install" terminal received data: "Waiting for server log..."
[20:26:19.929] "install" terminal received data: "Waiting for server log..."
[20:26:19.976] "install" terminal received data: "Waiting for server log..."
[20:26:20.025] "install" terminal received data: "Waiting for server log..."
[20:26:20.072] "install" terminal received data: "Waiting for server log..."
[20:26:20.120] "install" terminal received data: "Waiting for server log..."
[20:26:20.171] "install" terminal received data: "Waiting for server log..."
[20:26:20.219] "install" terminal received data: "Waiting for server log..."
[20:26:20.265] "install" terminal received data: "Waiting for server log..."
[20:26:20.313] "install" terminal received data: "Waiting for server log..."
[20:26:20.361] "install" terminal received data: "Waiting for server log..."
[20:26:20.410] "install" terminal received data: "Waiting for server log..."
[20:26:20.457] "install" terminal received data: "Waiting for server log..."
[20:26:20.503] "install" terminal received data: "Waiting for server log..."
[20:26:20.551] "install" terminal received data: "Waiting for server log..."
[20:26:20.597] "install" terminal received data: "Waiting for server log..."
[20:26:20.649] "install" terminal received data: "Waiting for server log..."
[20:26:20.698] "install" terminal received data: "Waiting for server log..."
[20:26:20.744] "install" terminal received data: "Waiting for server log..."
[20:26:20.791] "install" terminal received data: "Waiting for server log..."
[20:26:20.838] "install" terminal received data: "Waiting for server log..."
[20:26:20.887] "install" terminal received data: "Waiting for server log..."
[20:26:20.945] "install" terminal received data: "Waiting for server log..."
[20:26:20.984] "install" terminal received data: "Waiting for server log..."
[20:26:21.027] "install" terminal received data: "Waiting for server log..."
[20:26:21.068] "install" terminal received data: "Waiting for server log..."
[20:26:21.111] "install" terminal received data: "Waiting for server log..."
[20:26:21.151] "install" terminal received data: "Waiting for server log..."
[20:26:21.195] "install" terminal received data: "Waiting for server log..."
[20:26:21.236] "install" terminal received data: "Waiting for server log..."
[20:26:21.276] "install" terminal received data: "Waiting for server log..."
[20:26:21.318] "install" terminal received data: "Waiting for server log..."
[20:26:21.358] "install" terminal received data: "Waiting for server log..."
[20:26:21.400] "install" terminal received data: "Waiting for server log..."
[20:26:21.440] "install" terminal received data: "Waiting for server log..."
[20:26:21.481] "install" terminal received data: "Waiting for server log..."
[20:26:21.523] "install" terminal received data: "Waiting for server log..."
[20:26:21.564] "install" terminal received data: "Waiting for server log..."
[20:26:21.605] "install" terminal received data: "Waiting for server log..."
[20:26:21.646] "install" terminal received data: "Waiting for server log..."
[20:26:21.686] "install" terminal received data: "Waiting for server log..."
[20:26:21.728] "install" terminal received data: "Waiting for server log..."
[20:26:21.769] "install" terminal received data: "Waiting for server log..."
[20:26:21.810] "install" terminal received data: "Waiting for server log..."
[20:26:21.851] "install" terminal received data: "Waiting for server log..."
[20:26:21.892] "install" terminal received data: "Waiting for server log..."
[20:26:21.933] "install" terminal received data: "Waiting for server log..."
[20:26:21.975] "install" terminal received data: "Waiting for server log..."
[20:26:22.016] "install" terminal received data: "Waiting for server log..."
[20:26:22.058] "install" terminal received data: "Waiting for server log..."
[20:26:22.098] "install" terminal received data: "Waiting for server log..."
[20:26:22.142] "install" terminal received data: "Waiting for server log..."
[20:26:22.183] "install" terminal received data: "Waiting for server log..."
[20:26:22.224] "install" terminal received data: "Waiting for server log..."
[20:26:22.265] "install" terminal received data: "Waiting for server log..."
[20:26:22.307] "install" terminal received data: "Waiting for server log..."
[20:26:22.348] "install" terminal received data: "Waiting for server log..."
[20:26:22.389] "install" terminal received data: "Waiting for server log..."
[20:26:22.430] "install" terminal received data: "Waiting for server log..."
[20:26:22.472] "install" terminal received data: "Waiting for server log..."
[20:26:22.513] "install" terminal received data: "Waiting for server log..."
[20:26:22.553] "install" terminal received data: "Waiting for server log..."
[20:26:22.597] "install" terminal received data: "Waiting for server log..."
[20:26:22.639] "install" terminal received data: "Waiting for server log..."
[20:26:22.680] "install" terminal received data: "Waiting for server log..."
[20:26:22.723] "install" terminal received data: "Waiting for server log..."
[20:26:22.764] "install" terminal received data: "Waiting for server log..."
[20:26:22.807] "install" terminal received data: "Waiting for server log..."
[20:26:22.846] "install" terminal received data: "Waiting for server log..."
[20:26:22.886] "install" terminal received data: "Waiting for server log..."
[20:26:22.927] "install" terminal received data: "Waiting for server log..."
[20:26:22.970] "install" terminal received data: "Waiting for server log..."
[20:26:23.010] "install" terminal received data: "Waiting for server log..."
[20:26:23.051] "install" terminal received data: "Waiting for server log..."
[20:26:23.092] "install" terminal received data: "Waiting for server log..."
[20:26:23.132] "install" terminal received data: "Waiting for server log..."
[20:26:23.174] "install" terminal received data: "Waiting for server log..."
[20:26:23.217] "install" terminal received data: "Waiting for server log..."
[20:26:23.255] "install" terminal received data: "Waiting for server log..."
[20:26:23.296] "install" terminal received data: "Waiting for server log..."
[20:26:23.337] "install" terminal received data: "Waiting for server log..."
[20:26:23.380] "install" terminal received data: "Waiting for server log..."
[20:26:23.420] "install" terminal received data: "Waiting for server log..."
[20:26:23.462] "install" terminal received data: "Waiting for server log..."
[20:26:23.502] "install" terminal received data: "Waiting for server log..."
[20:26:23.543] "install" terminal received data: "Waiting for server log..."
[20:26:23.583] "install" terminal received data: "Waiting for server log..."
[20:26:23.625] "install" terminal received data: "Waiting for server log..."
[20:26:23.666] "install" terminal received data: "Waiting for server log..."
[20:26:23.709] "install" terminal received data: "Waiting for server log..."
[20:26:23.752] "install" terminal received data: "Waiting for server log..."
[20:26:23.793] "install" terminal received data: "Waiting for server log..."
[20:26:23.834] "install" terminal received data: "Waiting for server log..."
[20:26:23.876] "install" terminal received data: "Waiting for server log..."
[20:26:23.918] "install" terminal received data: "Waiting for server log..."
[20:26:23.962] "install" terminal received data: "Waiting for server log..."
[20:26:24.003] "install" terminal received data: "Waiting for server log..."
[20:26:24.045] "install" terminal received data: "Waiting for server log..."
[20:26:24.086] "install" terminal received data: "Waiting for server log..."
[20:26:24.126] "install" terminal received data: "Waiting for server log..."
[20:26:24.167] "install" terminal received data: "Waiting for server log..."
[20:26:24.209] "install" terminal received data: "Waiting for server log..."
[20:26:24.250] "install" terminal received data: "Waiting for server log..."
[20:26:24.292] "install" terminal received data: "Waiting for server log..."
[20:26:24.332] "install" terminal received data: "Waiting for server log..."
[20:26:24.374] "install" terminal received data: "Waiting for server log..."
[20:26:24.416] "install" terminal received data: "Waiting for server log..."
[20:26:24.456] "install" terminal received data: "Waiting for server log..."
[20:26:24.497] "install" terminal received data: "Waiting for server log..."
[20:26:24.539] "install" terminal received data: "Waiting for server log..."
[20:26:24.580] "install" terminal received data: "Waiting for server log..."
[20:26:24.632] "install" terminal received data: "Waiting for server log..."
[20:26:24.664] "install" terminal received data: "Waiting for server log..."
[20:26:24.703] "install" terminal received data: "Waiting for server log..."
[20:26:24.744] "install" terminal received data: "Waiting for server log..."
[20:26:24.785] "install" terminal received data: "Waiting for server log..."
[20:26:24.826] "install" terminal received data: "Waiting for server log..."
[20:26:24.879] "install" terminal received data: "Waiting for server log..."
[20:26:24.910] "install" terminal received data: "Waiting for server log..."
[20:26:24.950] "install" terminal received data: "Waiting for server log..."
[20:26:24.991] "install" terminal received data: "Waiting for server log..."
[20:26:25.033] "install" terminal received data: "Waiting for server log..."
[20:26:25.075] "install" terminal received data: "Waiting for server log..."
[20:26:25.117] "install" terminal received data: "Waiting for server log..."
[20:26:25.157] "install" terminal received data: "Waiting for server log..."
[20:26:25.198] "install" terminal received data: "Waiting for server log..."
[20:26:25.249] "install" terminal received data: "Waiting for server log..."
[20:26:25.280] "install" terminal received data: "Waiting for server log..."
[20:26:25.322] "install" terminal received data: "Waiting for server log..."
[20:26:25.363] "install" terminal received data: "Waiting for server log..."
[20:26:25.405] "install" terminal received data: "Waiting for server log..."
[20:26:25.447] "install" terminal received data: "Waiting for server log..."
[20:26:25.487] "install" terminal received data: "Waiting for server log..."
[20:26:25.529] "install" terminal received data: "Waiting for server log..."
[20:26:25.570] "install" terminal received data: "Waiting for server log..."
[20:26:25.611] "install" terminal received data: "Waiting for server log..."
[20:26:25.656] "install" terminal received data: "Waiting for server log..."
[20:26:25.695] "install" terminal received data: "Waiting for server log..."
[20:26:25.737] "install" terminal received data: "Waiting for server log..."
[20:26:25.780] "install" terminal received data: "Waiting for server log..."
[20:26:25.820] "install" terminal received data: "Waiting for server log..."
[20:26:25.861] "install" terminal received data: "Waiting for server log..."
[20:26:25.902] "install" terminal received data: "Waiting for server log..."
[20:26:25.942] "install" terminal received data: "Waiting for server log..."
[20:26:25.984] "install" terminal received data: "Waiting for server log..."
[20:26:26.032] "install" terminal received data: "Waiting for server log..."
[20:26:26.081] "install" terminal received data: "Waiting for server log..."
[20:26:26.130] "install" terminal received data: "Waiting for server log..."
[20:26:26.178] "install" terminal received data: "Waiting for server log..."
[20:26:26.225] "install" terminal received data: "Waiting for server log..."
[20:26:26.274] "install" terminal received data: "Waiting for server log..."
[20:26:26.322] "install" terminal received data: "Waiting for server log..."
[20:26:26.368] "install" terminal received data: "Waiting for server log..."
[20:26:26.418] "install" terminal received data: "Waiting for server log..."
[20:26:26.465] "install" terminal received data: "Waiting for server log..."
[20:26:26.515] "install" terminal received data: "Waiting for server log..."
[20:26:26.560] "install" terminal received data: "Waiting for server log..."
[20:26:26.616] "install" terminal received data: "Waiting for server log..."
[20:26:26.657] "install" terminal received data: "Waiting for server log..."
[20:26:26.704] "install" terminal received data: "Waiting for server log..."
[20:26:26.753] "install" terminal received data: "Waiting for server log..."
[20:26:26.801] "install" terminal received data: "Waiting for server log..."
[20:26:26.848] "install" terminal received data: "Waiting for server log..."
[20:26:26.897] "install" terminal received data: "Waiting for server log..."
[20:26:26.948] "install" terminal received data: "Waiting for server log..."
[20:26:26.995] "install" terminal received data: "Waiting for server log..."
[20:26:27.042] "install" terminal received data: "Waiting for server log..."
[20:26:27.089] "install" terminal received data: "Waiting for server log..."
[20:26:27.137] "install" terminal received data: "Waiting for server log..."
[20:26:27.187] "install" terminal received data: "Waiting for server log..."
[20:26:27.241] "install" terminal received data: "Waiting for server log..."
[20:26:27.283] "install" terminal received data: "Waiting for server log..."
[20:26:27.330] "install" terminal received data: "Waiting for server log..."
[20:26:27.375] "install" terminal received data: "Waiting for server log..."
[20:26:27.422] "install" terminal received data: "Waiting for server log..."
[20:26:27.468] "install" terminal received data: "Waiting for server log..."
[20:26:27.515] "install" terminal received data: "Waiting for server log..."
[20:26:27.561] "install" terminal received data: "Waiting for server log..."
[20:26:27.608] "install" terminal received data: "Waiting for server log..."
[20:26:27.653] "install" terminal received data: "Waiting for server log..."
[20:26:27.700] "install" terminal received data: "Waiting for server log..."
[20:26:27.748] "install" terminal received data: "Waiting for server log..."
[20:26:27.796] "install" terminal received data: "Waiting for server log..."
[20:26:27.843] "install" terminal received data: "Waiting for server log..."
[20:26:27.888] "install" terminal received data: "Waiting for server log..."
[20:26:27.935] "install" terminal received data: "Waiting for server log..."
[20:26:27.984] "install" terminal received data: "Waiting for server log..."
[20:26:28.032] "install" terminal received data: "Waiting for server log..."
[20:26:28.079] "install" terminal received data: "Waiting for server log..."
[20:26:28.126] "install" terminal received data: "Waiting for server log..."
[20:26:28.174] "install" terminal received data: "Waiting for server log..."
[20:26:28.220] "install" terminal received data: "Waiting for server log..."
[20:26:28.266] "install" terminal received data: "Waiting for server log..."
[20:26:28.323] "install" terminal received data: "Waiting for server log..."
[20:26:28.360] "install" terminal received data: "Waiting for server log..."
[20:26:28.409] "install" terminal received data: "Waiting for server log..."
[20:26:28.453] "install" terminal received data: "Waiting for server log..."
[20:26:28.502] "install" terminal received data: "Waiting for server log..."
[20:26:28.552] "install" terminal received data: "Waiting for server log..."
[20:26:28.601] "install" terminal received data: "Waiting for server log..."
[20:26:28.650] "install" terminal received data: "Waiting for server log..."
[20:26:28.697] "install" terminal received data: "Waiting for server log..."
[20:26:28.738] "install" terminal received data: "Waiting for server log..."
[20:26:28.779] "install" terminal received data: "Waiting for server log..."
[20:26:28.820] "install" terminal received data: "Waiting for server log..."
[20:26:28.862] "install" terminal received data: "Waiting for server log..."
[20:26:28.902] "install" terminal received data: "Waiting for server log..."
[20:26:28.943] "install" terminal received data: "Waiting for server log..."
[20:26:28.984] "install" terminal received data: "Waiting for server log..."
[20:26:29.025] "install" terminal received data: "Waiting for server log..."
[20:26:29.066] "install" terminal received data: "Waiting for server log..."
[20:26:29.107] "install" terminal received data: "Waiting for server log..."
[20:26:29.147] "install" terminal received data: "Waiting for server log..."
[20:26:29.187] "install" terminal received data: "Waiting for server log..."
[20:26:29.229] "install" terminal received data: "Waiting for server log..."
[20:26:29.270] "install" terminal received data: "Waiting for server log..."
[20:26:29.310] "install" terminal received data: "Waiting for server log..."
[20:26:29.351] "install" terminal received data: "Waiting for server log..."
[20:26:29.392] "install" terminal received data: "Waiting for server log..."
[20:26:29.432] "install" terminal received data: "Waiting for server log..."
[20:26:29.474] "install" terminal received data: "Waiting for server log..."
[20:26:29.515] "install" terminal received data: "Waiting for server log..."
[20:26:29.556] "install" terminal received data: "Waiting for server log..."
[20:26:29.596] "install" terminal received data: "Waiting for server log..."
[20:26:29.640] "install" terminal received data: "Waiting for server log..."
[20:26:29.682] "install" terminal received data: "Waiting for server log..."
[20:26:29.722] "install" terminal received data: "Waiting for server log..."
[20:26:29.764] "install" terminal received data: "Waiting for server log..."
[20:26:29.811] "install" terminal received data: "Waiting for server log..."
[20:26:29.851] "install" terminal received data: "Waiting for server log..."
[20:26:29.891] "install" terminal received data: "Waiting for server log..."
[20:26:29.931] "install" terminal received data: "Waiting for server log..."
[20:26:29.972] "install" terminal received data: "Waiting for server log..."
[20:26:30.013] "install" terminal received data: "Waiting for server log..."
[20:26:30.054] "install" terminal received data: "Waiting for server log..."
[20:26:30.096] "install" terminal received data: "Waiting for server log..."
[20:26:30.137] "install" terminal received data: "Waiting for server log..."
[20:26:30.177] "install" terminal received data: "Waiting for server log..."
[20:26:30.219] "install" terminal received data: "Waiting for server log..."
[20:26:30.263] "install" terminal received data: "Waiting for server log..."
[20:26:30.301] "install" terminal received data: "Waiting for server log..."
[20:26:30.345] "install" terminal received data: "Waiting for server log..."
[20:26:30.386] "install" terminal received data: "Waiting for server log..."
[20:26:30.427] "install" terminal received data: "Waiting for server log..."
[20:26:30.469] "install" terminal received data: "Waiting for server log..."
[20:26:30.510] "install" terminal received data: "Waiting for server log..."
[20:26:30.551] "install" terminal received data: "Waiting for server log..."
[20:26:30.591] "install" terminal received data: "Waiting for server log..."
[20:26:30.922] "install" terminal received data: "Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log..."
[20:26:31.076] "install" terminal received data: "Waiting for server log...
[25l[HWaiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
Waiting for server log...[K
[K[?25hWaiting for server log...
Waiting for server log..."
[20:26:31.166] "install" terminal received data: "Waiting for server log...
Waiting for server log...
Waiting for server log...
Waiting for server log..."
[20:26:31.190] "install" terminal received data: "Waiting for server log..."
[20:26:31.211] "install" terminal received data: "Waiting for server log..."
[20:26:31.245] "install" terminal received data: "Waiting for server log..."
[20:26:31.285] "install" terminal received data: "Waiting for server log..."
[20:26:31.333] "install" terminal received data: "Waiting for server log..."
[20:26:31.370] "install" terminal received data: "Waiting for server log..."
[20:26:31.409] "install" terminal received data: "Waiting for server log..."
[20:26:31.449] "install" terminal received data: "Waiting for server log..."
[20:26:31.495] "install" terminal received data: "Waiting for server log..."
[20:26:31.537] "install" terminal received data: "Waiting for server log..."
[20:26:31.577] "install" terminal received data: "Waiting for server log..."
[20:26:31.618] "install" terminal received data: "Waiting for server log..."
[20:26:31.659] "install" terminal received data: "Waiting for server log..."
[20:26:31.702] "install" terminal received data: "Waiting for server log..."
[20:26:31.743] "install" terminal received data: "Waiting for server log..."
[20:26:31.782] "install" terminal received data: "Waiting for server log..."
[20:26:31.825] "install" terminal received data: "Waiting for server log..."
[20:26:31.866] "install" terminal received data: "Waiting for server log..."
[20:26:31.906] "install" terminal received data: "Waiting for server log..."
[20:26:31.948] "install" terminal received data: "Waiting for server log..."
[20:26:31.988] "install" terminal received data: "Waiting for server log..."
[20:26:32.029] "install" terminal received data: "Waiting for server log..."
[20:26:32.070] "install" terminal received data: "Waiting for server log..."
[20:26:32.111] "install" terminal received data: "Waiting for server log..."
[20:26:32.152] "install" terminal received data: "Waiting for server log..."
[20:26:32.197] "install" terminal received data: "Waiting for server log..."
[20:26:32.235] "install" terminal received data: "Waiting for server log..."
[20:26:32.275] "install" terminal received data: "Waiting for server log..."
[20:26:32.316] "install" terminal received data: "Waiting for server log..."
[20:26:32.356] "install" terminal received data: "Waiting for server log..."
[20:26:32.397] "install" terminal received data: "Waiting for server log..."
[20:26:32.441] "install" terminal received data: "Waiting for server log..."
[20:26:32.482] "install" terminal received data: "Waiting for server log..."
[20:26:32.521] "install" terminal received data: "Waiting for server log..."
[20:26:32.560] "install" terminal received data: "Waiting for server log..."
[20:26:32.601] "install" terminal received data: "Waiting for server log..."
[20:26:32.645] "install" terminal received data: "Waiting for server log..."
[20:26:32.685] "install" terminal received data: "Waiting for server log..."
[20:26:32.728] "install" terminal received data: "Waiting for server log..."
[20:26:32.769] "install" terminal received data: "Waiting for server log..."
[20:26:32.809] "install" terminal received data: "Waiting for server log..."
[20:26:32.849] "install" terminal received data: "Waiting for server log..."
[20:26:32.891] "install" terminal received data: "Waiting for server log..."
[20:26:32.932] "install" terminal received data: "Waiting for server log..."
[20:26:32.973] "install" terminal received data: "Waiting for server log..."
[20:26:33.015] "install" terminal received data: "Waiting for server log..."
[20:26:33.056] "install" terminal received data: "Waiting for server log..."
[20:26:33.097] "install" terminal received data: "Waiting for server log..."
[20:26:33.136] "install" terminal received data: "Waiting for server log..."
[20:26:33.178] "install" terminal received data: "Waiting for server log..."
[20:26:33.219] "install" terminal received data: "Waiting for server log..."
[20:26:33.262] "install" terminal received data: "Waiting for server log..."
[20:26:33.303] "install" terminal received data: "Waiting for server log..."
[20:26:33.348] "install" terminal received data: "Waiting for server log..."
[20:26:33.387] "install" terminal received data: "Waiting for server log..."
[20:26:33.427] "install" terminal received data: "Waiting for server log..."
[20:26:33.468] "install" terminal received data: "Waiting for server log..."
[20:26:33.509] "install" terminal received data: "Waiting for server log..."
[20:26:33.549] "install" terminal received data: "Waiting for server log..."
[20:26:33.603] "install" terminal received data: "Waiting for server log..."
[20:26:33.631] "install" terminal received data: "Waiting for server log..."
[20:26:33.672] "install" terminal received data: "Waiting for server log..."
[20:26:33.712] "install" terminal received data: "Waiting for server log..."
[20:26:33.760] "install" terminal received data: "Waiting for server log..."
[20:26:33.809] "install" terminal received data: "Waiting for server log..."
[20:26:33.859] "install" terminal received data: "Waiting for server log..."
[20:26:33.908] "install" terminal received data: " 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[1C"
[20:26:33.926] "install" terminal received data: ""
[20:26:33.936] "install" terminal received data: "Server did not start successfully. Full server log at /home/leo/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log >>>
/home/leo/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/code-server: 12: /home/leo/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/node: not found
<<< End of server log
1b35dffd3a03: start
exitCode==32==
listeningOn====
osReleaseId==raspbian=="
[20:26:33.942] "install" terminal received data: "
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14267==
1b35dffd3a03: end"
[20:26:33.943] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14267==

[20:26:33.944] Resolver error: Error: Échec du démarrage du serveur VS Code
	at g.ServerInstallError (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583755)
	at f (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:578003)
	at t.handleInstallOutput (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:581028)
	at t.tryInstall (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at async c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\Léo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[20:26:33.947] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"raspbian","arch":"aarch64","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"ExitCode","exitCodeLabel":"ServerFailedToStart"},"measures":{"exitCode":32,"resolveAttempts":1,"retries":1,"timing.totalResolveTime":20988,"timing.preSshTime":1380,"timing.establishSshTime":5150,"timing.scriptTime":19608}}
[20:26:33.952] ------
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by poseidon974** [comment]
Problem solved with the following steps: 

1 - Delete the .vscode-server file
2 - Creation of a bash script :

```bash
#!/bin/sh

set -e

# Auto-Get the latest commit sha via command line.
get_latest_release() {
    tag=$(curl --silent "https://api.github.com/repos/${1}/releases/latest" | # Get latest release from GitHub API
          grep '"tag_name":'                                              | # Get tag line
          sed -E 's/.*"([^"]+)".*/\1/'                                    ) # Pluck JSON value

    tag_data=$(curl --silent "https://api.github.com/repos/${1}/git/ref/tags/${tag}")

    sha=$(echo "${tag_data}"           | # Get latest release from GitHub API
          grep '"sha":'                | # Get tag line
          sed -E 's/.*"([^"]+)".*/\1/' ) # Pluck JSON value

    sha_type=$(echo "${tag_data}"           | # Get latest release from GitHub API
          grep '"type":'                    | # Get tag line
          sed -E 's/.*"([^"]+)".*/\1/'      ) # Pluck JSON value

    if [ "${sha_type}" != "commit" ]; then
        combo_sha=$(curl -s "https://api.github.com/repos/${1}/git/tags/${sha}" | # Get latest release from GitHub API
              grep '"sha":'                                                     | # Get tag line
              sed -E 's/.*"([^"]+)".*/\1/'                                      ) # Pluck JSON value

        # Remove the tag sha, leaving only the commit sha;
        # this won't work if there are ever more than 2 sha,
        # and use xargs to remove whitespace/newline.
        sha=$(echo "${combo_sha}" | sed -E "s/${sha}//" | xargs)
    fi

    printf "${sha}"
}

ARCH="x64"
U_NAME=$(uname -m)

# Raspberry pi 4b needs armv7l (armhf), but uname is specified as aarch64 (arm64) so I modified this part.
if [ "${U_NAME}" = "aarch64" ]; then
    ARCH="armhf"
fi

archive="vscode-server-linux-${ARCH}.tar.gz"
owner='microsoft'
repo='vscode'
commit_sha=$(get_latest_release "${owner}/${repo}")

if [ -n "${commit_sha}" ]; then
    echo "will attempt to download VS Code Server version = '${commit_sha}'"

    # Download VS Code Server tarball to tmp directory.
    curl -L "https://update.code.visualstudio.com/commit:${commit_sha}/server-linux-${ARCH}/stable" -o "/tmp/${archive}"

    # Make the parent directory where the server should live.
    # NOTE: Ensure VS Code will have read/write access; namely the user running VScode or container user.
    mkdir -vp ~/.vscode-server/bin/"${commit_sha}"

    # Extract the tarball to the right location.
    tar --no-same-owner -xzv --strip-components=1 -C ~/.vscode-server/bin/"${commit_sha}" -f "/tmp/${archive}"
else
    echo "could not pre install vscode server"
fi
```

3 - Execution of the script with chmod +x
4 - Connection established with SSH-remote on the windows to the raspberry

**Comment by maor1993** [comment]
Hey, please note this issue still occurs, using the script shown above fixes this.
