### ISSUE TITLE
"medium" tab label format not respected on reload when editing remotely

### ISSUE THREAD

**Issue by orn688** [microsoft/vscode-remote-release#891]
The `editor.workbench.labelFormat` setting, when set to `"medium"`, is supposed to show the relative path to each open tab's file within the tab, after the file basename (see [the docs](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_editor)). 

This generally works as promised when using the Remote Development Extension. However, when I reload or reopen a workspace that has open tabs, the `"medium"` value is not respected, and instead the entire absolute file path is shown in the tab. This is frustrating because I generally don't care about most of the absolute path, and it makes the tabs much bigger than necessary.

I first noticed this when sshing from a Mac into a remote Linux machine, and was able to reproduce it fairly minimally using Docker.

I confirmed that it does *not* happen when working in local workspaces, so I assume it's a problem with the remote development extension set.

- VSCode Version: 1.36.0
- Local OS Version: MacOS 10.14.5
- Remote OS Version: Ubuntu 18.04.2
- Remote Extension/Connection Type: Docker (also ssh)

Steps to Reproduce:

1. `docker run -it ubuntu --name vscode-test`.
2. Within the container, run `mkdir -p /vscode/a/b/ && echo "test" > /vscode/a/b/c.txt`
3. Run "Remote Containers: Attach to Running Container..." in VS Code and select the "vscode-test" container.
4. Go to settings and change the `workbench.editor.labelFormat` setting to "medium".
5. Select "Open Folder" and open the container's `/vscode` directory.
6. Open the `a/b/c.txt` file in a new tab. The tab should read "**c.txt** a/b", properly displaying the relative path as expected.
7. Reload the window.
8. The `c.txt` tab will now show the entire absolute path after the filename: "**c.txt** /vscode/a/b".
9. If you close and reopen the tab, it goes back to normal. (In practice, it's quite annoying to have to close and reopen every tab whenever I reopen a workspace.)

Steps 5-9 are shown here:
![vscode-bug](https://user-images.githubusercontent.com/15459200/60641036-db5b3900-9dde-11e9-9c85-c230722eb1cf.gif)

Does this issue occur when you try this locally?: no
Does this issue occur when you try this locally and all extensions are disabled?: no

**Comment by isidorn** [comment]
I have pushed a commit which should fix this, a couple of days ago.
Can you please try with the latest vscode insiders and let us know if the issue gets really fixed for you
https://code.visualstudio.com/insiders/

**Comment by orn688** [comment]
I tested with Docker and it looks good! I'll try with ssh tomorrow.

It still shows the full path briefly right after I reload the window. However, it quickly replaces it with the relative path, and I don't mind the delay.

Thanks for the quick fix!

**Comment by isidorn** [comment]
No problem, closing this then. If it works with Docker it should work with ssh, we use the same underlying components.
The quick replace is expacted (just the timing when the extension contributinos its label provider with rules for showing remote uris)

**Comment by orn688** [comment]
Confirmed that it's also fixed with ssh 😄
