### ISSUE TITLE
Error: self signed certificate. You may need to sign out and back in.

### ISSUE THREAD

**Issue by rmathieu25** [microsoft/vscode-remote-release#8954]
Hello,

Since yesterday, when I tried to use remote - tunnel to connect to a remote machine, I have a message telling me: "The extension 'Remote - Tunnels' wants you to sign in again using github. I allowed it but I have then the error message "Error self signed certificate. You may need to sign out and back in.' Even if I sign out and back in this error message persists. Even when I open the link in my browser after executing ./code tunnel I am running into an issue saying: "An unexpected error occurred that requires a reload of this page. The workbench failed to connect to the server (Error: Network Error)". 

I do not understand what is going on. Everything was working fine and I was actually connected to the VS code server and suddenly was disconnected and since then it is not possible anymore to connect to it.

**Comment by Pacalor** [comment]
Same issue for me

**Comment by rmathieu25** [comment]
I got it fixed yesterday as well but that does not work again today

**Comment by cnellington** [comment]
I have the same issue, is there any known fix?

**Comment by Pacalor** [comment]
Looks like any remote extension can be used right now, we need to wait until it's fixed

**Comment by rmathieu25** [comment]
Is there update on this issue? Still not working for me.

**Comment by Pacalor** [comment]
Unluckily no 😅, still not working

**Comment by Asmilex** [comment]
Same here. Tunnels have been dead for approximately a week or so.

**Comment by ennioferreirab** [comment]
I hope it works again

**Comment by cnellington** [comment]
The tunnel GUI in vscode seems broken still, but I've gotten tunnels working on some machines by using the CLI `code tunnel`. 

On other machines I'm still getting this error: 
```
$ code tunnel
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[2023-09-19 01:39:29] error error listing current tunnels: connection error: error sending request for url
(https://global.rel.tunnels.api.visualstudio.com/api/v1/tunnels?global=true&tags=vscode-server-launcher): 
error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify 
failed:../src/nssl-3.1.2-a1adf9ea87.clean/ssl/statem/statem_clnt.c:1889: (unable to get
local issuer certificate)
```
This would seem like an SSL issue, but `curl https://global.rel.tunnels.api.visualstudio.com` works fine on this machine. Proxying HTTP/HTTPS to another machine doesn't fix this either. Any idea what's going on?

**Comment by bamurtaugh** [comment]
@connor4312 @aeschli would be great to get your thoughts on this one.

**Comment by connor4312** [comment]
I was able to reproduce this by running the CLI on an image that lacked CA certificates. This should be resolved by install the CA certificates package for your platform, e.g. `apt install ca-certificates` on Debian distros. Please let me know if not.

We recently updated to OpenSSL 3.1 which likely surfaced this problem.

**Comment by pipoe2h** [comment]
@connor4312 I'm running Ubuntu 22.04 with already ca-certificates installed and still the same issue.

**Comment by marcoskirsch** [comment]
I am getting this error trying to connect to VSCode running on Windows 11, from VSCode running on macOS. Any instructions on clearing out the certificate or how to sign out would be great.

**Comment by Yc-Chen** [comment]
Same here, I'm running VSCode 1.85.1 on AlmaLinux.

**Comment by Jen1us** [comment]
i think it is a proxy setting issue. When i set the proxy Global Routing to Global(previous rule) the connecting problem got fixed immediately.

**Comment by marcoskirsch** [comment]
@Jen1us would you mind explaining in a bit more detail how to do this?

**Comment by Jen1us** [comment]
> @Jen1us would you mind explaining in a bit more detail how to do this?

The situation was same to you. I got this error when I was connecting vscode in Win11 from vscode.dev in safari. My iPad's proxy app is Shadowrocket that its Global routing gets setting to config. The issue got fixed when I change that setting to proxy.

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-remote-release/issues/9923
