### ISSUE TITLE
devcontainer.json not found on disallowed WSL UNC paths

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode-remote-release#9302]
Type: <b>Bug</b>

Attempting to do "Open Folder in Container" on Dev Containers 0.327.0 on a folder with an existing dev container configuration file appears to get confused:
`Dev Container configuration '.devcontainer/devcontainer.json' file already exists.`
The dialog offers options "cancel" (which does what it says) or "continue" (which ignores the supplied configuration and tries to ask me to select a configuration template).
In case it matters, the folder I'm opening is in a WSL filesystem (opening via a path like `\\wsl$\Ubuntu-20.04\home\<me>\...\<folder>`).

On extension version 0.321.0, this opened fine. Reopening the folder (in container) via the recents list works fine with either version.

Expected behaviour would be to *use* the supplied configuration rather than complaining about its existence and ignoring it. Could you investigate please?

Extension version: 0.327.0
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.80GB (9.16GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c245c5c5562756e74752d32302e30345c5c686f6d655c5c72616c6578616e64657237325c5c6769745c5c77735c5c6578706572696d656e74222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f72616c6578616e64657237322f6769742f77732f6578706572696d656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d/workspaces/experiment|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: experiment-dev|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 2999)|
|Memory (System)|100.44GB (93.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 2999)|
|Memory (System)|100.44GB (93.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: qev_taproto-dev|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 2999)|
|Memory (System)|100.44GB (93.47GB free)|
|VM|0%|
</details>

**Comment by denera** [comment]
I'm also experiencing this issue at the moment. Digging into the container log files, I see this:
```
[6388 ms] Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c).
[6388 ms] Start: Run: /bin/sh 
[6400 ms] Start: Run in host: echo ~
[6451 ms] /home/adener
[6451 ms] 
[6452 ms] Start: Run in host: id -un
[6505 ms] adener
[6505 ms] 
[6506 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'adener' || grep -E '^adener|^[^:]*:[^:]*:adener:' /etc/passwd || true)
[6558 ms] userEnvProbe: loginInteractiveShell (default)
[6558 ms] userEnvProbe: not found in cache
[6558 ms] userEnvProbe shell: /bin/bash
[6866 ms] userEnvProbe PATHs:
Probe:     '/home/adener/Developer/scripts/git-custom-commands:/home/adener/Developer/dotfiles/.pyenv/plugins/pyenv-virtualenv/shims:/home/adener/Developer/dotfiles/.pyenv/shims:/home/adener/Developer/dotfiles/.pyenv/bin:/usr/local/cuda/bin:/home/adener/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/p4v/bin/:/opt/pycharm-community-2020.3.3/bin'
Container: None
[6965 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[7021 ms] 1.43
[7493 ms] Start: Run: tar --no-same-owner -x -f -
[7568 ms] Start: Run: /home/adener/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/node /home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/adener/Developer/code/te-jax-dev --log-level debug --log-format json --config /home/adener/Developer/code/te-jax-dev/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root --additional-features {"extensions.verifySignature":false}
[7758 ms] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.2.0-36-generic x64.
[7758 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/adener/Developer/code/te-jax-dev --filter label=devcontainer.config_file=/home/adener/Developer/code/te-jax-dev/.devcontainer/devcontainer.json
[7779 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/adener/Developer/code/te-jax-dev
[7794 ms] Resolving Feature dependencies for 'extensions.verifySignature'...
[7795 ms] * Processing feature: extensions.verifySignature
[7795 ms] Legacy feature 'extensions.verifySignature' not supported. Please check https://containers.dev/features for replacements.
[7797 ms] Error: Legacy feature 'extensions.verifySignature' not supported. Please check https://containers.dev/features for replacements.
    at yJ (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:4619)
    at tC (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:6575)
    at Q (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:1751)
    at q7 (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:24126)
    at AC (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:26717)
    at Su (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:285:26943)
    at vu (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:1824)
    at async _eA (/home/adener/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:35175)
[7779 ms] Exit code 1
```

It looks like Dev Containers extension attempts to launch with a  `--additional-features {"extensions.verifySignature":false}` feature, which is no longer supported and errors out.

My `devcontainer.json` is very barebones because it uses a compose file:
```
{
    "name": "TE-JAX Development",
    "dockerComposeFile": [ "/home/adener/Developer/containers/docker-compose.yaml" ],
    "service": "te-jax-dev",
    "overrideCommand": false,
    "workspaceFolder": "/home/adener/Developer/code/te-jax-dev"
}
```

There's nothing in here that has anything to do with the `{"extensions.VerifySignature": false}` option. I also don't have that in my `settings.json` either. It appears to be hard-coded into Dev Containers, with no way to control/disable/override in the settings.

I'm wondering if Dev Containers could be mistaking this as an error from the `devcontainers.json` file, refusing to use what it sees as a faulty configuration, and instead asking the user to select a different container from its preconfigured options.

**Comment by AidanTweedy** [comment]
I just ran into this issue myself.

Try adding an `"initializeCommand"` to `devcontainer.json`, such as `"initializeCommand": "ls"`

For some reason, that works.

**Comment by rjra100** [comment]
> Digging into the container log files, I see this ...

Strange - I don't have any references to extensions.VerifySignature in my logs. The tail end of mine (after the userEnvProbe bits just has 
```
Container: None
[2023-12-14T09:47:23.593Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-14T09:47:23.698Z] Stop (105 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-14T09:47:23.698Z] 1.43
[2023-12-14T09:47:23.699Z] Start: Run in Host: wslpath -w /home/ralexander72/git/ws/qev_taproto
[2023-12-14T09:47:23.713Z] Stop (14 ms): Run in Host: wslpath -w /home/ralexander72/git/ws/qev_taproto
[2023-12-14T09:47:26.825Z] Start: Run in Host: wslpath -w /home/ralexander72/git/ws/qev_taproto/.devcontainer/devcontainer.json
[2023-12-14T09:47:26.833Z] Stop (8 ms): Run in Host: wslpath -w /home/ralexander72/git/ws/qev_taproto/.devcontainer/devcontainer.json
```
No obvious sign of problems in there at all.

> Try adding an "initializeCommand" to devcontainer.json, such as "initializeCommand": "ls"

Doesn't seem to help for me.

**Comment by rjra100** [comment]
Ah - digging about in *other* logfiles, I found this in exhost.log:
```
2023-12-14 09:47:27.859 [error] CodeExpectedError: cannot open file://wsl%24/Ubuntu-20.04/home/ralexander72/git/ws/qev_taproto/.devcontainer/devcontainer.json. Detail: Unable to read file '\\wsl$\Ubuntu-20.04\home\ralexander72\git\ws\qev_taproto\.devcontainer\devcontainer.json' (Unknown (FileSystemError): UNC host 'wsl$' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)
    at r.$tryOpenDocument (vscode-file://vscode-app/c:/Users/ralexander72/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2163:62448)
```

Adding `"security.allowedUNCHosts": ["wsl$"]` to the settings _and_ restarting VSCode (it doesn't seem to take effect immediately) fixes the issue for me. But I assume this isn't an intended change in behaviour, and having to dig about in the logs to figure out what it's complaining about certainly isn't ideal.

**Comment by tim-helloquickly** [comment]
Ran into this today as well on M2 Macbook Pro running ubuntu

**Comment by RM-Terrell** [comment]
Hitting this today also on an M2 Macbook running Sonoma 14.2. Also running extension version `v0.327.0`.

**Comment by puls** [comment]
I have this problem as well; downgrading VS Code to 1.84.2 while keeping the latest extension version fixed the problem for me.

**Comment by kisamoto** [comment]
> Try adding an `"initializeCommand"` to `devcontainer.json`, such as `"initializeCommand": "ls"`

Can confirm, added `"initializeCommand": "echo 'Hello World!'"` to `devcontainer.json` resolved the issue for me on both `v0.327.0` and `v0.328.0`

**Comment by ceberttylertech** [comment]
I also recently ran into this issue after updating VS code while using dev containers, but the initializeCommand did not correct the issue for me.

**Comment by valerii15298** [comment]
Have the same problem! Adding `"initializeCommand": "echo Initialize...."` to `devcontainer.json` fixed the problem

**Comment by chrmarti** [comment]
Moving the discussion for those where adding an `initializeCommand` works around the issue with the unexpected `--additional-features` option to https://github.com/microsoft/vscode-remote-release/issues/9325. Please provide additional information there. Thanks.

Keeping the discussion on `//wsl$/...` being broken here.

@bpasero @deepak1556 Did anything change in the UNC path check with the latest release? (Comment mentioning `"security.allowedUNCHosts": ["wsl$"]` makes it work above: https://github.com/microsoft/vscode-remote-release/issues/9302#issuecomment-1855614958.)

**Comment by bpasero** [comment]
Nothing changed from what I can tell. If you are accessing UNC paths in VS Code, you have to allow them via the `security.allowedUNCHosts` setting.

**Comment by deepak1556** [comment]
Yes nothing changed on the path check side, @rjra100 did you only start seeing the UNC host log for wsl with 1.85 or does [1.84](https://code.visualstudio.com/updates/v1_84) also report it ?

**Comment by chrmarti** [comment]
Can reproduce now. Something in the extension appears to have changed, investigating.

**Comment by deepak1556** [comment]
@chrmarti one thing that might be related, Node.js worker threads didn't respect the UNC path checks and they were addressed in `1.85`, if your extension relies on it then it wouldn't have error seen before but now it will as expected.

**Comment by chrmarti** [comment]
A bug fix in the extension now calls `vscode.workspace.findFiles()` also with WSL paths to discover devcontainer.json files in subfolders of `.devcontainer`. Previously we wouldn't discover these when they were on a WSL path.

I can improve the response from the extension for this case, but to get at all devcontainer.json files, we will either need the user to allow these UNC hosts or use Remote-WSL to first connect to WSL and then open the folder from there.

One can also open the UNC path in VS Code locally first and that would ask you if you want to add WSL to the allowed UNC hosts. Maybe the extension could do something similar.

**Comment by rsarrazin2** [comment]
Same here, usually starting vscode via `code .` from a WSL2 Terminal, now getting the error
```
[error] CodeExpectedError: cannot open file://wsl.localhost/Ubuntu/path/to/.devcontainer/devcontainer.json. Detail: Unable to read file '\\wsl.localhost\Ubuntu\path\to\.devcontainer\devcontainer.json' (Unknown (FileSystemError): UNC host 'wsl.localhost' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)
    at r.$tryOpenDocument (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2163:62448)
```

Using "Remote Development" extension pack v0.25.0 on vscode 1.85.1.

Setting `"security.allowedUNCHosts": ["wsl.localhost", "wsl$"]` works neither when set in `/C:/Users/user/AppData/Roaming/Code/User/settings.json` nor when set in `/home/user/.vscode-server/data/Machine/settings.json`.

Will update if I can narrow down a bit more.

**Comment by rsarrazin2** [comment]
> Will update if I can narrow down a bit more.

Important fact: After logging into our container registry (where the docker image pointed to in devcontainer.json is hosted), everything worked fine. Important: There was no need to pull anything, the image was already present locally.

I can't find any log at first sight that would hint at what's happening and why being able to connect to the container registry would be required despite the image's already being present.

**Comment by rjra100** [comment]
> A bug fix in the extension now calls `vscode.workspace.findFiles()` also with WSL paths to discover devcontainer.json files in subfolders of `.devcontainer`. Previously we wouldn't discover these when they were on a WSL path.

...and yet the content took effect... :)

> I can improve the response from the extension for this case, but to get at all devcontainer.json files, we will either need the user to allow these UNC hosts or use Remote-WSL to first connect to WSL and then open the folder from there.

Yeah, it's not particularly crazy to have it asks to have the UNC path approved; my problem was having to dig about in non-obvious logfiles to find what the problem was! If it could pop up the kind of approval dialog you get when you just open the UNC path directly, that'd be fine. If that's not possible, if it could at least indicate why it can't open the file, that'd help!

> One can also open the UNC path in VS Code locally first and that would ask you if you want to add WSL to the allowed UNC hosts. Maybe the extension could do something similar.

Might be worth noting that this is pretty much exactly what I ended up doing, but while the UNC path can be opened once permission is granted, it doesn't seem to allow the extension to have access until VSCode is restarted.

**Comment by nanoz** [comment]
On my end, I had this message because I was missing a .env file, after cloning one of my template repository. Adding the expected .env file in my .devcontainer/ folder fixed the problem.

**Comment by ulrichSchreiner** [comment]
hi,

i have the same problem with linux machine. my `.devcontainer/devcontainer.json`  is a symlink to another location (which is in a trusted folder).  creating a real file seems to work now.

is there a setting in vscode for linux which forbids symlinks? it looks like vscode sees the file but cannot use it.

**Comment by rbuckland** [comment]
> I just ran into this issue myself.
> 
> Try adding an `"initializeCommand"` to `devcontainer.json`, such as `"initializeCommand": "ls"`
> 
> For some reason, that works.

This did resolve the issue (added the `	"initializeCommand" : "ls",` 

Setup was 
- VS Code 1.85.1 on Ubuntu 22.04
- Dev Containers extension v0.327.0
- mono repo, but VSCode opened at a subfolder. 
```
.git
└── ...
docs        # <-- VScode workspace folder open here
└──.devcontainer
   └── devcontainer.json  
tools/containers/doc-tooling
└── Dockerfile
```

```
// devcontainer.json
{
	"name": "Document Writing",
	"build": {
		"context": "../../tools/containers/doc-tooling",
		"dockerfile": "../../tools/containers/doc-tooling/Dockerfile"
	},
	"initializeCommand" : "ls",
        ...
}
```

**Comment by engelberger** [comment]
Same issue here, but the "initializeCommand" to devcontainer.json, such as "initializeCommand": "ls" is not working for me

**Comment by chrmarti** [comment]
Fixing the UNC path issue here by detecting the case and looking up the config files through WSL. Please open separate issues for other problems. Thanks!

**Comment by chrmarti** [comment]
Fix is available in Dev Containers extension 0.330.0-pre-release.

Verification (requires WSL on Windows):
- Set up a devcontainer.json in a WSL folder.
  - Run `WSL: Connect to WSL`.
  - Open empty folder in WSL.
  - Run `Dev Containers: Add Dev Container Configuration Files`, pick any template.
  - Run `Remote: Close Remote Connection`.
- Remove any WSL entry from the `"security.allowedUNCHosts"` setting. Restart VS Code if there was one.
- In the local window: Run `Dev Containers: Open Folder in Container` and enter the UNC path to the WSL folder.
  - E.g.: `\\wsl.localhost\Ubuntu\home\chrmarti\devel\smktst`.
- Verify that the folder is opened in the dev container without any dialogs about the configuration file.

**Comment by irsyadpage** [comment]
> > Try adding an `"initializeCommand"` to `devcontainer.json`, such as `"initializeCommand": "ls"`
> 
> Can confirm, added `"initializeCommand": "echo 'Hello World!'"` to `devcontainer.json` resolved the issue for me on both `v0.327.0` and `v0.328.0`

Adding  `"initializeCommand"` is not working for me.



> Fix is available in Dev Containers extension 0.330.0-pre-release.
> 
> Verification (requires WSL on Windows):
> 
> * Set up a devcontainer.json in a WSL folder.
>   
>   * Run `WSL: Connect to WSL`.
>   * Open empty folder in WSL.
>   * Run `Dev Containers: Add Dev Container Configuration Files`, pick any template.
>   * Run `Remote: Close Remote Connection`.
> * Remove any WSL entry from the `"security.allowedUNCHosts"` setting. Restart VS Code if there was one.
> * In the local window: Run `Dev Containers: Open Folder in Container` and enter the UNC path to the WSL folder.
>   
>   * E.g.: `\\wsl.localhost\Ubuntu\home\chrmarti\devel\smktst`.
> * Verify that the folder is opened in the dev container without any dialogs about the configuration file.

This fix is still not working for me and my environment is:
- OS: Windows 10 x64
- VSCode version: 1.85.1
- Dev Containers version: v0.330.0 (Pre-Release)

**Comment by chrmarti** [comment]
@irsyadpage Could you open a new issue with the complete log? Yours might be a different bug. Thanks.

**Comment by irsyadpage** [comment]
@chrmarti Okay, I opened a new issue: #9381.

**Comment by rzhao271** [comment]
@chrmarti I'm getting the following on my Windows device on the second-last step.
I also didn't have any disallowed WSL UNC paths added during the verification.

![Path doesn't exist error while trying to open a folder in WSL](https://github.com/microsoft/vscode-remote-release/assets/7199958/f6253f1d-5d5a-4956-9d31-1f6107dbee57)

**Comment by chrmarti** [comment]
@rzhao271 Could you try with the OS folder picker? (I.e., turn off the simple file dialog in user setting.)
