### ISSUE TITLE
[Remote-SSH Bug]: 0.108 chokes on comments in an include in my ~/.ssh/config

### ISSUE THREAD

**Issue by mtovino-cloudflare** [microsoft/vscode-remote-release#9479]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

"Connect to host" and "Connect current window to host" show me a menu of hosts based on my ssh config.  
"Open Recent" on a remote workspace connects to the remote workspace

### Steps To Reproduce

Environment: macOS 14.3 (23D56) Apple M2 Pro 32GB RAM
vsCode1.86, SSH remote extension version 0.108
"Connect to host" and "Connect current window to host" do absolutely nothing aside from leave "picking SSH host" in the log. 
Trying "Open Recent" on a remote workspace yields an error in the lower right "Failed to connect to the remote extension host server (Error: Missing value for match criteria SETUP)"

All is well if I downgrade the plugin to 0.107.1 and reload. 

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
15:18:16.055] Log Level: 2
[15:18:16.060] VS Code version: 1.86.0
[15:18:16.060] Remote-SSH version: remote-ssh@0.108.0
[15:18:16.060] darwin arm64
[15:18:16.063] SSH Resolver called for "ssh-remote+tovino-office", attempt 1
[15:18:16.063] "remote.SSH.useLocalServer": true
[15:18:16.063] "remote.SSH.useExecServer": false
[15:18:16.064] "remote.SSH.path": undefined
[15:18:16.064] "remote.SSH.configFile": undefined
[15:18:16.064] "remote.SSH.useFlock": true
[15:18:16.064] "remote.SSH.lockfilesInTmp": false
[15:18:16.064] "remote.SSH.localServerDownload": auto
[15:18:16.064] "remote.SSH.remoteServerListenOnSocket": false
[15:18:16.064] "remote.SSH.showLoginTerminal": true
[15:18:16.064] "remote.SSH.defaultExtensions": []
[15:18:16.064] "remote.SSH.loglevel": 2
[15:18:16.064] "remote.SSH.enableDynamicForwarding": true
[15:18:16.064] "remote.SSH.enableRemoteCommand": false
[15:18:16.064] "remote.SSH.serverPickPortsFromRange": {}
[15:18:16.064] "remote.SSH.serverInstallPath": {}
[15:21:46.344] Picking SSH host
[15:21:55.426] Picking SSH host
```

</p>
</details>

### Anything else?

I have a screen recording but it's ~80MB in size, I'd be happy to upload it, email it, etc.

**Comment by mtovino-cloudflare** [comment]
<img width="1840" alt="Screenshot 2024-02-02 at 3 30 35 PM" src="https://github.com/microsoft/vscode-remote-release/assets/151655012/ee498a7b-4ad2-4cae-9a83-03ed87c4c723">

**Comment by mtovino-cloudflare** [comment]
Aha!   I figured out the problem.  0.108 is unhappy with comments in an include in my ~/.ssh/config. 

```
# CLOUDFLARE SETUP https://URL_REDACTED
Match all # CLOUDFLARE SETUP
    Include /Users/mtovino/.ssh/cloudflare/config # CLOUDFLARE SETUP

(additional configs hosts listed here)
```

I hesitate to mess with lines 1 - 3 , since Big Brother put them there and the comments may be meaningful.  So, I moved the rest of my configs to a separate file, and include that file as such:

```
# CLOUDFLARE SETUP https://URL_REDACTED
Match all # CLOUDFLARE SETUP
    Include /Users/mtovino/.ssh/cloudflare/config # CLOUDFLARE SETUP

Include /Users/mtovino/.ssh/mine/config
```

and then add:

```
    "remote.SSH.configFile": "/Users/mtovino/.ssh/mine/config"
```

to my user settings.  I am able to connect just fine now.

**Comment by mtovino-cloudflare** [comment]
Additionally... I noticed the syntax highlighting doesn't seem to recognize the comments in my include as comments... compare: 

 
<img width="1375" alt="Screenshot 2024-02-02 at 3 52 09 PM" src="https://github.com/microsoft/vscode-remote-release/assets/151655012/ea9a2329-9204-4a53-b8e7-b897883c7b46">

<img width="1419" alt="Screenshot 2024-02-02 at 3 52 14 PM" src="https://github.com/microsoft/vscode-remote-release/assets/151655012/d9f90479-a71c-4cae-9fae-9e3b30fc11eb">

**Comment by mtovino-cloudflare** [comment]
This is new behavior in 0.108; 0.107.1 has no trouble with the comments.

**Comment by kpi88** [comment]
0.108 is also failing to process wildcards in `include` statements; ex. `include ssh_config.d/*.conf` causes no hosts to appear in the Remote Explorer / Remotes window. Since this also involves the `include` statement, I have not filed a new issue.

**Comment by mtovino-cloudflare** [comment]
> Thanks! Filed upstream: [cyjake/ssh-config#73](https://github.com/cyjake/ssh-config/issues/73)

Many thanks!!

**Comment by lpsinger** [comment]
Another similar bug: cyjake/ssh-config#74.

**Comment by rzhao271** [comment]
Hi @mtovino-cloudflare, could you verify that the issue is now fixed with the latest Remote SSH pre-release extension?

**Comment by mtovino-cloudflare** [comment]
Hi @rzhao271 I tried using `v0.111.2024040515 (pre-release)`, and am still seeing the behavior that I originally reported.

**Comment by rzhao271** [comment]
Could you try again with the latest pre-release, `v0.112.2024042515 (pre-release)`?

**Comment by mtovino-cloudflare** [comment]
@rzhao271 I don't see that choice in the menu:

Would I need to run a pre-release version of vscode as well? 
<img width="1712" alt="Screenshot 2024-04-25 at 10 18 45 AM" src="https://github.com/microsoft/vscode-remote-release/assets/151655012/fc1830b0-3494-4931-8129-04a7f6995803">

**Comment by rzhao271** [comment]
Yep, you might need [VS Code Insiders](https://code.visualstudio.com/insiders/) to see newer pre-release versions.

**Comment by mtovino-cloudflare** [comment]
🎉 

I no longer observe the problem using code version:

Version: 1.89.0-insider
Commit: cc3429872df5e655abd12c233a9defbd15b0987d

and extension version: `v0.112.2024042515 (pre-release)`

🎉
