### ISSUE TITLE
Remote Explorer: SSH targets not appearing

### ISSUE THREAD

**Issue by MariamNakhle** [microsoft/vscode-remote-release#9497]
After using Remote Explorer for over a year without any issue, suddenly last week none of the ssh targets appear when I click on the Remote Explorer icon on the left side bar. The .ssh/config file still contains all the host names.

I tried uninstalling + reinstalling Remote Explorer and Remote-SSH extensions. I also uninstalled and reinstalled VScode.

Here are the versions I am using:

VScode version: 1.86.0
Remote - SSH version: v0.108.0
Remote Explorer version v0.4.1

**Comment by jamesps-ebi** [comment]
Same issue here. I rolled back to v0.107.1 and the SSH targets re-appeared for me.

**Comment by MariamNakhle** [comment]
Thanks, this worked for me too.

**Comment by CrustyPistachio** [comment]
Same issue here. Rolling back to v0.107.1 fixed it for me.

Issue occurs with these versions:
VS Code: 1.86.0
Remote - SSH: 0.108.0
Remote Explorer: 0.4.1
OS: Windows 10 Pro (22H2)

**Comment by Neeham** [comment]
Another issue to keep in mind, you may have to downgrade your VSCode to 1.85.2 if the server that you are SSHing to does not meet the minimum linux distribution requirement.

From the latest release notes:

> [Linux minimum requirements update](https://code.visualstudio.com/updates/v1_86#_linux-minimum-requirements-update)
> In this milestone, we have updated the toolchains to build our desktop client. From this release onwards, VS Code desktop is only compatible with Linux distributions based on glibc 2.28 or later, and glibcxx 3.4.25 or later, such as Debian 10, RHEL 8, or Ubuntu 20.04.
> 
> If you are unable to upgrade your Linux distribution, the recommended alternative is to use our [web client](https://code.visualstudio.com/docs/editor/vscode-web). If you would like to use the desktop version, then you can [download the VS Code release 1.85](https://code.visualstudio.com/updates/v1_85). Depending on your platform, make sure to disable updates to stay on that version. A good recommendation is to set up the installation with [Portable Mode](https://code.visualstudio.com/docs/editor/portable).

**Comment by tom-ami** [comment]
I'm having the same issue and noticed in the process explorer that it is doing DNS lookups for domains specified in my ssh config CanonicalDomains option.

To test if it is linked, I commented out CanonicalizeHostname and CanonicalDomainsin my ssh config. This seems to work around the issue and the list of remotes appears again.

Unfortunately I need this setting for other reasons, so it's not really a solution for me.

**Comment by rudiservo** [comment]
Same here, I got vs code from snap on ubuntu 22.04, no targets appear.

**Comment by isidorn** [comment]
Update to latest VS Code and this should be fixed. More details here https://github.com/microsoft/vscode/issues/203375

**Comment by rudiservo** [comment]
Not fixed, I have vscode 1.87 and remote-ssh 0.109, still the same issue.

**Comment by hsimonfroy** [comment]
Same issue, vscode 1.87 and remote-ssh 0.109

**Comment by isidorn** [comment]
Let me reopen just in case, and assign to @connor4312

**Comment by 1a1a11a** [comment]
I confirm `CanonicalDomains` is the issue

**Comment by alfa0112** [comment]
I have same issue in following environment.

OS: Windows 11
VSCode version: 1.95.3
Remote-SSH version: remote-ssh@0.115.1

SSH command, host resolution is working well in the console.

**Comment by joshspicer** [comment]
@alfa0112 , could you share what your configuration file looks like?  Does it help if you remove your hosts and put something simple in there, like:

```
Host myhost
    HostName 1.2.3.4
```

When you repro, can you also check the 'Output Channel' main/window/'extension host' logs and share anything peculiar
