### ISSUE TITLE
[Dev Containers]the local WSL starts automatically when connecting to a container on a REMOTE host

### ISSUE THREAD

**Issue by NirvanaCh** [microsoft/vscode-remote-release#9905]
I have very little memory on this host, so I'm working on a remote host. I often find that WSL starts up automatically.

Until I found this in the Dev Containers logs
```bash
...
[4358 ms] Start: Run: docker inspect --type container /beautiful_jepsen
[4516 ms] Start: Run: wsl -l -v
[4978 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c echo ~
[17414 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/user' && /bin/sh
[17423 ms] Start: Run in host: id -un
[17797 ms] user
...
```
I'm connecting to a container on a remote host, why do I need to turn on the local WSL？
The logs of the port forwarding made me think it had to be forwarded to WSL.
```bash
... 
[4512098 ms] Port forwarding 50684 > 46051 > 46051 stderr: Connection established
[4512117 ms] Port forwarding 50686 > 46051 > 46051 stderr: Connection established
[4512167 ms] Port forwarding 50688 > 46051 > 46051 stderr: Connection established
[4512201 ms] Port forwarding 50690 > 46051 > 46051 stderr: Connection established
...
```
After 'wsl --shutdown'
```bash
[2191307 ms] Host server terminated (code: 1, signal: null).
```
But the remote connection and port forwarding were not interrupted.

So turning on the local WSL doesn't do anything.

**Comment by NirvanaCh** [comment]
> Try disabling WSL services in the user settings: ![Image](https://private-user-images.githubusercontent.com/9205389/334336720-203bb47a-dffe-4923-85a3-c6aeba277187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDU3NjEsIm5iZiI6MTcxNjkwNTQ2MSwicGF0aCI6Ii85MjA1Mzg5LzMzNDMzNjcyMC0yMDNiYjQ3YS1kZmZlLTQ5MjMtODVhMy1jNmFlYmEyNzcxODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMTQxMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEzY2I3NDdjZDQwNmNlMGMyMDBjNDdmMzFhYzlmNTk2ZDM5ZGNmYzU5OGRlOTJmZDUwYTJkZmExNjQyYzI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tPoVB1TbKZ8zyBp_CE7I4L78-SIaNv6J9WKTa9BZ_d4) Does that help?

Yes, thank you so much, the issue is resolved. I'm sorry for taking up your time.

With this, I can use WSL services within the container, like ssh-agent, even if it's a remote container, right?

I‘d seen #9897 . I think, just for me, this should not be enabled by default. Perhaps a notification or prompt would be helpful?

**Comment by chrmarti** [comment]
> With this, I can use WSL services within the container, like ssh-agent, even if it's a remote container, right?

Correct. You still get the ssh-agent forwarded from Windows (if it is running) when you disable this setting.

> I‘d seen #9897 . I think, just for me, this should not be enabled by default. Perhaps a notification or prompt would be helpful?

We are trying to avoid adding more noise to the UI. I assume most users are fine with the default WSL distro starting and this user setting can be used to avoid it when needed. Thanks.
