### ISSUE TITLE
Remote-WSL: Reopen Folder in WSL not available in Command Palette if already in WSL

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-remote-release#998]
- VSCode Version: 1.37 Insiders
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install two Linux distros for WSL (Ubuntu, Debian)
2. Open a folder in Ubuntu

Remote-WSL: Reopen Folder in WSL is available from the Status bar command list but not from the Command Palette.

If you close the remote connection, the Reopen Folder in WSL command is available in both the Status bar command list and the Command Palette.

Reopen Folder in WSL is handy if you have opened a folder in the wrong distro and want to switch quickly to another distro. Having to click and use the Status bar list is inconvenient for keyboard use.

**Comment by aeschli** [comment]
This works for me (likely fixed in the meantime)

**Comment by gregvanl** [comment]
Still seems to repro for me.

From the Remote Status bar button:

![image](https://user-images.githubusercontent.com/12818376/67819777-03a52c80-fa8d-11e9-9c0a-9e622976fa22.png)

From the Command Palette:

![image](https://user-images.githubusercontent.com/12818376/67819820-2a636300-fa8d-11e9-8bff-812de3160890.png)

Only Remote-WSL: Reopen Folder in Windows is available from the Command Palette.

**Comment by aeschli** [comment]
I pushed a fix.

**Comment by dbaeumer** [comment]
Reopening. I am still seeing the entry in todays insider.

<img width="514" alt="capture" src="https://user-images.githubusercontent.com/1931590/100999406-0b22e900-355d-11eb-8202-0e70037df081.png">

**Comment by aeschli** [comment]
@dbaeumer If `Reopen Folder in WSL` shows up, then that's good. The issue that `Reopen Folder in WSL` did not show in the command palette. Can you verify if it is now available also in the command palette? Both when the window is a WSL window or a local window.

**Comment by dbaeumer** [comment]
Sorry. Misread.

**Comment by dbaeumer** [comment]
Verified according to your steps above.
